//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildHierarchy::deltas
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildHierarchy::rangeLefts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildHierarchy::rangeRights
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildHierarchy::lowers
// {
//
//   struct PackedNodeHalf
//   {
//       
//       float x;                       // Offset:    0
//       float y;                       // Offset:    4
//       float z;                       // Offset:    8
//       uint ib;                       // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for BuildHierarchy::uppers
// {
//
//   struct PackedNodeHalf
//   {
//       
//       float x;                       // Offset:    0
//       float y;                       // Offset:    4
//       float z;                       // Offset:    8
//       uint ib;                       // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for BuildHierarchy::numChildren
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildHierarchy::root
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// BuildHierarchy::deltas            texture  struct         r/o             t2      1 
// BuildHierarchy::rangeLefts            UAV  struct         r/w             u0      1 
// BuildHierarchy::rangeRights           UAV  struct         r/w             u1      1 
// BuildHierarchy::lowers                UAV  struct         r/w             u2      1 
// BuildHierarchy::uppers                UAV  struct         r/w             u3      1 
// BuildHierarchy::numChildren           UAV  struct         r/w             u4      1 
// BuildHierarchy::root                  UAV  struct         r/w             u5      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t2, 4
dcl_uav_structured_glc u0, 4
dcl_uav_structured_glc u1, 4
dcl_uav_structured_glc u2, 16
dcl_uav_structured_glc u3, 16
dcl_uav_structured_glc u4, 4
dcl_uav_structured_glc u5, 4
dcl_input vThreadID.x
dcl_temps 6
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
if_nz r0.x
  iadd r0.x, cb0[0].x, l(-1)
  mov r1.yw, l(0,0,0,0)
  mov r2.y, l(0)
  mov r1.x, vThreadID.x
  loop 
    imm_atomic_or r3.x, u0, r1.xyxx, l(0)
    imm_atomic_or r4.x, u1, r1.xyxx, l(0)
    ieq r0.y, r3.x, l(0)
    ieq r0.z, r0.x, r4.x
    and r0.z, r0.z, r0.y
    if_nz r0.z
      store_structured u5.x, l(0), l(0), r1.x
      ret 
    endif 
    ine r0.z, r0.x, r4.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r4.x, l(0), t2.xxxx
    iadd r2.z, r3.x, l(-1)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.z, r2.z, l(0), t2.xxxx
    ilt r0.w, r0.w, r2.z
    and r0.z, r0.w, r0.z
    or r0.y, r0.z, r0.y
    if_nz r0.y
      iadd r1.z, r4.x, cb0[0].x
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.y, r1.z, l(12), u2.xxxx
      and r0.y, r0.y, l(0x80000000)
      or r0.y, r1.x, r0.y
      store_structured u2.x, r1.z, l(12), r0.y
      imm_atomic_exch r5.x, u0, r1.zwzz, r3.x
      imm_atomic_iadd r5.x, u4, r1.zwzz, l(1)
      mov r1.x, r1.z
    else 
      iadd r0.y, r3.x, cb0[0].x
      iadd r2.x, r0.y, l(-1)
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.y, r2.x, l(12), u3.xxxx
      and r0.y, r0.y, l(0x80000000)
      or r0.y, r1.x, r0.y
      store_structured u3.x, r2.x, l(12), r0.y
      imm_atomic_exch r3.x, u1, r2.xyxx, r4.x
      imm_atomic_iadd r5.x, u4, r2.xyxx, l(1)
      mov r1.x, r2.x
    endif 
    ieq r0.y, r5.x, l(1)
    if_nz r0.y
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.y, r1.x, l(12), u2.xxxx
      and r3.w, r0.y, l(0x7fffffff)
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.y, r1.x, l(12), u3.xxxx
      and r4.w, r0.y, l(0x7fffffff)
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, r3.w, l(0), u2.xxyz
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xzw, r4.w, l(0), u2.xxyz
      min r3.xyz, r0.yzwy, r2.xzwx
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, r3.w, l(0), u3.xxyz
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xzw, r4.w, l(0), u3.xxyz
      max r4.xyz, r0.yzwy, r2.xzwx
      store_structured u2.xyzw, r1.x, l(0), r3.xyzw
      store_structured u3.xyzw, r1.x, l(0), r4.xyzw
    else 
      ret 
    endif 
  endloop 
endif 
ret 
// Approximately 63 instruction slots used
