//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for ComputeTotalBounds::itemLowers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::itemUppers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::writeBoundsLower
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::writeBoundsUpper
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ComputeTotalBounds::itemLowers    texture  struct         r/o             t0      1 
// ComputeTotalBounds::itemUppers    texture  struct         r/o             t1      1 
// ComputeTotalBounds::writeBoundsLower        UAV  struct         r/w             u0      1 
// ComputeTotalBounds::writeBoundsUpper        UAV  struct         r/w             u1      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_input vThreadID.x
dcl_temps 3
dcl_tgsm_structured g0, 12, 256
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t0.xxyz
movc r0.yzw, r0.xxxx, r0.yyzw, l(0,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000)
store_structured g0.xyz, vThreadIDInGroup.x, l(0), r0.yzwy
mov r0.y, l(128)
loop 
  uge r0.z, l(0), r0.y
  breakc_nz r0.z
  sync_g_t
  ult r0.z, vThreadIDInGroup.x, r0.y
  if_nz r0.z
    ld_structured r1.xyz, vThreadIDInGroup.x, l(0), g0.xyzx
    iadd r0.z, r0.y, vThreadIDInGroup.x
    ld_structured r2.xyz, r0.z, l(0), g0.xyzx
    min r1.xyz, r1.xyzx, r2.xyzx
    store_structured g0.xyz, vThreadIDInGroup.x, l(0), r1.xyzx
  endif 
  ushr r0.y, r0.y, l(1)
endloop 
sync_g_t
ld_structured r1.xyz, l(0), l(0), g0.xyzx
sync_g_t
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t1.xxyz
movc r0.xyz, r0.xxxx, r0.yzwy, l(-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,0)
store_structured g0.xyz, vThreadIDInGroup.x, l(0), r0.xyzx
mov r0.x, l(128)
loop 
  uge r0.y, l(0), r0.x
  breakc_nz r0.y
  sync_g_t
  ult r0.y, vThreadIDInGroup.x, r0.x
  if_nz r0.y
    ld_structured r0.yzw, vThreadIDInGroup.x, l(0), g0.xxyz
    iadd r2.x, r0.x, vThreadIDInGroup.x
    ld_structured r2.xyz, r2.x, l(0), g0.xyzx
    max r0.yzw, r0.yyzw, r2.xxyz
    store_structured g0.xyz, vThreadIDInGroup.x, l(0), r0.yzwy
  endif 
  ushr r0.x, r0.x, l(1)
endloop 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.xyz, l(0), l(0), g0.xyzx
  mov r1.w, l(0)
  store_structured u0.xyzw, vThreadGroupID.x, l(0), r1.xyzw
  mov r0.w, l(0)
  store_structured u1.xyzw, vThreadGroupID.x, l(0), r0.xyzw
endif 
ret 
// Approximately 49 instruction slots used
