//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// Resource bind info for ComputeTotalInvEdges::totalLower
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for ComputeTotalInvEdges::totalUpper
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for ComputeTotalInvEdges::totalInvEdges
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ComputeTotalInvEdges::totalLower    texture  struct         r/o             t0      1 
// ComputeTotalInvEdges::totalUpper    texture  struct         r/o             t1      1 
// ComputeTotalInvEdges::totalInvEdges        UAV  struct         r/w             u0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 12
dcl_resource_structured t1, 12
dcl_uav_structured u0, 12
dcl_temps 2
dcl_thread_group 1, 1, 1
ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r0.xyz, l(0), l(0), t1.xyzx
ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r1.xyz, l(0), l(0), t0.xyzx
add r0.xyz, r0.xyzx, -r1.xyzx
add r0.xyz, r0.xyzx, l(0.000100, 0.000100, 0.000100, 0.000000)
div r0.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), r0.xyzx
store_structured u0.xyz, l(0), l(0), r0.xyzx
ret 
// Approximately 7 instruction slots used
