//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateKeyDeltas::deltas
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CalculateKeyDeltas::keys          texture    uint         buf             t0      1 
// CalculateKeyDeltas::deltas            UAV  struct         r/w             u0      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_buffer (uint,uint,uint,uint) t0
dcl_uav_structured u0, 4
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 256, 1, 1
iadd r0.x, cb0[0].x, l(-1)
ilt r0.x, vThreadID.x, r0.x
if_nz r0.x
  ld_indexable(buffer)(uint,uint,uint,uint) r0.x, vThreadID.xxxx, t0.xyzw
  iadd r0.y, vThreadID.x, l(1)
  ld_indexable(buffer)(uint,uint,uint,uint) r0.y, r0.yyyy, t0.yxzw
  xor r0.x, r0.y, r0.x
  store_structured u0.x, vThreadID.x, l(0), r0.x
endif 
ret 
// Approximately 10 instruction slots used
