//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateMortonCodes::itemLowers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateMortonCodes::itemUppers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateMortonCodes::gridLower
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for CalculateMortonCodes::gridInvEdges
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CalculateMortonCodes::itemLowers    texture  struct         r/o             t0      1 
// CalculateMortonCodes::itemUppers    texture  struct         r/o             t1      1 
// CalculateMortonCodes::gridLower    texture  struct         r/o             t2      1 
// CalculateMortonCodes::gridInvEdges    texture  struct         r/o             t3      1 
// CalculateMortonCodes::indices         UAV    uint         buf             u0      1 
// CalculateMortonCodes::keys            UAV    uint         buf             u1      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 12
dcl_resource_structured t3, 12
dcl_uav_typed_buffer (uint,uint,uint,uint) u0
dcl_uav_typed_buffer (uint,uint,uint,uint) u1
dcl_input vThreadID.x
dcl_temps 2
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), t0.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(0), t1.xyzx
  add r0.xyz, r0.zyxz, r1.zyxz
  ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r1.xyz, l(0), l(0), t2.xyzx
  mad r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -r1.zyxz
  ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r1.xyz, l(0), l(0), t3.xyzx
  mul r0.xyz, r0.xyzx, r1.zyxz
  mul r0.xyz, r0.xyzx, l(512.000000, 512.000000, 512.000000, 0.000000)
  round_z r0.xyz, r0.xyzx
  min r0.xyz, r0.xyzx, l(511.000000, 511.000000, 511.000000, 0.000000)
  max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  ftou r0.xyz, r0.xyzx
  ishl r1.xyz, r0.xyzx, l(16, 16, 16, 0)
  xor r0.xyz, r0.xyzx, r1.xyzx
  and r1.xyz, r0.xyzx, l(0x010000ff, 0x010000ff, 0x010000ff, 0)
  bfi r0.xyz, l(8, 8, 8, 0), l(8, 8, 8, 0), r0.xyzx, l(0, 0, 0, 0)
  xor r0.xyz, r0.xyzx, r1.xyzx
  and r0.xyz, r0.xyzx, l(0x0100f00f, 0x0100f00f, 0x0100f00f, 0)
  ishl r1.xyz, r0.xyzx, l(4, 4, 4, 0)
  xor r0.xyz, r0.xyzx, r1.xyzx
  and r0.xyz, r0.xyzx, l(0x010c30c3, 0x010c30c3, 0x010c30c3, 0)
  ishl r1.xyz, r0.xyzx, l(2, 2, 2, 0)
  xor r0.xyz, r0.xyzx, r1.xyzx
  ishl r0.xy, r0.xyxx, l(2, 1, 0, 0)
  and r0.xy, r0.xyxx, l(0x04924924, 0x02492492, 0, 0)
  iadd r0.x, r0.y, r0.x
  and r0.y, r0.z, l(0x01249249)
  iadd r0.x, r0.y, r0.x
  mov r0.y, vThreadID.x
else 
  mov r0.xy, l(-1,-1,0,0)
endif 
store_uav_typed u1.xyzw, vThreadID.xxxx, r0.xxxx
store_uav_typed u0.xyzw, vThreadID.xxxx, r0.yyyy
ret 
// Approximately 37 instruction slots used
