//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for ComputeTotalBounds::readBoundsLower
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::readBoundsUpper
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::totalLower
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for ComputeTotalBounds::totalUpper
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for ComputeTotalBounds::totalInvEdges
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ComputeTotalBounds::readBoundsLower    texture  struct         r/o             t2      1 
// ComputeTotalBounds::readBoundsUpper    texture  struct         r/o             t3      1 
// ComputeTotalBounds::totalLower        UAV  struct         r/w             u2      1 
// ComputeTotalBounds::totalUpper        UAV  struct         r/w             u3      1 
// ComputeTotalBounds::totalInvEdges        UAV  struct         r/w             u4      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t2, 16
dcl_resource_structured t3, 16
dcl_uav_structured u2, 12
dcl_uav_structured u3, 12
dcl_uav_structured u4, 12
dcl_temps 5
dcl_thread_group 1, 1, 1
iadd r0.x, cb0[0].x, l(255)
ushr r0.x, r0.x, l(8)
iadd r0.x, r0.x, l(255)
ushr r0.x, r0.x, l(8)
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, l(0), l(0), t2.xxyz
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyz, l(0), l(0), t3.xyzx
mov r2.xyz, r0.yzwy
mov r3.xyz, r1.xyzx
mov r1.w, l(1)
loop 
  ige r2.w, r1.w, r0.x
  breakc_nz r2.w
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyz, r1.w, l(0), t2.xyzx
  min r2.xyz, r2.xyzx, r4.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyz, r1.w, l(0), t3.xyzx
  max r3.xyz, r3.xyzx, r4.xyzx
  iadd r1.w, r1.w, l(1)
endloop 
store_structured u2.xyz, l(0), l(0), r2.xyzx
store_structured u3.xyz, l(0), l(0), r3.xyzx
add r0.xyz, -r2.xyzx, r3.xyzx
add r0.xyz, r0.xyzx, l(0.000100, 0.000100, 0.000100, 0.000000)
div r0.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), r0.xyzx
store_structured u4.xyz, l(0), l(0), r0.xyzx
ret 
// Approximately 25 instruction slots used
