//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for ComputeTotalBounds::itemLowers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::itemUppers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::writeBoundsLower
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::writeBoundsUpper
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ComputeTotalBounds::itemLowers    texture  struct         r/o             t0      1 
// ComputeTotalBounds::itemUppers    texture  struct         r/o             t1      1 
// ComputeTotalBounds::writeBoundsLower        UAV  struct         r/w             u0      1 
// ComputeTotalBounds::writeBoundsUpper        UAV  struct         r/w             u1      1 
// AmdDxExtShaderIntrinsicsUAV           UAV    byte         r/w             u7      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_uav_raw u7
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_input vThreadID.x
dcl_temps 4
dcl_tgsm_structured g0, 12, 256
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t0.xxyz
movc r0.yzw, r0.xxxx, r0.yyzw, l(0,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000)
and r1.x, vThreadIDInGroup.x, l(31)
ishr r1.y, vThreadIDInGroup.x, l(5)
imm_atomic_cmp_exch r2.x, u7, l(0x50401f04), r0.y, l(0)
imm_atomic_cmp_exch r2.y, u7, l(0x50401f04), r0.z, l(0)
imm_atomic_cmp_exch r2.z, u7, l(0x50401f04), r0.w, l(0)
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_cmp_exch r2.x, u7, l(0x50201f04), r0.y, l(0)
imm_atomic_cmp_exch r2.y, u7, l(0x50201f04), r0.z, l(0)
imm_atomic_cmp_exch r2.z, u7, l(0x50201f04), r0.w, l(0)
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_cmp_exch r2.x, u7, l(0x50101f04), r0.y, l(0)
imm_atomic_cmp_exch r2.y, u7, l(0x50101f04), r0.z, l(0)
imm_atomic_cmp_exch r2.z, u7, l(0x50101f04), r0.w, l(0)
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_cmp_exch r2.x, u7, l(0x50081f04), r0.y, l(0)
imm_atomic_cmp_exch r2.y, u7, l(0x50081f04), r0.z, l(0)
imm_atomic_cmp_exch r2.z, u7, l(0x50081f04), r0.w, l(0)
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_cmp_exch r2.x, u7, l(0x50041f04), r0.y, l(0)
imm_atomic_cmp_exch r2.y, u7, l(0x50041f04), r0.z, l(0)
imm_atomic_cmp_exch r2.z, u7, l(0x50041f04), r0.w, l(0)
if_z r1.x
  min r0.yzw, r0.yyzw, r2.xxyz
  store_structured g0.xyz, r1.y, l(0), r0.yzwy
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.yzw, l(0), l(0), g0.xxyz
  ld_structured r2.xyz, l(1), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(2), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(3), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(4), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(5), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(6), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(7), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  store_structured g0.xyz, l(0), l(0), r0.yzwy
endif 
sync_g_t
ld_structured r2.xyz, l(0), l(0), g0.xyzx
sync_g_t
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t1.xxyz
movc r0.xyz, r0.xxxx, r0.yzwy, l(-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,0)
imm_atomic_cmp_exch r3.x, u7, l(0x50401f04), r0.x, l(0)
imm_atomic_cmp_exch r3.y, u7, l(0x50401f04), r0.y, l(0)
imm_atomic_cmp_exch r3.z, u7, l(0x50401f04), r0.z, l(0)
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_cmp_exch r3.x, u7, l(0x50201f04), r0.x, l(0)
imm_atomic_cmp_exch r3.y, u7, l(0x50201f04), r0.y, l(0)
imm_atomic_cmp_exch r3.z, u7, l(0x50201f04), r0.z, l(0)
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_cmp_exch r3.x, u7, l(0x50101f04), r0.x, l(0)
imm_atomic_cmp_exch r3.y, u7, l(0x50101f04), r0.y, l(0)
imm_atomic_cmp_exch r3.z, u7, l(0x50101f04), r0.z, l(0)
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_cmp_exch r3.x, u7, l(0x50081f04), r0.x, l(0)
imm_atomic_cmp_exch r3.y, u7, l(0x50081f04), r0.y, l(0)
imm_atomic_cmp_exch r3.z, u7, l(0x50081f04), r0.z, l(0)
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_cmp_exch r3.x, u7, l(0x50041f04), r0.x, l(0)
imm_atomic_cmp_exch r3.y, u7, l(0x50041f04), r0.y, l(0)
imm_atomic_cmp_exch r3.z, u7, l(0x50041f04), r0.z, l(0)
if_z r1.x
  max r0.xyz, r0.xyzx, r3.xyzx
  store_structured g0.xyz, r1.y, l(0), r0.xyzx
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.xyz, l(0), l(0), g0.xyzx
  ld_structured r1.xyz, l(1), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(2), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(3), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(4), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(5), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(6), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(7), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  store_structured g0.xyz, l(0), l(0), r0.xyzx
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.xyz, l(0), l(0), g0.xyzx
  mov r2.w, l(0)
  store_structured u0.xyzw, vThreadGroupID.x, l(0), r2.xyzw
  mov r0.w, l(0)
  store_structured u1.xyzw, vThreadGroupID.x, l(0), r0.xyzw
endif 
ret 
// Approximately 103 instruction slots used
