//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildLeaves::itemLowers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for BuildLeaves::itemUppers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for BuildLeaves::rangeLefts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildLeaves::rangeRights
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for BuildLeaves::lowers
// {
//
//   struct PackedNodeHalf
//   {
//       
//       float x;                       // Offset:    0
//       float y;                       // Offset:    4
//       float z;                       // Offset:    8
//       uint ib;                       // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for BuildLeaves::uppers
// {
//
//   struct PackedNodeHalf
//   {
//       
//       float x;                       // Offset:    0
//       float y;                       // Offset:    4
//       float z;                       // Offset:    8
//       uint ib;                       // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// BuildLeaves::itemLowers           texture  struct         r/o             t0      1 
// BuildLeaves::itemUppers           texture  struct         r/o             t1      1 
// BuildLeaves::indices              texture    uint         buf             t2      1 
// BuildLeaves::rangeLefts               UAV  struct         r/w             u0      1 
// BuildLeaves::rangeRights              UAV  struct         r/w             u1      1 
// BuildLeaves::lowers                   UAV  struct         r/w             u2      1 
// BuildLeaves::uppers                   UAV  struct         r/w             u3      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_buffer (uint,uint,uint,uint) t2
dcl_uav_structured u0, 4
dcl_uav_structured u1, 4
dcl_uav_structured u2, 16
dcl_uav_structured u3, 16
dcl_input vThreadID.x
dcl_temps 3
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
if_nz r0.x
  ld_indexable(buffer)(uint,uint,uint,uint) r0.x, vThreadID.xxxx, t2.xyzw
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyz, r0.x, l(0), t0.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, r0.x, l(0), t1.xyzx
  and r2.w, r0.x, l(0x7fffffff)
  bfi r1.w, l(31), l(0), r0.x, l(0x80000000)
  store_structured u2.xyzw, vThreadID.x, l(0), r1.xyzw
  store_structured u3.xyzw, vThreadID.x, l(0), r2.xyzw
  store_structured u0.x, vThreadID.x, l(0), vThreadID.x
  store_structured u1.x, vThreadID.x, l(0), vThreadID.x
endif 
ret 
// Approximately 13 instruction slots used
