//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer constBVH
// {
//
//   int gNumItems;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for ComputeTotalBounds::readBoundsLower
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::readBoundsUpper
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::writeBoundsLower
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTotalBounds::writeBoundsUpper
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for g_NvidiaExt
// {
//
//   struct NvShaderExtnStruct
//   {
//       
//       uint opcode;                   // Offset:    0
//       uint rid;                      // Offset:    4
//       uint sid;                      // Offset:    8
//       uint4 dst1u;                   // Offset:   12
//       uint4 padding0[3];             // Offset:   28
//       uint4 src0u;                   // Offset:   76
//       uint4 src1u;                   // Offset:   92
//       uint4 src2u;                   // Offset:  108
//       uint4 dst0u;                   // Offset:  124
//       uint markUavRef;               // Offset:  140
//       float padding1[28];            // Offset:  144
//
//   } $Element;                        // Offset:    0 Size:   256
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ComputeTotalBounds::readBoundsLower    texture  struct         r/o             t2      1 
// ComputeTotalBounds::readBoundsUpper    texture  struct         r/o             t3      1 
// ComputeTotalBounds::writeBoundsLower        UAV  struct         r/w             u0      1 
// ComputeTotalBounds::writeBoundsUpper        UAV  struct         r/w             u1      1 
// g_NvidiaExt                           UAV  struct     r/w+cnt             u7      1 
// constBVH                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t2, 16
dcl_resource_structured t3, 16
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_uav_structured_opc u7, 256
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_input vThreadID.x
dcl_temps 6
dcl_tgsm_structured g0, 12, 8
dcl_thread_group 256, 1, 1
iadd r0.x, cb0[0].x, l(255)
ushr r0.x, r0.x, l(8)
ilt r0.x, vThreadID.x, r0.x
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t2.xxyz
movc r0.yzw, r0.xxxx, r0.yyzw, l(0,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000)
and r1.x, vThreadIDInGroup.x, l(31)
ishr r1.y, vThreadIDInGroup.x, l(5)
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,1,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,1,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,1,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,2,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,2,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,2,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,4,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,4,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,4,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,8,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,8,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,8,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,16,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,16,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,16,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
if_z r1.x
  min r0.yzw, r0.yyzw, r2.xxyz
  store_structured g0.xyz, r1.y, l(0), r0.yzwy
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.yzw, l(0), l(0), g0.xxyz
  ld_structured r2.xyz, l(1), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(2), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(3), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(4), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(5), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(6), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(7), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  store_structured g0.xyz, l(0), l(0), r0.yzwy
endif 
sync_g_t
ld_structured r2.xyz, l(0), l(0), g0.xyzx
sync_g_t
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t3.xxyz
movc r0.xyz, r0.xxxx, r0.yzwy, l(-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,0)
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,1,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,1,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,1,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,2,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,2,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,2,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,4,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,4,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,4,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,8,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,8,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,8,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,16,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,16,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,16,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
if_z r1.x
  max r0.xyz, r0.xyzx, r3.xyzx
  store_structured g0.xyz, r1.y, l(0), r0.xyzx
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.xyz, l(0), l(0), g0.xyzx
  ld_structured r1.xyz, l(1), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(2), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(3), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(4), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(5), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(6), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(7), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  store_structured g0.xyz, l(0), l(0), r0.xyzx
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.xyz, l(0), l(0), g0.xyzx
  mov r2.w, l(0)
  store_structured u0.xyzw, vThreadGroupID.x, l(0), r2.xyzw
  mov r0.w, l(0)
  store_structured u1.xyzw, vThreadGroupID.x, l(0), r0.xyzw
endif 
ret 
// Approximately 255 instruction slots used
