//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer SpringsGenerateIndices::consts
// {
//
//   uint SpringsGenerateIndices::gNumSprings;// Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SpringsGenerateIndices::indices        UAV    uint         buf             u0      1 
// SpringsGenerateIndices::consts    cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_uav_typed_buffer (uint,uint,uint,uint) u0
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 256, 1, 1
ishl r0.x, cb0[0].x, l(1)
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  store_uav_typed u0.xyzw, vThreadID.xxxx, vThreadID.xxxx
endif 
ret 
// Approximately 6 instruction slots used
