//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for UpdateDiffuseParticles::numDiffuseParticles
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for UpdateDiffuseParticles::cellBucketStarts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for UpdateDiffuseParticles::cellBucketEnds
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for UpdateDiffuseParticles::contactCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for UpdateDiffuseParticles::sortedNewPositionsTex
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for UpdateDiffuseParticles::sortedNewVelocitiesTex
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for UpdateDiffuseParticles::gBounds
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for UpdateDiffuseParticles::diffusePositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for UpdateDiffuseParticles::diffuseVelocities
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// UpdateDiffuseParticles::numDiffuseParticles    texture  struct         r/o             t0      1 
// UpdateDiffuseParticles::cellBucketStarts    texture  struct         r/o             t1      1 
// UpdateDiffuseParticles::cellBucketEnds    texture  struct         r/o             t2      1 
// UpdateDiffuseParticles::contactCounts    texture  struct         r/o             t3      1 
// UpdateDiffuseParticles::sortedNewPositionsTex    texture  struct         r/o             t4      1 
// UpdateDiffuseParticles::sortedNewVelocitiesTex    texture  struct         r/o             t5      1 
// UpdateDiffuseParticles::gBounds    texture  struct         r/o             t7      1 
// UpdateDiffuseParticles::diffusePositions        UAV  struct         r/w             u0      1 
// UpdateDiffuseParticles::diffuseVelocities        UAV  struct         r/w             u1      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[32], dynamicIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 4
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_resource_structured t4, 16
dcl_resource_structured t5, 16
dcl_resource_structured t7, 12
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_input vThreadID.x
dcl_temps 7
dcl_thread_group 256, 1, 1
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, l(0), l(0), t0.xxxx
ilt r0.x, vThreadID.x, r0.x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), u0.xyzw
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(0), u1.xyzx
  ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r2.xyz, l(0), l(0), t7.xyzx
  add r2.xyz, r0.xyzx, -r2.xyzx
  mul r2.xyz, r2.xyzx, cb0[24].zzzz
  ftoi r2.xyz, r2.xyzx
  bfi r2.yz, l(0, 7, 7, 0), l(0, 14, 7, 0), r2.zzyz, l(0, 0, 0, 0)
  iadd r1.w, r2.y, r2.z
  bfi r1.w, l(7), l(0), r2.x, r1.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.x, r1.w, l(0), t1.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r1.w, l(0), t2.xxxx
  mov r2.yzw, l(0,0,0,0)
  mov r3.xy, l(0,0,0,0)
  mov r3.z, r2.x
  loop 
    ige r3.w, r3.z, r1.w
    breakc_nz r3.w
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyz, r3.z, l(0), t4.xyzx
    add r4.xyz, r0.xyzx, -r4.xyzx
    dp3 r3.w, r4.xyzx, r4.xyzx
    lt r4.x, r3.w, cb0[8].z
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.yzw, r3.z, l(0), t5.xxyz
    mad r3.w, -r3.w, cb0[8].w, l(1.000000)
    add r5.y, r3.w, r3.y
    mad r4.yzw, r4.yyzw, r3.wwww, r2.yyzw
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.z, l(0), t3.xxxx
    movc r5.x, r3.x, r3.x, r3.w
    movc r2.yzw, r4.xxxx, r4.yyzw, r2.yyzw
    movc r3.xy, r4.xxxx, r5.xyxx, r3.xyxx
    iadd r3.z, r3.z, l(1)
  endloop 
  div r2.xyz, r2.yzwy, r3.yyyy
  ige r1.w, r3.x, cb0[15].w
  mul r3.xyz, cb0[15].yyyy, cb0[16].xyzx
  mad r3.xyz, -r3.xyzx, cb0[27].zzzz, r1.xyzx
  add r2.xyz, -r1.xyzx, r2.xyzx
  mad r2.xyz, cb0[15].zzzz, r2.xyzx, r3.xyzx
  dp3 r2.w, r2.xyzx, r2.xyzx
  rsq r3.x, r2.w
  mul r3.y, cb0[27].w, cb0[27].w
  lt r2.w, r3.y, r2.w
  mul r3.x, r3.x, cb0[27].w
  mul r3.xzw, r2.xxyz, r3.xxxx
  movc r2.xyz, r2.wwww, r3.xzwx, r2.xyzx
  mad r3.xzw, r2.xxyz, cb0[27].zzzz, r0.xxyz
  add r4.x, l(1.000000), -cb0[27].z
  mul r4.yzw, cb0[16].xxyz, cb0[27].zzzz
  mad r4.xyz, r1.xyzx, r4.xxxx, r4.yzwy
  dp3 r4.w, r4.xyzx, r4.xyzx
  rsq r5.x, r4.w
  lt r3.y, r3.y, r4.w
  mul r4.w, r5.x, cb0[27].w
  mul r5.xyz, r4.wwww, r4.xyzx
  movc r4.xyz, r3.yyyy, r5.xyzx, r4.xyzx
  mad r0.xyz, r4.xyzx, cb0[27].zzzz, r0.xyzx
  mov r2.w, r3.x
  mov r4.w, r0.x
  movc r2.xyzw, r1.wwww, r2.xyzw, r4.xyzw
  movc r0.xy, r1.wwww, r3.zwzz, r0.yzyy
  mov r3.xyz, r2.xyzx
  mov r4.x, r2.w
  mov r4.yz, r0.xxyx
  mov r0.z, l(0)
  loop 
    ige r1.w, r0.z, cb0[8].x
    breakc_nz r1.w
    dp3 r1.w, r4.xyzx, cb0[r0.z + 0].xyzx
    add r1.w, r1.w, cb0[r0.z + 0].w
    add r1.w, r1.w, -cb0[18].z
    ge r5.x, l(0.000000), r1.w
    mad r5.yzw, -r1.wwww, cb0[r0.z + 0].xxyz, r4.xxyz
    dp3 r1.w, r1.xyzx, cb0[r0.z + 0].xyzx
    lt r6.x, r1.w, l(0.000000)
    mul r1.w, r1.w, l(1.500000)
    mad r6.yzw, -r1.wwww, cb0[r0.z + 0].xxyz, r3.xxyz
    movc r6.xyz, r6.xxxx, r6.yzwy, r3.xyzx
    movc r3.xyz, r5.xxxx, r6.xyzx, r3.xyzx
    movc r4.xyz, r5.xxxx, r5.yzwy, r4.xyzx
    iadd r0.z, r0.z, l(1)
  endloop 
  mov r3.w, l(0)
  store_structured u1.xyzw, vThreadID.x, l(0), r3.xyzw
  add r4.w, r0.w, -cb0[27].z
  store_structured u0.xyzw, vThreadID.x, l(0), r4.xyzw
endif 
ret 
// Approximately 89 instruction slots used
