//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer ClearFloat4::consts
// {
//
//   int ClearFloat4::gLength;          // Offset:    0 Size:     4
//   float3 ClearFloat4::_pad3;         // Offset:    4 Size:    12 [unused]
//   float4 ClearFloat4::gValue;        // Offset:   16 Size:    16
//
// }
//
// Resource bind info for ClearFloat4::buf
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ClearFloat4::buf                      UAV  struct         r/w             u0      1 
// ClearFloat4::consts               cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_uav_structured u0, 16
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
if_nz r0.x
  store_structured u0.xyzw, vThreadID.x, l(0), cb0[1].xyzw
endif 
ret 
// Approximately 5 instruction slots used
