//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for SolveVelocities::contacts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveVelocities::contactCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveVelocities::collisionPlanes
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveVelocities::collisionCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveVelocities::sortedPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveVelocities::sortedVelocities
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveVelocities::sortedNewVelocities
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveVelocities::phases
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveVelocities::curl
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveVelocities::sortedNewPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveVelocities::densities
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveVelocities::potentials
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SolveVelocities::contacts         texture  struct         r/o             t0      1 
// SolveVelocities::contactCounts    texture  struct         r/o             t1      1 
// SolveVelocities::collisionPlanes    texture  struct         r/o             t2      1 
// SolveVelocities::collisionCounts    texture  struct         r/o             t3      1 
// SolveVelocities::sortedPositions    texture  struct         r/o             t4      1 
// SolveVelocities::sortedVelocities    texture  struct         r/o             t5      1 
// SolveVelocities::sortedNewVelocities    texture  struct         r/o             t6      1 
// SolveVelocities::phases           texture  struct         r/o             t7      1 
// SolveVelocities::curl             texture  struct         r/o             t8      1 
// SolveVelocities::sortedNewPositions        UAV  struct         r/w             u0      1 
// SolveVelocities::deltas               UAV    byte         r/w             u1      1 
// SolveVelocities::densities            UAV  struct         r/w             u2      1 
// SolveVelocities::potentials           UAV  struct         r/w             u3      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[32], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 4
dcl_resource_structured t2, 16
dcl_resource_structured t3, 4
dcl_resource_structured t4, 16
dcl_resource_structured t5, 16
dcl_resource_structured t6, 16
dcl_resource_structured t7, 4
dcl_resource_structured t8, 16
dcl_uav_structured u0, 16
dcl_uav_raw u1
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_input vThreadID.x
dcl_temps 11
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[23].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), u0.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(0), t6.xyzx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), t7.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(0), t1.xxxx
  and r0.w, r0.w, l(0x00400000)
  ine r2.x, r0.w, l(0)
  lt r2.y, l(0.000000), cb0[13].x
  lt r2.z, l(0.000000), cb0[15].x
  mov r2.w, vThreadID.x
  mov r5.xy, l(0,0,0,0)
  mov r3.xyzw, l(0,0,0,0)
  mov r4.xyzw, l(0,0,0,0)
  loop 
    ige r5.z, r4.w, r1.w
    breakc_nz r5.z
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.z, r2.w, l(0), t0.xxxx
    iadd r2.w, r2.w, cb0[23].y
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r6.xyz, r5.z, l(0), u0.xyzx
    add r6.xyz, r0.xyzx, -r6.xyzx
    dp3 r5.w, r6.xyzx, r6.xyzx
    ge r6.w, cb0[8].z, r5.w
    lt r7.x, l(0.000000), r5.w
    and r6.w, r6.w, r7.x
    if_nz r6.w
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.w, r5.z, l(0), t7.xxxx
      add r3.w, r3.w, l(1.000000)
      and r6.w, r6.w, l(0x00400000)
      ine r6.w, r6.w, l(0)
      and r6.w, r2.x, r6.w
      sqrt r5.w, r5.w
      div r6.xyz, r6.xyzx, r5.wwww
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r7.xyz, r5.z, l(0), t6.xyzx
      add r7.xyz, -r1.xyzx, r7.xyzx
      mad r5.w, -r5.w, cb0[8].w, l(1.000000)
      mul r7.w, r5.w, r5.w
      mul r8.x, r7.w, cb0[9].y
      mad r9.x, cb0[9].y, r7.w, r5.x
      mul r8.yzw, r7.xxyz, cb0[14].yyyy
      mul r8.yzw, r8.xxxx, r8.yyzw
      mad r8.yzw, r8.yyzw, cb0[23].zzzz, r3.xxyz
      mul r5.w, r5.w, -cb0[9].z
      mul r10.xyz, r6.xyzx, r5.wwww
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r5.z, r5.z, l(12), t8.xxxx
      mad r10.xyz, r5.zzzz, r10.xyzx, r4.xyzx
      movc r10.xyz, r2.yyyy, r10.xyzx, r4.xyzx
      dp3 r5.z, r7.xyzx, r7.xyzx
      sqrt r5.z, r5.z
      dp3 r5.w, r7.xyzx, r6.xyzx
      add r5.z, -r5.w, r5.z
      mad r5.z, r5.z, r8.x, r5.y
      movc r9.y, r2.z, r5.z, r5.y
      movc r3.xyz, r6.wwww, r8.yzwy, r3.xyzx
      movc r4.xyz, r6.wwww, r10.xyzx, r4.xyzx
      movc r5.xy, r6.wwww, r9.xyxx, r5.xyxx
    endif 
    iadd r4.w, r4.w, l(1)
  endloop 
  mov r4.xyzw, r4.yzzx
  lt r1.w, l(0.000000), r5.x
  and r1.w, r1.w, r2.y
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyw, vThreadID.x, l(0), t8.xyxz
  mul r5.z, cb0[23].z, cb0[23].z
  mul r5.z, r5.z, cb0[11].y
  mul r5.z, r5.z, cb0[13].x
  dp3 r5.w, r4.xzwx, r4.xzwx
  lt r6.x, l(0.000000), r5.w
  rsq r5.w, r5.w
  mul r4.xyzw, r4.xyzw, r5.wwww
  and r4.xyzw, r4.xyzw, r6.xxxx
  mul r6.xy, r2.ywyy, r4.ywyy
  mad r6.xy, r4.xzxx, r2.wxww, -r6.xyxx
  mul r2.x, r2.x, r4.x
  mad r6.z, r4.w, r2.y, -r2.x
  mad r2.xyw, r5.zzzz, r6.xyxz, r3.xyxz
  movc r2.xyw, r1.wwww, r2.xyxw, r3.xyxz
  lt r1.w, l(0.000000), cb0[17].w
  mul r3.xyz, r1.xyzx, cb0[23].zzzz
  mul r4.xyz, r3.wwww, r3.xyzx
  mad r4.xyz, -r4.xyzx, cb0[17].wwww, r2.xywx
  movc r2.xyw, r1.wwww, r4.xyxz, r2.xyxw
  lt r1.w, l(0.000000), cb0[18].x
  mad r3.xyz, -r3.xyzx, cb0[18].xxxx, r2.xywx
  movc r3.xyz, r1.wwww, r3.xyzx, r2.xywx
  lt r1.w, l(0.000000), cb0[21].w
  if_nz r1.w
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(0), t3.xxxx
    if_nz r1.w
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyw, vThreadID.x, l(0), t5.xyxz
      mov r4.xyzw, l(0,0,0,0)
      mov r5.z, l(0)
      loop 
        ige r5.w, r5.z, r1.w
        breakc_nz r5.w
        imad r5.w, vThreadID.x, cb0[31].w, r5.z
        ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r6.xyzw, r5.w, l(0), t2.xyzw
        dp3 r5.w, r0.xyzx, r6.xyzx
        add r5.w, r6.w, r5.w
        mad r5.w, -cb0[18].z, l(1.001000), r5.w
        dp3 r6.w, r2.xywx, r6.xyzx
        ge r5.w, l(0.000000), r5.w
        lt r7.x, r6.w, l(0.000000)
        and r5.w, r5.w, r7.x
        dp3 r7.x, r1.xyzx, r6.xyzx
        mad r6.w, cb0[21].w, r6.w, r7.x
        mad r6.xyz, -r6.wwww, r6.xyzx, r4.xyzx
        add r6.w, r4.w, l(1.000000)
        movc r4.xyzw, r5.wwww, r6.xyzw, r4.xyzw
        iadd r5.z, r5.z, l(1)
      endloop 
      max r0.x, r4.w, l(1.000000)
      div r0.xyz, r4.xyzx, r0.xxxx
      add r3.xyz, r0.xyzx, r3.xyzx
    endif 
  endif 
  if_nz r2.z
    dp3 r0.x, r1.xyzx, r1.xyzx
    mul r0.x, r0.x, l(3.000000)
    dp2 r0.y, cb0[11].yyyy, r5.xxxx
    add r0.y, -r0.y, l(1.000000)
    max r0.y, r0.y, l(0.000000)
    mul r0.y, r5.y, r0.y
    mul r0.x, r0.x, r0.y
    movc r0.x, r0.w, r0.x, l(0)
    store_structured u3.x, vThreadID.x, l(0), r0.x
  endif 
  add r0.xyz, r1.xyzx, r3.xyzx
  dp3 r0.x, r0.xyzx, r0.xyzx
  lt r0.x, r0.x, cb0[21].y
  if_nz r0.x
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), t4.xyzx
    store_structured u0.xyz, vThreadID.x, l(0), r0.xyzx
    mov r3.xyz, -r1.xxxx
  endif 
  ishl r0.x, vThreadID.x, l(4)
  mov r3.w, l(0)
  store_raw u1.xyzw, r0.x, r3.xyzw
  store_structured u2.x, vThreadID.x, l(0), r5.x
endif 
ret 
// Approximately 141 instruction slots used
