//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for CollideParticles::cellStarts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideParticles::cellEnds
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideParticles::sortedNewPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideParticles::restPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideParticles::phases
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideParticles::bounds
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for CollideParticles::contacts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideParticles::contactCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CollideParticles::cellStarts      texture  struct         r/o             t0      1 
// CollideParticles::cellEnds        texture  struct         r/o             t1      1 
// CollideParticles::indices         texture    uint         buf             t2      1 
// CollideParticles::sortedNewPositions    texture  struct         r/o             t3      1 
// CollideParticles::restPositions    texture  struct         r/o             t4      1 
// CollideParticles::phases          texture  struct         r/o             t5      1 
// CollideParticles::bounds          texture  struct         r/o             t6      1 
// CollideParticles::contacts            UAV  struct         r/w             u0      1 
// CollideParticles::contactCounts        UAV  struct         r/w             u1      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[31], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 4
dcl_resource_buffer (uint,uint,uint,uint) t2
dcl_resource_structured t3, 16
dcl_resource_structured t4, 16
dcl_resource_structured t5, 4
dcl_resource_structured t6, 12
dcl_uav_structured u0, 4
dcl_uav_structured u1, 4
dcl_input vThreadID.x
dcl_temps 10
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[23].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), t3.xyzx
  ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r1.xyz, l(0), l(0), t6.xyzx
  add r1.xyz, r0.xyzx, -r1.xyzx
  mul r1.xyz, r1.xyzx, cb0[24].zzzz
  ftoi r1.xyz, r1.xyzx
  iadd r2.xyzw, r1.xxyy, l(-1, 1, -1, 1)
  iadd r1.xy, r1.zzzz, l(-1, 1, 0, 0)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), t5.xxxx
  and r3.xyz, r0.wwww, l(0x00200000, 0x000fffff, 0x00100000, 0)
  if_nz r3.x
    ld_indexable(buffer)(uint,uint,uint,uint) r0.w, vThreadID.xxxx, t2.yzwx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyz, r0.w, l(0), t4.xyzx
  endif 
  iadd r5.z, vThreadID.x, l(1)
  ine r1.zw, r3.xxxz, l(0, 0, 0, 0)
  mov r3.z, vThreadID.x
  mov r3.x, l(0)
  mov r0.w, r1.x
  loop 
    ilt r3.w, r1.y, r0.w
    breakc_nz r3.w
    bfi r3.w, l(7), l(14), r0.w, l(0)
    mov r6.xy, r3.zxzz
    mov r4.w, r2.z
    loop 
      ilt r5.w, r2.w, r4.w
      breakc_nz r5.w
      bfi r5.w, l(7), l(7), r4.w, l(0)
      iadd r5.w, r3.w, r5.w
      mov r6.zw, r6.xxxy
      mov r7.x, r2.x
      loop 
        ilt r7.y, r2.y, r7.x
        breakc_nz r7.y
        bfi r7.y, l(7), l(0), r7.x, r5.w
        ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.z, r7.y, l(0), t0.xxxx
        ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.y, r7.y, l(0), t1.xxxx
        mov r8.yz, r6.zzwz
        mov r8.x, r7.z
        loop 
          ige r7.w, r8.x, r7.y
          breakc_nz r7.w
          ieq r7.w, r8.x, vThreadID.x
          if_nz r7.w
            mov r5.xy, r8.yzyy
            mov r8.xyz, r5.zxyz
            continue 
          endif 
          ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.x, r8.x, l(0), t5.xxxx
          and r5.x, r5.x, l(0x000fffff)
          ieq r5.x, r3.y, r5.x
          not r5.y, r5.x
          or r5.y, r1.w, r5.y
          if_nz r5.y
            and r5.x, r1.z, r5.x
            if_nz r5.x
              ld_indexable(buffer)(uint,uint,uint,uint) r5.x, r8.xxxx, t2.xyzw
              ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r9.xyz, r5.x, l(0), t4.xyzx
              add r9.xyz, r4.xyzx, -r9.xyzx
              dp3 r5.x, r9.xyzx, r9.xyzx
              lt r5.x, r5.x, cb0[8].z
              if_nz r5.x
                iadd r9.z, r8.x, l(1)
                mov r9.xy, r8.yzyy
                mov r8.xyz, r9.zxyz
                continue 
              endif 
            endif 
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r9.xyz, r8.x, l(0), t3.xyzx
            add r9.xyz, r0.xyzx, -r9.xyzx
            dp3 r5.x, r9.xyzx, r9.xyzx
            lt r5.x, r5.x, cb0[25].x
            if_nz r5.x
              ilt r5.x, r8.z, cb0[30].w
              if_nz r5.x
                store_structured u0.x, r8.y, l(0), r8.x
                iadd r8.y, r8.y, cb0[23].y
                iadd r8.z, r8.z, l(1)
              endif 
            endif 
          endif 
          iadd r8.x, r8.x, l(1)
        endloop 
        mov r6.zw, r8.yyyz
        iadd r7.x, r7.x, l(1)
      endloop 
      mov r6.xy, r6.zwzz
      iadd r4.w, r4.w, l(1)
    endloop 
    mov r3.xz, r6.yyxy
    iadd r0.w, r0.w, l(1)
  endloop 
  store_structured u1.x, vThreadID.x, l(0), r3.x
endif 
ret 
// Approximately 97 instruction slots used
