//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for SolveSprings::halfSpringOpposites
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveSprings::halfSpringLengths
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveSprings::halfSpringStiffness
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveSprings::particleSpringBegin
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveSprings::particleSpringEnd
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveSprings::reverseLookup
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveSprings::sortedNewPositionsTex
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SolveSprings::halfSpringOpposites    texture  struct         r/o             t1      1 
// SolveSprings::halfSpringLengths    texture  struct         r/o             t2      1 
// SolveSprings::halfSpringStiffness    texture  struct         r/o             t3      1 
// SolveSprings::particleSpringBegin    texture  struct         r/o             t4      1 
// SolveSprings::particleSpringEnd    texture  struct         r/o             t5      1 
// SolveSprings::reverseLookup       texture  struct         r/o             t6      1 
// SolveSprings::sortedNewPositionsTex    texture  struct         r/o             t7      1 
// SolveSprings::deltas                  UAV    byte         r/w             u0      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[26], immediateIndexed
dcl_resource_structured t1, 4
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_resource_structured t4, 4
dcl_resource_structured t5, 4
dcl_resource_structured t6, 4
dcl_resource_structured t7, 16
dcl_uav_raw u0
dcl_input vThreadIDInGroup.x
dcl_input vThreadID.x
dcl_temps 7
dcl_tgsm_structured g0, 12, 512
dcl_thread_group 512, 1, 1
ushr r0.x, vThreadID.x, l(3)
and r0.y, vThreadID.x, l(7)
uge r0.z, r0.x, cb0[25].y
movc r0.x, r0.z, l(0), r0.x
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r0.x, l(0), t4.xxxx
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.x, r0.x, l(0), t5.xxxx
iadd r1.y, -r0.w, r1.x
movc r0.z, r0.z, l(0), r1.y
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), t6.xxxx
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyzw, r0.x, l(0), t7.xyzw
lt r1.y, l(0.000000), r2.w
ult r1.z, l(0), r0.z
and r1.w, r1.z, r1.y
if_nz r1.w
  iadd r0.w, r0.y, r0.w
  mov r3.xyz, l(0,0,0,0)
  mov r1.w, r0.w
  loop 
    uge r3.w, r1.w, r1.x
    breakc_nz r3.w
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r1.w, l(0), t1.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), t6.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyzw, r3.w, l(0), t7.xyzw
    add r4.xyz, r2.xyzx, -r4.xyzx
    add r3.w, r2.w, r4.w
    lt r4.w, l(0.000000), r3.w
    dp3 r5.x, r4.xyzx, r4.xyzx
    lt r5.y, l(0.000000), r5.x
    div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
    sqrt r5.x, r5.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.z, r1.w, l(0), t2.xxxx
    add r6.x, -r5.x, r5.z
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.y, r1.w, l(0), t3.xxxx
    lt r5.z, r6.y, l(0.000000)
    if_nz r5.z
      min r6.x, r6.x, l(0.000000)
      mov r6.y, -r6.y
    endif 
    div r4.xyz, r4.xyzx, r5.xxxx
    mul r3.w, r3.w, r6.y
    mul r3.w, r6.x, r3.w
    mad r4.xyz, r3.wwww, r4.xyzx, r3.xyzx
    movc r4.xyz, r5.yyyy, r4.xyzx, r3.xyzx
    movc r3.xyz, r4.wwww, r4.xyzx, r3.xyzx
    iadd r1.w, r1.w, l(8)
  endloop 
else 
  mov r3.xyz, l(0,0,0,0)
endif 
store_structured g0.xyz, vThreadIDInGroup.x, l(0), r3.xyzx
sync_g_t
ieq r0.y, r0.y, l(0)
and r0.y, r1.z, r0.y
and r0.y, r1.y, r0.y
if_nz r0.y
  iadd r1.xyzw, vThreadIDInGroup.xxxx, l(1, 2, 3, 4)
  ld_structured r2.xyz, r1.x, l(0), g0.xyzx
  add r2.xyz, r2.xyzx, r3.xyzx
  ld_structured r3.xyz, r1.y, l(0), g0.xyzx
  add r2.xyz, r2.xyzx, r3.xyzx
  ld_structured r1.xyz, r1.z, l(0), g0.xyzx
  add r1.xyz, r1.xyzx, r2.xyzx
  ld_structured r2.xyz, r1.w, l(0), g0.xyzx
  add r1.xyz, r1.xyzx, r2.xyzx
  iadd r2.xyz, vThreadIDInGroup.xxxx, l(5, 6, 7, 0)
  ld_structured r3.xyz, r2.x, l(0), g0.xyzx
  add r1.xyz, r1.xyzx, r3.xyzx
  ld_structured r3.xyz, r2.y, l(0), g0.xyzx
  add r1.xyz, r1.xyzx, r3.xyzx
  ld_structured r2.xyz, r2.z, l(0), g0.xyzx
  add r1.xyz, r1.xyzx, r2.xyzx
  ishl r0.x, r0.x, l(4)
  ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r3.xyzw, r0.x, u0.xyzw
  mul r1.xyz, r2.wwww, r1.xyzx
  utof r1.w, r0.z
  add r1.xyzw, r1.xyzw, r3.xyzw
  store_raw u0.xyzw, r0.x, r1.xyzw
endif 
ret 
// Approximately 79 instruction slots used
