//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer SpringsParticleRange::consts
// {
//
//   uint SpringsParticleRange::gNumSprings;// Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsParticleRange::starts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsParticleRange::ends
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SpringsParticleRange::ids         texture    uint         buf             t0      1 
// SpringsParticleRange::starts          UAV  struct         r/w             u0      1 
// SpringsParticleRange::ends            UAV  struct         r/w             u1      1 
// SpringsParticleRange::consts      cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_buffer (uint,uint,uint,uint) t0
dcl_uav_structured u0, 4
dcl_uav_structured u1, 4
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 256, 1, 1
ishl r0.x, cb0[0].x, l(1)
ult r0.y, vThreadID.x, r0.x
if_nz r0.y
  ld_indexable(buffer)(uint,uint,uint,uint) r0.y, vThreadID.xxxx, t0.yxzw
  if_z vThreadID.x
    store_structured u0.x, r0.y, l(0), l(0)
  else 
    iadd r0.z, vThreadID.x, l(-1)
    ld_indexable(buffer)(uint,uint,uint,uint) r0.z, r0.zzzz, t0.yzxw
    ine r0.w, r0.z, r0.y
    if_nz r0.w
      store_structured u0.x, r0.y, l(0), vThreadID.x
      store_structured u1.x, r0.z, l(0), vThreadID.x
    endif 
  endif 
  iadd r0.x, r0.x, l(-1)
  ieq r0.x, r0.x, vThreadID.x
  if_nz r0.x
    iadd r0.x, vThreadID.x, l(1)
    store_structured u1.x, r0.y, l(0), r0.x
  endif 
endif 
ret 
// Approximately 23 instruction slots used
