//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer SpringsReorder::consts
// {
//
//   uint SpringsReorder::gNumSprings;  // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsReorder::indices
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsReorder::lengths
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsReorder::stiffness
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsReorder::halfOpposite
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsReorder::halfLengths
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SpringsReorder::halfStiffness
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SpringsReorder::sortedIndices     texture    uint         buf             t0      1 
// SpringsReorder::indices           texture  struct         r/o             t1      1 
// SpringsReorder::lengths           texture  struct         r/o             t2      1 
// SpringsReorder::stiffness         texture  struct         r/o             t3      1 
// SpringsReorder::halfOpposite          UAV  struct         r/w             u0      1 
// SpringsReorder::halfLengths           UAV  struct         r/w             u1      1 
// SpringsReorder::halfStiffness         UAV  struct         r/w             u2      1 
// SpringsReorder::consts            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_buffer (uint,uint,uint,uint) t0
dcl_resource_structured t1, 4
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_uav_structured u0, 4
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 256, 1, 1
ishl r0.x, cb0[0].x, l(1)
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  ld_indexable(buffer)(uint,uint,uint,uint) r0.x, vThreadID.xxxx, t0.xyzw
  ushr r0.y, r0.x, l(1)
  and r0.z, r0.x, l(1)
  iadd r0.xw, r0.xxxx, l(-1, 0, 0, 1)
  movc r0.x, r0.z, r0.x, r0.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), t1.xxxx
  store_structured u0.x, vThreadID.x, l(0), r0.x
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.y, l(0), t2.xxxx
  store_structured u1.x, vThreadID.x, l(0), r0.x
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.y, l(0), t3.xxxx
  store_structured u2.x, vThreadID.x, l(0), r0.x
endif 
ret 
// Approximately 16 instruction slots used
