//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for CalculateBounds::readBoundsLower
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateBounds::readBoundsUpper
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateBounds::writeBoundsLower
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateBounds::writeBoundsUpper
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for g_NvidiaExt
// {
//
//   struct NvShaderExtnStruct
//   {
//       
//       uint opcode;                   // Offset:    0
//       uint rid;                      // Offset:    4
//       uint sid;                      // Offset:    8
//       uint4 dst1u;                   // Offset:   12
//       uint4 padding0[3];             // Offset:   28
//       uint4 src0u;                   // Offset:   76
//       uint4 src1u;                   // Offset:   92
//       uint4 src2u;                   // Offset:  108
//       uint4 dst0u;                   // Offset:  124
//       uint markUavRef;               // Offset:  140
//       float padding1[28];            // Offset:  144
//
//   } $Element;                        // Offset:    0 Size:   256
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CalculateBounds::readBoundsLower    texture  struct         r/o             t2      1 
// CalculateBounds::readBoundsUpper    texture  struct         r/o             t3      1 
// CalculateBounds::writeBoundsLower        UAV  struct         r/w             u0      1 
// CalculateBounds::writeBoundsUpper        UAV  struct         r/w             u1      1 
// g_NvidiaExt                           UAV  struct     r/w+cnt             u7      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_resource_structured t2, 16
dcl_resource_structured t3, 16
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_uav_structured_opc u7, 256
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_input vThreadID.x
dcl_temps 6
dcl_tgsm_structured g0, 12, 4
dcl_thread_group 128, 1, 1
iadd r0.x, cb0[23].x, l(127)
ushr r0.x, r0.x, l(7)
ilt r0.x, vThreadID.x, r0.x
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t2.xxyz
movc r0.yzw, r0.xxxx, r0.yyzw, l(0,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000,340282346638528859811704183484516925440.000000)
and r1.x, vThreadIDInGroup.x, l(31)
ishr r1.y, vThreadIDInGroup.x, l(5)
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,1,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,1,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,1,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,2,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,2,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,2,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,4,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,4,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,4,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,8,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,8,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,8,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
min r0.yzw, r0.yyzw, r2.xxyz
imm_atomic_alloc r2.x, u7
mov r3.x, r0.y
mov r3.yz, l(0,16,31,0)
store_structured u7.xyz, r2.x, l(76), r3.xyzx
store_structured u7.x, r2.x, l(0), l(3)
imm_atomic_alloc r2.x, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.z
mov r4.yz, l(0,16,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.y, u7
imm_atomic_alloc r3.x, u7
mov r4.x, r0.w
mov r4.yz, l(0,16,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r2.z, u7
if_z r1.x
  min r0.yzw, r0.yyzw, r2.xxyz
  store_structured g0.xyz, r1.y, l(0), r0.yzwy
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.yzw, l(0), l(0), g0.xxyz
  ld_structured r2.xyz, l(1), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(2), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  ld_structured r2.xyz, l(3), l(0), g0.xyzx
  min r0.yzw, r0.yyzw, r2.xxyz
  store_structured g0.xyz, l(0), l(0), r0.yzwy
endif 
sync_g_t
ld_structured r2.xyz, l(0), l(0), g0.xyzx
sync_g_t
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yzw, vThreadID.x, l(0), t3.xxyz
movc r0.xyz, r0.xxxx, r0.yzwy, l(-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,-340282346638528859811704183484516925440.000000,0)
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,1,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,1,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,1,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,2,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,2,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,2,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,4,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,4,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,4,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,8,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,8,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,8,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
max r0.xyz, r0.xyzx, r3.xyzx
imm_atomic_alloc r3.x, u7
mov r4.x, r0.x
mov r4.yz, l(0,16,31,0)
store_structured u7.xyz, r3.x, l(76), r4.xyzx
store_structured u7.x, r3.x, l(0), l(3)
imm_atomic_alloc r3.x, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.y
mov r5.yz, l(0,16,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.y, u7
imm_atomic_alloc r4.x, u7
mov r5.x, r0.z
mov r5.yz, l(0,16,31,0)
store_structured u7.xyz, r4.x, l(76), r5.xyzx
store_structured u7.x, r4.x, l(0), l(3)
imm_atomic_alloc r3.z, u7
if_z r1.x
  max r0.xyz, r0.xyzx, r3.xyzx
  store_structured g0.xyz, r1.y, l(0), r0.xyzx
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.xyz, l(0), l(0), g0.xyzx
  ld_structured r1.xyz, l(1), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(2), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  ld_structured r1.xyz, l(3), l(0), g0.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  store_structured g0.xyz, l(0), l(0), r0.xyzx
endif 
sync_g_t
if_z vThreadIDInGroup.x
  ld_structured r0.xyz, l(0), l(0), g0.xyzx
  mov r2.w, l(0)
  store_structured u0.xyzw, vThreadGroupID.x, l(0), r2.xyzw
  mov r0.w, l(0)
  store_structured u1.xyzw, vThreadGroupID.x, l(0), r0.xyzw
endif 
ret 
// Approximately 239 instruction slots used
