//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// cbuffer CollideShapes::constSubstep
// {
//
//   struct SubstepParams
//   {
//       
//       float kSubstepStart;           // Offset:    0
//       float kSubstepEnd;             // Offset:    4
//
//   } CollideShapes::gSubParams;       // Offset:    0 Size:     8
//
// }
//
// Resource bind info for CollideShapes::shapeGeometry
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::shapePositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::shapeRotations
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::shapePrevPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::shapePrevRotations
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::shapeFlags
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideShapes::sortedPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::sortedNewPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::sortedPhases
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideShapes::shapeBvhRootNode
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideShapes::shapeBvhNodeLowers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::shapeBvhNodeUppers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::convexes
// {
//
//   struct FlexConvexMeshDevice
//   {
//       
//       float4 mLower;                 // Offset:    0
//       float4 mUpper;                 // Offset:   16
//       int mPlaneOffset;              // Offset:   32
//       int mPlaneCount;               // Offset:   36
//       int mPad[2];                   // Offset:   40
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for CollideShapes::convexPlanes
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::sdfs
// {
//
//   struct FlexSDFDevice
//   {
//       
//       int4 mDim;                     // Offset:    0
//       float4 mInvDim;                // Offset:   16
//
//   } $Element;                        // Offset:    0 Size:    32
//
// }
//
// Resource bind info for CollideShapes::collisionCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CollideShapes::collisionPlanes
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CollideShapes::collisionVelocities
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CollideShapes::sdfSampler         sampler      NA          NA             s0      1 
// CollideShapes::shapeGeometry      texture  struct         r/o             t0      1 
// CollideShapes::shapePositions     texture  struct         r/o             t1      1 
// CollideShapes::shapeRotations     texture  struct         r/o             t2      1 
// CollideShapes::shapePrevPositions    texture  struct         r/o             t3      1 
// CollideShapes::shapePrevRotations    texture  struct         r/o             t4      1 
// CollideShapes::shapeFlags         texture  struct         r/o             t5      1 
// CollideShapes::sortedPositions    texture  struct         r/o             t6      1 
// CollideShapes::sortedNewPositions    texture  struct         r/o             t7      1 
// CollideShapes::sortedPhases       texture  struct         r/o             t8      1 
// CollideShapes::shapeBvhRootNode    texture  struct         r/o             t9      1 
// CollideShapes::shapeBvhNodeLowers    texture  struct         r/o            t10      1 
// CollideShapes::shapeBvhNodeUppers    texture  struct         r/o            t11      1 
// CollideShapes::convexes           texture  struct         r/o            t12      1 
// CollideShapes::convexPlanes       texture  struct         r/o            t13      1 
// CollideShapes::sdfs               texture  struct         r/o            t14      1 
// CollideShapes::sdfTex0            texture   float          3d            t15      1 
// CollideShapes::sdfTex1            texture   float          3d            t16      1 
// CollideShapes::sdfTex2            texture   float          3d            t17      1 
// CollideShapes::sdfTex3            texture   float          3d            t18      1 
// CollideShapes::sdfTex4            texture   float          3d            t19      1 
// CollideShapes::sdfTex5            texture   float          3d            t20      1 
// CollideShapes::sdfTex6            texture   float          3d            t21      1 
// CollideShapes::sdfTex7            texture   float          3d            t22      1 
// CollideShapes::sdfTex8            texture   float          3d            t23      1 
// CollideShapes::sdfTex9            texture   float          3d            t24      1 
// CollideShapes::sdfTex10           texture   float          3d            t25      1 
// CollideShapes::sdfTex11           texture   float          3d            t26      1 
// CollideShapes::sdfTex12           texture   float          3d            t27      1 
// CollideShapes::sdfTex13           texture   float          3d            t28      1 
// CollideShapes::sdfTex14           texture   float          3d            t29      1 
// CollideShapes::sdfTex15           texture   float          3d            t30      1 
// CollideShapes::collisionCounts        UAV  struct         r/w             u0      1 
// CollideShapes::collisionPlanes        UAV  struct         r/w             u1      1 
// CollideShapes::collisionVelocities        UAV  struct         r/w             u2      1 
// consts                            cbuffer      NA          NA            cb0      1 
// CollideShapes::constSubstep       cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[32], dynamicIndexed
dcl_constantbuffer CB1[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 16
dcl_resource_structured t3, 16
dcl_resource_structured t4, 16
dcl_resource_structured t5, 4
dcl_resource_structured t6, 16
dcl_resource_structured t7, 16
dcl_resource_structured t8, 4
dcl_resource_structured t9, 4
dcl_resource_structured t10, 16
dcl_resource_structured t11, 16
dcl_resource_structured t12, 48
dcl_resource_structured t13, 16
dcl_resource_structured t14, 32
dcl_resource_texture3d (float,float,float,float) t15
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture3d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texture3d (float,float,float,float) t22
dcl_resource_texture3d (float,float,float,float) t23
dcl_resource_texture3d (float,float,float,float) t24
dcl_resource_texture3d (float,float,float,float) t25
dcl_resource_texture3d (float,float,float,float) t26
dcl_resource_texture3d (float,float,float,float) t27
dcl_resource_texture3d (float,float,float,float) t28
dcl_resource_texture3d (float,float,float,float) t29
dcl_resource_texture3d (float,float,float,float) t30
dcl_uav_structured u0, 4
dcl_uav_structured u1, 16
dcl_uav_structured u2, 16
dcl_input vThreadID.x
dcl_temps 29
dcl_indexableTemp x0[64], 4
dcl_thread_group 128, 1, 1
ilt r0.x, vThreadID.x, cb0[23].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), t7.xyzx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), u0.xxxx
  mov r1.x, cb0[31].w
  mov r1.y, r0.w
  mov r1.z, l(0)
  loop 
    ige r1.w, r1.z, cb0[8].x
    breakc_nz r1.w
    dp3 r1.w, r0.xyzx, cb0[r1.z + 0].xyzx
    add r1.w, r1.w, cb0[r1.z + 0].w
    add r1.w, r1.w, -cb0[18].z
    ge r1.w, cb0[18].w, r1.w
    ilt r2.x, r1.y, r1.x
    and r1.w, r1.w, r2.x
    if_nz r1.w
      imad r1.w, vThreadID.x, r1.x, r1.y
      store_structured u1.xyzw, r1.w, l(0), cb0[r1.z + 0].xyzw
      store_structured u2.xyzw, r1.w, l(0), l(0,0,0,-1.000000)
      iadd r1.y, r1.y, l(1)
    endif 
    iadd r1.z, r1.z, l(1)
  endloop 
  if_nz cb0[26].x
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xzw, vThreadID.x, l(0), t6.xxyz
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), t8.xxxx
    and r0.w, r0.w, l(0xff000000)
    min r2.xyz, r0.xyzx, r1.xzwx
    max r3.xyz, r0.xyzx, r1.xzwx
    add r2.xyz, r2.xyzx, -cb0[19].xxxx
    add r3.xyz, r3.xyzx, cb0[19].xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, l(0), l(0), t9.xxxx
    mov x0[0].x, r2.w
    add r2.w, cb0[18].w, cb0[18].z
    mov r4.xyz, l(-1.000000,0,0,0)
    mov r5.xyz, l(1.000000,0,0,0)
    mov r6.xy, l(0,1.000000,0,0)
    mov r7.xy, l(0,-1.000000,0,0)
    mov r8.xz, l(0,0,1.000000,0)
    mov r9.xz, l(0,0,-1.000000,0)
    mov r10.w, l(1.000000)
    mov r11.yz, l(0,0,0,0)
    mov r12.z, l(0)
    mov r13.yw, l(0,1.000000,0,0)
    mov r14.yz, l(0,0,0,0)
    mov r3.w, cb0[31].w
    mov r6.z, r1.y
    mov r7.z, l(1)
    loop 
      breakc_z r7.z
      iadd r8.y, r7.z, l(-1)
      mov r9.y, x0[r8.y + 0].x
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r15.xyzw, r9.y, l(0), t10.xyzw
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r16.xyzw, r9.y, l(0), t11.xyzw
      lt r15.xyz, r3.xyzx, r15.xyzx
      or r9.y, r15.y, r15.x
      or r9.y, r15.z, r9.y
      lt r15.xyz, r16.xyzx, r2.xyzx
      or r9.y, r9.y, r15.x
      or r9.y, r15.y, r9.y
      or r9.y, r15.z, r9.y
      if_z r9.y
        and r15.xy, r15.wwww, l(0x7fffffff, 0x80000000, 0, 0)
        if_nz r15.y
          ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r9.y, r15.x, l(0), t5.xxxx
          and r11.w, r0.w, r9.y
          if_nz r11.w
            and r11.w, r9.y, l(7)
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r15.yzw, r15.x, l(0), t1.xxyz
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r17.xyzw, r15.x, l(0), t2.xyzw
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r16.xyz, r15.x, l(0), t3.xyzx
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r18.xyzw, r15.x, l(0), t4.xyzw
            add r15.yzw, r15.yyzw, -r16.xxyz
            mad r19.xyz, r15.yzwy, cb1[0].xxxx, r16.xyzx
            add r17.xyzw, r17.xyzw, -r18.xyzw
            mad r20.xyzw, r17.xyzw, cb1[0].xxxx, r18.xyzw
            dp4 r12.w, r20.xyzw, r20.xyzw
            rsq r12.w, r12.w
            mul r20.xyzw, r12.wwww, r20.xyzw
            mad r15.yzw, r15.yyzw, cb1[0].yyyy, r16.xxyz
            mad r17.xyzw, r17.xyzw, cb1[0].yyyy, r18.xyzw
            dp4 r12.w, r17.xyzw, r17.xyzw
            rsq r12.w, r12.w
            mul r17.xyzw, r12.wwww, r17.xyzw
            add r16.xyz, r0.xyzx, -r15.yzwy
            dp2 r12.w, r17.wwww, r17.wwww
            add r12.w, r12.w, l(-1.000000)
            mul r18.xy, r16.yzyy, r17.zxzz
            mad r18.xy, r17.yzyy, r16.zxzz, -r18.xyxx
            mul r14.w, r16.x, r17.y
            mad r18.z, r17.x, r16.y, -r14.w
            mul r18.xyz, r17.wwww, r18.xyzx
            add r18.xyz, r18.xyzx, r18.xyzx
            mad r18.xyz, r16.xyzx, r12.wwww, -r18.xyzx
            dp3 r14.w, r17.xyzx, r16.xyzx
            mul r16.xyz, r14.wwww, r17.xyzx
            mad r16.xyz, r16.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r18.xyzx
            add r18.xyz, r1.xzwx, -r19.xyzx
            dp2 r14.w, r20.wwww, r20.wwww
            add r14.w, r14.w, l(-1.000000)
            mul r21.xy, r18.yzyy, r20.zxzz
            mad r21.xy, r20.yzyy, r18.zxzz, -r21.xyxx
            mul r18.w, r18.x, r20.y
            mad r21.z, r20.x, r18.y, -r18.w
            mul r21.xyz, r20.wwww, r21.xyzx
            add r21.xyz, r21.xyzx, r21.xyzx
            mad r21.xyz, r18.xyzx, r14.wwww, -r21.xyzx
            dp3 r18.x, r20.xyzx, r18.xyzx
            mul r18.xyz, r18.xxxx, r20.xyzx
            mad r10.xyz, r18.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r21.xyzx
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r18.xyzw, r15.x, l(0), t0.xyzw
            ieq r19.w, r11.w, l(2)
            if_nz r19.w
              add r21.xyz, -r10.xyzx, r16.xyzx
              div r21.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), r21.xyzx
              add r22.xyz, r18.xyzx, cb0[18].zzzz
              add r22.xyz, r22.xyzx, cb0[18].wwww
              add r23.xyz, -r10.xyzx, r22.xyzx
              mul r23.xyz, r21.xyzx, r23.xyzx
              add r24.xyz, -r10.xyzx, -r22.xyzx
              mul r21.xyz, r21.xyzx, r24.xyzx
              min r24.xyz, r21.xyzx, r23.xyzx
              max r19.w, r24.x, l(0.000000)
              max r21.xyz, r21.xyzx, r23.xyzx
              min r21.x, r21.x, l(1.000000)
              max r19.w, r24.y, r19.w
              min r21.x, r21.y, r21.x
              max r19.w, r24.z, r19.w
              min r21.x, r21.z, r21.x
              lt r19.w, r19.w, r21.x
              if_nz r19.w
                ilt r19.w, r6.z, r3.w
                if_nz r19.w
                  add r21.xyz, r10.xyzx, -r22.xyzx
                  min r19.w, |r21.x|, l(340282346638528859811704183484516925440.000000)
                  add r22.xyz, r10.xyzx, r22.xyzx
                  lt r21.x, |r22.x|, r19.w
                  mov r4.w, -r18.x
                  mov r5.w, r4.w
                  movc r23.xyzw, r21.xxxx, r4.xyzw, r5.xyzw
                  min r4.w, r19.w, |r22.x|
                  lt r5.w, |r21.y|, r4.w
                  mov r6.w, -r18.y
                  movc r23.xyzw, r5.wwww, r6.xyxw, r23.xyzw
                  min r4.w, |r21.y|, r4.w
                  lt r5.w, |r22.y|, r4.w
                  mov r7.w, r6.w
                  movc r23.xyzw, r5.wwww, r7.xyxw, r23.xyzw
                  min r4.w, |r22.y|, r4.w
                  lt r5.w, |r21.z|, r4.w
                  mov r8.w, -r18.z
                  movc r23.xyzw, r5.wwww, r8.xxzw, r23.xyzw
                  min r4.w, |r21.z|, r4.w
                  lt r4.w, |r22.z|, r4.w
                  mov r9.w, r8.w
                  movc r21.xyzw, r4.wwww, r9.xxzw, r23.xyzw
                  mul r22.xy, r16.yzyy, r20.zxzz
                  mad r22.xy, r20.yzyy, r16.zxzz, -r22.xyxx
                  mul r4.w, r16.x, r20.y
                  mad r22.z, r20.x, r16.y, -r4.w
                  mul r22.xyz, r20.wwww, r22.xyzx
                  add r22.xyz, r22.xyzx, r22.xyzx
                  mad r22.xyz, r16.xyzx, r14.wwww, r22.xyzx
                  dp3 r4.w, r20.xyzx, r16.xyzx
                  mul r23.xyz, r4.wwww, r20.xyzx
                  mad r22.xyz, r23.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r22.xyzx
                  add r22.xyz, r19.xyzx, r22.xyzx
                  add r22.xyz, r0.xyzx, -r22.xyzx
                  imad r4.w, vThreadID.x, r3.w, r6.z
                  mul r23.xy, r17.zxzz, r21.yzyy
                  mad r23.xy, r17.yzyy, r21.zxzz, -r23.xyxx
                  mul r5.w, r17.y, r21.x
                  mad r23.z, r17.x, r21.y, -r5.w
                  mul r23.xyz, r17.wwww, r23.xyzx
                  add r23.xyz, r23.xyzx, r23.xyzx
                  mad r23.xyz, r21.xyzx, r12.wwww, r23.xyzx
                  dp3 r5.w, r17.xyzx, r21.xyzx
                  mul r21.xyz, r5.wwww, r17.xyzx
                  mad r23.xyz, r21.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r23.xyzx
                  dp3 r5.w, r23.xyzx, r15.yzwy
                  add r23.w, -r5.w, r21.w
                  and r5.w, r9.y, l(16)
                  movc r21.xyzw, r5.wwww, l(0,0,0,0), r23.xyzw
                  store_structured u1.xyzw, r4.w, l(0), r21.xyzw
                  itof r22.w, r15.x
                  store_structured u2.xyzw, r4.w, l(0), r22.xyzw
                  iadd r6.z, r6.z, l(1)
                endif 
              endif 
            else 
              ieq r4.w, r11.w, l(3)
              if_nz r4.w
                iadd r4.w, r18.w, l(-1)
                ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r21.xy, r4.w, l(32), t12.xyxx
                add r22.xyz, -r10.xyzx, r16.xyzx
                iadd r4.w, r21.x, r21.y
                div r21.yzw, l(1.000000, 1.000000, 1.000000, 1.000000), r18.xxyz
                mov r23.xyz, l(0,0,0,0)
                mov r24.x, l(0)
                mov r25.y, l(1.000000)
                mov r26.xy, l(340282346638528859811704183484516925440.000000,0,0,0)
                mov r5.w, r21.x
                loop 
                  ige r6.w, r5.w, r4.w
                  breakc_nz r6.w
                  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r27.xyzw, r5.w, l(0), t13.xyzw
                  mul r27.xyz, r21.yzwy, r27.xyzx
                  dp3 r6.w, r27.xyzx, r27.xyzx
                  sqrt r6.w, r6.w
                  div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
                  mul r28.xyzw, r27.xwyz, r6.wwww
                  mad r6.w, r6.w, r27.w, -cb0[18].z
                  add r27.w, r6.w, -cb0[18].w
                  mov r27.xyz, r28.xzwx
                  dp4 r6.w, r27.xyzw, r10.xyzw
                  dp3 r7.w, r27.xyzx, r22.xyzx
                  ne r8.w, r7.w, l(0.000000)
                  if_nz r8.w
                    div r8.w, -r6.w, r7.w
                    lt r7.w, r7.w, l(0.000000)
                    lt r9.w, r24.x, r8.w
                    movc r25.x, r9.w, r8.w, r24.x
                    lt r9.w, r8.w, r25.y
                    movc r24.y, r9.w, r8.w, r25.y
                    movc r18.zw, r7.wwww, r25.xxxy, r24.xxxy
                    ge r7.w, r18.z, r18.w
                    if_nz r7.w
                      mov r24.x, r18.z
                      mov r25.y, r18.w
                      break 
                    endif 
                    mov r24.x, r18.z
                    mov r25.y, r18.w
                  else 
                    lt r7.w, l(0.000000), r6.w
                    if_nz r7.w
                      add r7.w, r25.y, l(1.000000)
                      mov r24.x, r7.w
                      break 
                    endif 
                  endif 
                  mov r28.x, |r6.w|
                  lt r6.w, r28.x, r26.x
                  movc r23.xyz, r6.wwww, r27.xyzx, r23.xyzx
                  movc r26.xy, r6.wwww, r28.xyxx, r26.xyxx
                  iadd r5.w, r5.w, l(1)
                endloop 
                lt r4.w, r24.x, r25.y
                if_nz r4.w
                  ilt r4.w, r6.z, r3.w
                  if_nz r4.w
                    mul r18.zw, r16.yyyz, r20.zzzx
                    mad r21.xy, r20.yzyy, r16.zxzz, -r18.zwzz
                    mul r4.w, r16.x, r20.y
                    mad r21.z, r20.x, r16.y, -r4.w
                    mul r21.xyz, r20.wwww, r21.xyzx
                    add r21.xyz, r21.xyzx, r21.xyzx
                    mad r21.xyz, r16.xyzx, r14.wwww, r21.xyzx
                    dp3 r4.w, r20.xyzx, r16.xyzx
                    mul r22.xyz, r4.wwww, r20.xyzx
                    mad r21.xyz, r22.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r21.xyzx
                    add r21.xyz, r19.xyzx, r21.xyzx
                    add r21.xyz, r0.xyzx, -r21.xyzx
                    imad r4.w, vThreadID.x, r3.w, r6.z
                    mul r18.zw, r17.zzzx, r23.yyyz
                    mad r22.xy, r17.yzyy, r23.zxzz, -r18.zwzz
                    mul r5.w, r17.y, r23.x
                    mad r22.z, r17.x, r23.y, -r5.w
                    mul r22.xyz, r17.wwww, r22.xyzx
                    add r22.xyz, r22.xyzx, r22.xyzx
                    mad r22.xyz, r23.xyzx, r12.wwww, r22.xyzx
                    dp3 r5.w, r17.xyzx, r23.xyzx
                    mul r24.yzw, r5.wwww, r17.xxyz
                    mad r22.xyz, r24.yzwy, l(2.000000, 2.000000, 2.000000, 0.000000), r22.xyzx
                    dp3 r5.w, r22.xyzx, r15.yzwy
                    add r22.w, -r5.w, r26.y
                    and r5.w, r9.y, l(16)
                    movc r22.xyzw, r5.wwww, l(0,0,0,0), r22.xyzw
                    store_structured u1.xyzw, r4.w, l(0), r22.xyzw
                    itof r21.w, r15.x
                    store_structured u2.xyzw, r4.w, l(0), r21.xyzw
                    iadd r6.z, r6.z, l(1)
                  endif 
                endif 
              else 
                if_z r11.w
                  dp3 r4.w, r16.xyzx, r16.xyzx
                  sqrt r5.w, r4.w
                  add r5.w, -r18.x, r5.w
                  add r5.w, r5.w, -cb0[18].z
                  lt r5.w, r5.w, cb0[18].w
                  if_nz r5.w
                    ilt r5.w, r6.z, r3.w
                    if_nz r5.w
                      lt r5.w, l(0.000000), r4.w
                      rsq r4.w, r4.w
                      mul r21.xyz, r4.wwww, r16.xyzx
                      and r21.xyz, r5.wwww, r21.xyzx
                      mul r18.zw, r16.yyyz, r20.zzzx
                      mad r22.xy, r20.yzyy, r16.zxzz, -r18.zwzz
                      mul r4.w, r16.x, r20.y
                      mad r22.z, r20.x, r16.y, -r4.w
                      mul r22.xyz, r20.wwww, r22.xyzx
                      add r22.xyz, r22.xyzx, r22.xyzx
                      mad r22.xyz, r16.xyzx, r14.wwww, r22.xyzx
                      dp3 r4.w, r20.xyzx, r16.xyzx
                      mul r24.yzw, r4.wwww, r20.xxyz
                      mad r22.xyz, r24.yzwy, l(2.000000, 2.000000, 2.000000, 0.000000), r22.xyzx
                      add r22.xyz, r19.xyzx, r22.xyzx
                      add r22.xyz, r0.xyzx, -r22.xyzx
                      imad r4.w, vThreadID.x, r3.w, r6.z
                      mul r18.zw, r17.zzzx, r21.yyyz
                      mad r27.xy, r17.yzyy, r21.zxzz, -r18.zwzz
                      mul r5.w, r17.y, r21.x
                      mad r27.z, r17.x, r21.y, -r5.w
                      mul r24.yzw, r17.wwww, r27.xxyz
                      add r24.yzw, r24.yyzw, r24.yyzw
                      mad r24.yzw, r21.xxyz, r12.wwww, r24.yyzw
                      dp3 r5.w, r17.xyzx, r21.xyzx
                      mul r21.xyz, r5.wwww, r17.xyzx
                      mad r21.xyz, r21.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r24.yzwy
                      dp3 r5.w, r21.xyzx, r15.yzwy
                      add r21.w, -r5.w, -r18.x
                      and r5.w, r9.y, l(16)
                      movc r21.xyzw, r5.wwww, l(0,0,0,0), r21.xyzw
                      store_structured u1.xyzw, r4.w, l(0), r21.xyzw
                      itof r22.w, r15.x
                      store_structured u2.xyzw, r4.w, l(0), r22.xyzw
                      iadd r6.z, r6.z, l(1)
                    endif 
                  endif 
                else 
                  ieq r4.w, r11.w, l(1)
                  if_nz r4.w
                    lt r4.w, r18.y, r10.x
                    lt r5.w, r10.x, -r18.y
                    movc r5.w, r5.w, -r18.y, r10.x
                    movc r11.x, r4.w, r18.y, r5.w
                    add r21.xyz, -r11.xzzx, r10.xyzx
                    dp3 r4.w, r21.xyzx, r21.xyzx
                    sqrt r5.w, r4.w
                    add r5.w, -r18.x, r5.w
                    add r5.w, r5.w, -cb0[18].z
                    add r12.xy, -r18.xxxx, -r18.yyyy
                    add r6.w, r18.x, r18.y
                    add r22.xyz, -r10.xyzx, r16.xyzx
                    add r6.w, -r12.x, r6.w
                    add r24.yzw, -r12.yyzz, r10.xxyz
                    dp3 r7.w, r22.xyzx, r22.xyzx
                    dp3 r8.w, r22.xyzx, r24.yzwy
                    mul r9.w, r6.w, r6.w
                    mul r12.x, r6.w, r24.y
                    mul r18.z, r6.w, r22.x
                    mul r18.w, r18.z, r18.z
                    mad r18.w, r7.w, r9.w, -r18.w
                    ne r19.w, r18.w, l(0.000000)
                    mul r21.w, r8.w, r9.w
                    mad r21.w, r18.z, r12.x, -r21.w
                    div_sat r18.w, r21.w, r18.w
                    and r27.x, r18.w, r19.w
                    mad r12.x, r18.z, r27.x, r12.x
                    div r27.y, r12.x, r9.w
                    lt r9.w, r27.y, l(0.000000)
                    div_sat r13.z, -r8.w, r7.w
                    lt r12.x, l(1.000000), r27.y
                    mad r8.w, r22.x, r6.w, -r8.w
                    div_sat r13.x, r8.w, r7.w
                    movc r18.zw, r12.xxxx, r13.xxxy, r27.xxxy
                    movc r13.xz, r9.wwww, r13.zzwz, r18.zzwz
                    mad r10.xyz, r22.xyzx, r13.xxxx, r10.xyzx
                    mad r14.x, r6.w, r13.z, r12.y
                    add r10.xyz, -r14.xyzx, r10.xyzx
                    dp3 r6.w, r10.xyzx, r10.xyzx
                    add r7.w, r2.w, r18.x
                    mul r7.w, r7.w, r7.w
                    ge r6.w, r7.w, r6.w
                    lt r5.w, r5.w, cb0[18].w
                    or r5.w, r5.w, r6.w
                    if_nz r5.w
                      ilt r5.w, r6.z, r3.w
                      if_nz r5.w
                        lt r5.w, l(0.000000), r4.w
                        rsq r4.w, r4.w
                        mul r10.xyz, r4.wwww, r21.xyzx
                        and r10.xyz, r5.wwww, r10.xyzx
                        mad r21.xyz, r10.xyzx, r18.xxxx, r11.xyzx
                        dp3 r4.w, r10.xyzx, r21.xyzx
                        mul r12.xy, r16.yzyy, r20.zxzz
                        mad r21.xy, r20.yzyy, r16.zxzz, -r12.xyxx
                        mul r5.w, r16.x, r20.y
                        mad r21.z, r20.x, r16.y, -r5.w
                        mul r21.xyz, r20.wwww, r21.xyzx
                        add r21.xyz, r21.xyzx, r21.xyzx
                        mad r21.xyz, r16.xyzx, r14.wwww, r21.xyzx
                        dp3 r5.w, r20.xyzx, r16.xyzx
                        mul r22.xyz, r5.wwww, r20.xyzx
                        mad r21.xyz, r22.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r21.xyzx
                        add r21.xyz, r19.xyzx, r21.xyzx
                        add r21.xyz, r0.xyzx, -r21.xyzx
                        imad r5.w, vThreadID.x, r3.w, r6.z
                        mul r12.xy, r10.yzyy, r17.zxzz
                        mad r22.xy, r17.yzyy, r10.zxzz, -r12.xyxx
                        mul r6.w, r10.x, r17.y
                        mad r22.z, r17.x, r10.y, -r6.w
                        mul r22.xyz, r17.wwww, r22.xyzx
                        add r22.xyz, r22.xyzx, r22.xyzx
                        mad r22.xyz, r10.xyzx, r12.wwww, r22.xyzx
                        dp3 r6.w, r17.xyzx, r10.xyzx
                        mul r10.xyz, r6.wwww, r17.xyzx
                        mad r22.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r22.xyzx
                        dp3 r6.w, r22.xyzx, r15.yzwy
                        add r22.w, -r4.w, -r6.w
                        and r4.w, r9.y, l(16)
                        movc r22.xyzw, r4.wwww, l(0,0,0,0), r22.xyzw
                        store_structured u1.xyzw, r5.w, l(0), r22.xyzw
                        itof r21.w, r15.x
                        store_structured u2.xyzw, r5.w, l(0), r21.xyzw
                        iadd r6.z, r6.z, l(1)
                      endif 
                    endif 
                  else 
                    ieq r4.w, r11.w, l(5)
                    if_nz r4.w
                      div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r18.x
                      mul r21.xyz, r4.wwww, r16.xyzx
                      lt r10.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r21.xyzx
                      lt r22.xyz, r21.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
                      and r5.w, r10.x, r22.x
                      and r5.w, r10.y, r5.w
                      and r5.w, r22.y, r5.w
                      and r5.w, r10.z, r5.w
                      and r5.w, r22.z, r5.w
                      if_nz r5.w
                        iadd r5.w, r18.y, l(-1)
                        switch r5.w
                          case l(0)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t15.yzwx, s0, l(0.000000)
                          break 
                          case l(1)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t16.yzwx, s0, l(0.000000)
                          break 
                          case l(2)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t17.yzwx, s0, l(0.000000)
                          break 
                          case l(3)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t18.yzwx, s0, l(0.000000)
                          break 
                          case l(4)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t19.yzwx, s0, l(0.000000)
                          break 
                          case l(5)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t20.yzwx, s0, l(0.000000)
                          break 
                          case l(6)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t21.yzwx, s0, l(0.000000)
                          break 
                          case l(7)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t22.yzwx, s0, l(0.000000)
                          break 
                          case l(8)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t23.yzwx, s0, l(0.000000)
                          break 
                          case l(9)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t24.yzwx, s0, l(0.000000)
                          break 
                          case l(10)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t25.yzwx, s0, l(0.000000)
                          break 
                          case l(11)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t26.yzwx, s0, l(0.000000)
                          break 
                          case l(12)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t27.yzwx, s0, l(0.000000)
                          break 
                          case l(13)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t28.yzwx, s0, l(0.000000)
                          break 
                          case l(14)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t29.yzwx, s0, l(0.000000)
                          break 
                          case l(15)
                          sample_l_indexable(texture3d)(float,float,float,float) r6.w, r21.xyzx, t30.yzwx, s0, l(0.000000)
                          break 
                          default 
                          mov r6.w, l(0)
                          break 
                        endswitch 
                        mul r7.w, r2.w, r4.w
                        lt r7.w, r6.w, r7.w
                        if_nz r7.w
                          ld_structured_indexable(structured_buffer, stride=32)(mixed,mixed,mixed,mixed) r10.xyz, r5.w, l(0), t14.xyzx
                          itof r10.xyz, r10.xyzx
                          div r10.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), r10.xyzx
                          mad r18.yzw, r16.xxyz, r4.wwww, -r10.xxyz
                          mad r10.xyz, r16.xyzx, r4.wwww, r10.xyzx
                          switch r5.w
                            case l(0)
                            mov r21.w, r10.x
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r21.wyzw, t15.yzwx, s0, l(0.000000)
                            break 
                            case l(1)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t16.yzwx, s0, l(0.000000)
                            break 
                            case l(2)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t17.yzwx, s0, l(0.000000)
                            break 
                            case l(3)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t18.yzwx, s0, l(0.000000)
                            break 
                            case l(4)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t19.yzwx, s0, l(0.000000)
                            break 
                            case l(5)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t20.yzwx, s0, l(0.000000)
                            break 
                            case l(6)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t21.yzwx, s0, l(0.000000)
                            break 
                            case l(7)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t22.yzwx, s0, l(0.000000)
                            break 
                            case l(8)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t23.yzwx, s0, l(0.000000)
                            break 
                            case l(9)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t24.yzwx, s0, l(0.000000)
                            break 
                            case l(10)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t25.yzwx, s0, l(0.000000)
                            break 
                            case l(11)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t26.yzwx, s0, l(0.000000)
                            break 
                            case l(12)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t27.yzwx, s0, l(0.000000)
                            break 
                            case l(13)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t28.yzwx, s0, l(0.000000)
                            break 
                            case l(14)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t29.yzwx, s0, l(0.000000)
                            break 
                            case l(15)
                            mov r16.x, r10.x
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r16.xyzx, t30.yzwx, s0, l(0.000000)
                            break 
                            default 
                            mov r4.w, l(0)
                            break 
                          endswitch 
                          switch r5.w
                            case l(0)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t15.yzwx, s0, l(0.000000)
                            break 
                            case l(1)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t16.yzwx, s0, l(0.000000)
                            break 
                            case l(2)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t17.yzwx, s0, l(0.000000)
                            break 
                            case l(3)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t18.yzwx, s0, l(0.000000)
                            break 
                            case l(4)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t19.yzwx, s0, l(0.000000)
                            break 
                            case l(5)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t20.yzwx, s0, l(0.000000)
                            break 
                            case l(6)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t21.yzwx, s0, l(0.000000)
                            break 
                            case l(7)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t22.yzwx, s0, l(0.000000)
                            break 
                            case l(8)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t23.yzwx, s0, l(0.000000)
                            break 
                            case l(9)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t24.yzwx, s0, l(0.000000)
                            break 
                            case l(10)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t25.yzwx, s0, l(0.000000)
                            break 
                            case l(11)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t26.yzwx, s0, l(0.000000)
                            break 
                            case l(12)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t27.yzwx, s0, l(0.000000)
                            break 
                            case l(13)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t28.yzwx, s0, l(0.000000)
                            break 
                            case l(14)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t29.yzwx, s0, l(0.000000)
                            break 
                            case l(15)
                            mov r16.x, r18.y
                            mov r16.yz, r21.yyzy
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r16.xyzx, t30.yzwx, s0, l(0.000000)
                            break 
                            default 
                            mov r7.w, l(0)
                            break 
                          endswitch 
                          add r16.x, r4.w, -r7.w
                          switch r5.w
                            case l(0)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t15.yzwx, s0, l(0.000000)
                            break 
                            case l(1)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t16.yzwx, s0, l(0.000000)
                            break 
                            case l(2)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t17.yzwx, s0, l(0.000000)
                            break 
                            case l(3)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t18.yzwx, s0, l(0.000000)
                            break 
                            case l(4)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t19.yzwx, s0, l(0.000000)
                            break 
                            case l(5)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t20.yzwx, s0, l(0.000000)
                            break 
                            case l(6)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t21.yzwx, s0, l(0.000000)
                            break 
                            case l(7)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t22.yzwx, s0, l(0.000000)
                            break 
                            case l(8)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t23.yzwx, s0, l(0.000000)
                            break 
                            case l(9)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t24.yzwx, s0, l(0.000000)
                            break 
                            case l(10)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t25.yzwx, s0, l(0.000000)
                            break 
                            case l(11)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t26.yzwx, s0, l(0.000000)
                            break 
                            case l(12)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t27.yzwx, s0, l(0.000000)
                            break 
                            case l(13)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t28.yzwx, s0, l(0.000000)
                            break 
                            case l(14)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t29.yzwx, s0, l(0.000000)
                            break 
                            case l(15)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r10.y
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r22.xyzx, t30.yzwx, s0, l(0.000000)
                            break 
                            default 
                            mov r4.w, l(0)
                            break 
                          endswitch 
                          switch r5.w
                            case l(0)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t15.yzwx, s0, l(0.000000)
                            break 
                            case l(1)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t16.yzwx, s0, l(0.000000)
                            break 
                            case l(2)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t17.yzwx, s0, l(0.000000)
                            break 
                            case l(3)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t18.yzwx, s0, l(0.000000)
                            break 
                            case l(4)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t19.yzwx, s0, l(0.000000)
                            break 
                            case l(5)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t20.yzwx, s0, l(0.000000)
                            break 
                            case l(6)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t21.yzwx, s0, l(0.000000)
                            break 
                            case l(7)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t22.yzwx, s0, l(0.000000)
                            break 
                            case l(8)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t23.yzwx, s0, l(0.000000)
                            break 
                            case l(9)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t24.yzwx, s0, l(0.000000)
                            break 
                            case l(10)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t25.yzwx, s0, l(0.000000)
                            break 
                            case l(11)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t26.yzwx, s0, l(0.000000)
                            break 
                            case l(12)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t27.yzwx, s0, l(0.000000)
                            break 
                            case l(13)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t28.yzwx, s0, l(0.000000)
                            break 
                            case l(14)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t29.yzwx, s0, l(0.000000)
                            break 
                            case l(15)
                            mov r22.xz, r21.xxzx
                            mov r22.y, r18.z
                            sample_l_indexable(texture3d)(float,float,float,float) r7.w, r22.xyzx, t30.yzwx, s0, l(0.000000)
                            break 
                            default 
                            mov r7.w, l(0)
                            break 
                          endswitch 
                          add r16.y, r4.w, -r7.w
                          switch r5.w
                            case l(0)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t15.yzwx, s0, l(0.000000)
                            break 
                            case l(1)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t16.yzwx, s0, l(0.000000)
                            break 
                            case l(2)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t17.yzwx, s0, l(0.000000)
                            break 
                            case l(3)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t18.yzwx, s0, l(0.000000)
                            break 
                            case l(4)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t19.yzwx, s0, l(0.000000)
                            break 
                            case l(5)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t20.yzwx, s0, l(0.000000)
                            break 
                            case l(6)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t21.yzwx, s0, l(0.000000)
                            break 
                            case l(7)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t22.yzwx, s0, l(0.000000)
                            break 
                            case l(8)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t23.yzwx, s0, l(0.000000)
                            break 
                            case l(9)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t24.yzwx, s0, l(0.000000)
                            break 
                            case l(10)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t25.yzwx, s0, l(0.000000)
                            break 
                            case l(11)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t26.yzwx, s0, l(0.000000)
                            break 
                            case l(12)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t27.yzwx, s0, l(0.000000)
                            break 
                            case l(13)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t28.yzwx, s0, l(0.000000)
                            break 
                            case l(14)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t29.yzwx, s0, l(0.000000)
                            break 
                            case l(15)
                            mov r10.xy, r21.xyxx
                            sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t30.yzwx, s0, l(0.000000)
                            break 
                            default 
                            mov r4.w, l(0)
                            break 
                          endswitch 
                          switch r5.w
                            case l(0)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t15.yzwx, s0, l(0.000000)
                            break 
                            case l(1)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t16.yzwx, s0, l(0.000000)
                            break 
                            case l(2)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t17.yzwx, s0, l(0.000000)
                            break 
                            case l(3)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t18.yzwx, s0, l(0.000000)
                            break 
                            case l(4)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t19.yzwx, s0, l(0.000000)
                            break 
                            case l(5)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t20.yzwx, s0, l(0.000000)
                            break 
                            case l(6)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t21.yzwx, s0, l(0.000000)
                            break 
                            case l(7)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t22.yzwx, s0, l(0.000000)
                            break 
                            case l(8)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t23.yzwx, s0, l(0.000000)
                            break 
                            case l(9)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t24.yzwx, s0, l(0.000000)
                            break 
                            case l(10)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t25.yzwx, s0, l(0.000000)
                            break 
                            case l(11)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t26.yzwx, s0, l(0.000000)
                            break 
                            case l(12)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t27.yzwx, s0, l(0.000000)
                            break 
                            case l(13)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t28.yzwx, s0, l(0.000000)
                            break 
                            case l(14)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t29.yzwx, s0, l(0.000000)
                            break 
                            case l(15)
                            mov r18.yz, r21.xxyx
                            sample_l_indexable(texture3d)(float,float,float,float) r5.w, r18.yzwy, t30.yzwx, s0, l(0.000000)
                            break 
                            default 
                            mov r5.w, l(0)
                            break 
                          endswitch 
                          add r16.z, r4.w, -r5.w
                          dp3 r4.w, r16.xyzx, r16.xyzx
                          lt r5.w, l(0.000000), r4.w
                          if_nz r5.w
                            ilt r5.w, r6.z, r3.w
                            if_nz r5.w
                              mul r10.xyz, r18.xxxx, r21.xyzx
                              rsq r4.w, r4.w
                              mul r16.xyz, r4.wwww, r16.xyzx
                              dp3 r4.w, r10.xyzx, r16.xyzx
                              mad r4.w, r18.x, r6.w, -r4.w
                              mul r11.xw, r10.yyyz, r20.zzzx
                              mad r18.xy, r20.yzyy, r10.zxzz, -r11.xwxx
                              mul r5.w, r10.x, r20.y
                              mad r18.z, r20.x, r10.y, -r5.w
                              mul r18.xyz, r20.wwww, r18.xyzx
                              add r18.xyz, r18.xyzx, r18.xyzx
                              mad r18.xyz, r10.xyzx, r14.wwww, r18.xyzx
                              dp3 r5.w, r20.xyzx, r10.xyzx
                              mul r10.xyz, r5.wwww, r20.xyzx
                              mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r18.xyzx
                              add r10.xyz, r19.xyzx, r10.xyzx
                              add r18.xyz, r0.xyzx, -r10.xyzx
                              imad r5.w, vThreadID.x, r3.w, r6.z
                              mul r10.xy, r16.yzyy, r17.zxzz
                              mad r10.xy, r17.yzyy, r16.zxzz, -r10.xyxx
                              mul r6.w, r16.x, r17.y
                              mad r10.z, r17.x, r16.y, -r6.w
                              mul r10.xyz, r17.wwww, r10.xyzx
                              add r10.xyz, r10.xyzx, r10.xyzx
                              mad r10.xyz, r16.xyzx, r12.wwww, r10.xyzx
                              dp3 r6.w, r17.xyzx, r16.xyzx
                              mul r12.xyw, r6.wwww, r17.xyxz
                              mad r17.xyz, r12.xywx, l(2.000000, 2.000000, 2.000000, 0.000000), r10.xyzx
                              dp3 r6.w, r17.xyzx, r15.yzwy
                              add r17.w, r4.w, -r6.w
                              and r4.w, r9.y, l(16)
                              movc r17.xyzw, r4.wwww, l(0,0,0,0), r17.xyzw
                              store_structured u1.xyzw, r5.w, l(0), r17.xyzw
                              itof r18.w, r15.x
                              store_structured u2.xyzw, r5.w, l(0), r18.xyzw
                              iadd r6.z, r6.z, l(1)
                            endif 
                          endif 
                        endif 
                      endif 
                    endif 
                  endif 
                endif 
              endif 
            endif 
          endif 
          mov r7.z, r8.y
        else 
          and r4.w, r16.w, l(0x7fffffff)
          mov x0[r8.y + 0].x, r15.x
          iadd r5.w, r7.z, l(1)
          mov x0[r7.z + 0].x, r4.w
          mov r7.z, r5.w
        endif 
      else 
        mov r7.z, r8.y
      endif 
    endloop 
    mov r1.y, r6.z
  endif 
  store_structured u0.x, vThreadID.x, l(0), r1.y
endif 
ret 
// Approximately 1044 instruction slots used
