//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for UpdateTriangles::sortedNewPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for UpdateTriangles::sortedVelocities
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for UpdateTriangles::reverseLookup
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for UpdateTriangles::indices
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for UpdateTriangles::triNormals
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for g_NvidiaExt
// {
//
//   struct NvShaderExtnStruct
//   {
//       
//       uint opcode;                   // Offset:    0
//       uint rid;                      // Offset:    4
//       uint sid;                      // Offset:    8
//       uint4 dst1u;                   // Offset:   12
//       uint4 padding0[3];             // Offset:   28
//       uint4 src0u;                   // Offset:   76
//       uint4 src1u;                   // Offset:   92
//       uint4 src2u;                   // Offset:  108
//       uint4 dst0u;                   // Offset:  124
//       uint markUavRef;               // Offset:  140
//       float padding1[28];            // Offset:  144
//
//   } $Element;                        // Offset:    0 Size:   256
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// UpdateTriangles::sortedNewPositions    texture  struct         r/o             t0      1 
// UpdateTriangles::sortedVelocities    texture  struct         r/o             t1      1 
// UpdateTriangles::reverseLookup    texture  struct         r/o             t2      1 
// UpdateTriangles::indices          texture  struct         r/o             t3      1 
// InterlockedFloat::accum               UAV    byte         r/w             u0      1 
// UpdateTriangles::triNormals           UAV  struct         r/w             u1      1 
// g_NvidiaExt                           UAV  struct     r/w+cnt             u7      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[31], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_uav_raw u0
dcl_uav_structured u1, 12
dcl_uav_structured_opc u7, 256
dcl_input vThreadID.x
dcl_temps 7
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[26].w
if_nz r0.x
  imul null, r0.x, vThreadID.x, l(3)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), t3.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), t2.xxxx
  imad r0.yz, vThreadID.xxxx, l(0, 3, 3, 0), l(0, 1, 2, 0)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.y, r0.y, l(0), t3.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.y, r0.y, l(0), t2.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.z, r0.z, l(0), t3.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.z, r0.z, l(0), t2.xxxx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyzw, r0.x, l(0), t0.xyzw
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyzw, r0.y, l(0), t0.xyzw
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyzw, r0.z, l(0), t0.xyzw
  add r4.xyzw, -r1.zyxz, r2.zyxz
  add r5.xyzw, -r1.yzzx, r3.yzzx
  mul r1.xy, r4.ywyy, r5.ywyy
  mad r1.xy, r5.xzxx, r4.xzxx, -r1.xyxx
  mul r0.w, r4.z, r5.x
  mad r1.z, r5.w, r4.y, -r0.w
  dp3 r0.w, r1.xyzx, r1.xyzx
  lt r2.x, l(0.000000), r0.w
  rsq r0.w, r0.w
  mul r1.xyz, r0.wwww, r1.xyzx
  and r4.xyz, r1.xyzx, r2.xxxx
  store_structured u1.xyz, vThreadID.x, l(0), r4.xyzx
  ne r1.xy, cb0[20].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  or r0.w, r1.y, r1.x
  if_nz r0.w
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyz, r0.x, l(0), t1.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, r0.y, l(0), t1.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyz, r0.z, l(0), t1.xyzx
    add r5.xyzw, r1.zzyx, r2.zzyx
    add r5.xyzw, r3.zzyx, r5.xyzw
    mad r5.xyzw, -r5.xyzw, l(0.333300, 0.333300, 0.333300, 0.333300), cb0[30].zzyx
    dp3 r0.w, r5.yzwy, r5.yzwy
    lt r1.x, l(0.000000), r0.w
    rsq r1.y, r0.w
    mul r2.xyz, r1.yyyy, r5.wzyw
    and r1.xyz, r1.xxxx, r2.xyzx
    dp3 r4.w, r1.xyzx, r4.xyzx
    lt r1.x, r4.w, l(0.000000)
    movc r4.xyzw, r1.xxxx, -r4.xyzw, r4.xyzw
    mul r1.xy, cb0[20].xyxx, cb0[23].zzzz
    mul r1.xy, r4.wwww, r1.xyxx
    sqrt r0.w, r0.w
    mad r1.z, -r4.w, r4.w, l(1.000000)
    max r1.z, r1.z, l(0.000000)
    sqrt r1.z, r1.z
    mul r1.y, r1.z, r1.y
    min r1.y, r1.y, l(1.000000)
    max r1.y, r1.y, l(-1.000000)
    mul r0.w, r0.w, r1.y
    mul r1.yz, r4.yyzy, r5.yywy
    mad r6.xyzw, r5.yzzy, r4.xzzx, -r1.zyyz
    mul r1.y, r4.x, r5.z
    mad r1.y, r5.w, r4.y, -r1.y
    mul r2.xy, r5.ywyy, r6.ywyy
    mul r1.z, r5.z, r1.y
    mad r3.x, r6.x, r5.x, -r1.z
    mad r3.y, r1.y, r5.w, -r2.x
    mad r3.z, r6.z, r5.z, -r2.y
    dp3 r1.y, r3.xyzx, r3.xyzx
    lt r1.z, l(0.000000), r1.y
    rsq r1.y, r1.y
    mul r2.xyz, r1.yyyy, r3.xyzx
    and r2.xyz, r1.zzzz, r2.xyzx
    mul r2.xyz, r0.wwww, r2.xyzx
    mad r1.xyz, r1.xxxx, r5.wzyw, r2.xyzx
    ishl r0.w, r0.x, l(4)
    mul r2.xyz, r1.wwww, r1.xyzx
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(140), l(1)
    store_raw u0.x, r4.x, l(0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(76), r0.w
    store_structured u7.x, r4.x, l(92), r2.x
    store_structured u7.x, r4.x, l(108), l(3)
    store_structured u7.x, r4.x, l(0), l(13)
    bfi r3.xyz, l(28, 28, 28, 0), l(4, 4, 4, 0), r0.xxxx, l(4, 8, 12, 0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(140), l(1)
    store_raw u0.x, r4.x, l(0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(76), r3.x
    store_structured u7.x, r4.x, l(92), r2.y
    store_structured u7.x, r4.x, l(108), l(3)
    store_structured u7.x, r4.x, l(0), l(13)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(140), l(1)
    store_raw u0.x, r4.x, l(0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(76), r3.y
    store_structured u7.x, r4.x, l(92), r2.z
    store_structured u7.x, r4.x, l(108), l(3)
    store_structured u7.x, r4.x, l(0), l(13)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(140), l(1)
    store_raw u0.x, r4.x, l(0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(76), r3.z
    store_structured u7.x, r4.x, l(92), l(1.000000)
    store_structured u7.x, r4.x, l(108), l(3)
    store_structured u7.x, r4.x, l(0), l(13)
    ishl r0.x, r0.y, l(4)
    mul r2.xyz, r2.wwww, r1.xyzx
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(140), l(1)
    store_raw u0.x, r4.x, l(0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(76), r0.x
    store_structured u7.x, r4.x, l(92), r2.x
    store_structured u7.x, r4.x, l(108), l(3)
    store_structured u7.x, r4.x, l(0), l(13)
    bfi r0.xyw, l(28, 28, 0, 28), l(4, 4, 0, 4), r0.yyyy, l(4, 8, 0, 12)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(140), l(1)
    store_raw u0.x, r4.x, l(0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(76), r0.x
    store_structured u7.x, r4.x, l(92), r2.y
    store_structured u7.x, r4.x, l(108), l(3)
    store_structured u7.x, r4.x, l(0), l(13)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(140), l(1)
    store_raw u0.x, r4.x, l(0)
    imm_atomic_alloc r4.x, u7
    store_structured u7.x, r4.x, l(76), r0.y
    store_structured u7.x, r4.x, l(92), r2.z
    store_structured u7.x, r4.x, l(108), l(3)
    store_structured u7.x, r4.x, l(0), l(13)
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(140), l(1)
    store_raw u0.x, r2.x, l(0)
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(76), r0.w
    store_structured u7.x, r2.x, l(92), l(1.000000)
    store_structured u7.x, r2.x, l(108), l(3)
    store_structured u7.x, r2.x, l(0), l(13)
    ishl r0.x, r0.z, l(4)
    mul r1.xyz, r3.wwww, r1.xyzx
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(140), l(1)
    store_raw u0.x, r2.x, l(0)
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(76), r0.x
    store_structured u7.x, r2.x, l(92), r1.x
    store_structured u7.x, r2.x, l(108), l(3)
    store_structured u7.x, r2.x, l(0), l(13)
    bfi r0.xyz, l(28, 28, 28, 0), l(4, 4, 4, 0), r0.zzzz, l(4, 8, 12, 0)
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(140), l(1)
    store_raw u0.x, r2.x, l(0)
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(76), r0.x
    store_structured u7.x, r2.x, l(92), r1.y
    store_structured u7.x, r2.x, l(108), l(3)
    store_structured u7.x, r2.x, l(0), l(13)
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(140), l(1)
    store_raw u0.x, r2.x, l(0)
    imm_atomic_alloc r2.x, u7
    store_structured u7.x, r2.x, l(76), r0.y
    store_structured u7.x, r2.x, l(92), r1.z
    store_structured u7.x, r2.x, l(108), l(3)
    store_structured u7.x, r2.x, l(0), l(13)
    imm_atomic_alloc r1.x, u7
    store_structured u7.x, r1.x, l(140), l(1)
    store_raw u0.x, r1.x, l(0)
    imm_atomic_alloc r1.x, u7
    store_structured u7.x, r1.x, l(76), r0.z
    store_structured u7.x, r1.x, l(92), l(1.000000)
    store_structured u7.x, r1.x, l(108), l(3)
    store_structured u7.x, r1.x, l(0), l(13)
  endif 
endif 
ret 
// Approximately 176 instruction slots used
