//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// Resource bind info for SolveShapes::rigidOffsets
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveShapes::rigidIndices
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveShapes::rigidCoefficients
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveShapes::reverseLookup
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveShapes::localNormals
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveShapes::localPositions
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for SolveShapes::newPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveShapes::rotations
// {
//
//   struct DxQuat
//   {
//       
//       float3 xyz;                    // Offset:    0
//       float w;                       // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveShapes::translations
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for SolveShapes::normals
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SolveShapes::rigidOffsets         texture  struct         r/o             t0      1 
// SolveShapes::rigidIndices         texture  struct         r/o             t1      1 
// SolveShapes::rigidCoefficients    texture  struct         r/o             t2      1 
// SolveShapes::reverseLookup        texture  struct         r/o             t5      1 
// SolveShapes::localNormals         texture  struct         r/o             t7      1 
// InterlockedFloat::accum               UAV    byte         r/w             u0      1 
// SolveShapes::localPositions           UAV  struct         r/w             u1      1 
// SolveShapes::newPositions             UAV  struct         r/w             u2      1 
// SolveShapes::rotations                UAV  struct         r/w             u3      1 
// SolveShapes::translations             UAV  struct         r/w             u4      1 
// SolveShapes::normals                  UAV  struct         r/w             u5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 4
dcl_resource_structured t2, 4
dcl_resource_structured t5, 4
dcl_resource_structured t7, 16
dcl_uav_raw u0
dcl_uav_structured u1, 12
dcl_uav_structured u2, 16
dcl_uav_structured u3, 16
dcl_uav_structured u4, 12
dcl_uav_structured u5, 16
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 11
dcl_tgsm_raw g0, 12
dcl_tgsm_raw g1, 12
dcl_tgsm_raw g2, 36
dcl_tgsm_structured g3, 12, 64
dcl_tgsm_raw g4, 16
dcl_thread_group 64, 1, 1
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, vThreadGroupID.x, l(0), t0.xxxx
iadd r0.y, vThreadGroupID.x, l(1)
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.y, r0.y, l(0), t0.xxxx
iadd r0.y, -r0.x, r0.y
iadd r0.z, r0.y, l(63)
ushr r0.z, r0.z, l(6)
if_z vThreadIDInGroup.x
  store_raw g0.xyz, l(0), l(0,0,0,0)
  ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r1.xyz, vThreadGroupID.x, l(0), u4.xyzx
  store_raw g1.xyz, l(0), r1.xyzx
  store_raw g2.xyz, l(0), l(0,0,0,0)
  store_raw g2.xyz, l(12), l(0,0,0,0)
  store_raw g2.xyz, l(24), l(0,0,0,0)
endif 
mov r0.w, vThreadIDInGroup.x
mov r1.x, l(0)
loop 
  ige r1.y, r1.x, r0.z
  breakc_nz r1.y
  bfi r1.y, l(26), l(6), r1.x, r0.w
  ilt r1.z, r1.y, r0.y
  iadd r1.y, r0.x, r1.y
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, r1.y, l(0), t1.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, r1.y, l(0), t5.xxxx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, r1.y, l(0), u2.xyzx
  and r1.yzw, r1.zzzz, r2.xxyz
  store_structured g3.xyz, r0.w, l(0), r1.yzwy
  mov r1.y, l(32)
  loop 
    uge r1.z, l(0), r1.y
    breakc_nz r1.z
    sync_g_t
    ult r1.z, r0.w, r1.y
    if_nz r1.z
      iadd r1.z, r0.w, r1.y
      ld_structured r2.xyz, r0.w, l(0), g3.xyzx
      ld_structured r3.xyz, r1.z, l(0), g3.xyzx
      add r2.xyz, r2.xyzx, r3.xyzx
      store_structured g3.xyz, r0.w, l(0), r2.xyzx
    endif 
    ushr r1.y, r1.y, l(1)
  endloop 
  sync_g_t
  ld_structured r1.yzw, l(0), l(0), g3.xxyz
  if_z r0.w
    ld_raw r2.xyz, l(0), g0.xyzx
    add r1.yzw, r1.yyzw, r2.xxyz
    store_raw g0.xyz, l(0), r1.yzwy
  endif 
  sync_g_t
  iadd r1.x, r1.x, l(1)
endloop 
if_z vThreadIDInGroup.x
  itof r0.w, r0.y
  ld_raw r1.xyz, l(0), g0.xyzx
  div r1.xyz, r1.xyzx, r0.wwww
  store_raw g0.xyz, l(0), r1.xyzx
  ld_raw r0.w, l(0), g1.xxxx
  add r1.x, -r0.w, r1.x
  lt r1.x, |r1.x|, l(0.000010)
  if_nz r1.x
    store_raw g0.x, l(0), r0.w
  endif 
  ld_raw r0.w, l(4), g1.xxxx
  add r1.x, -r0.w, r1.y
  lt r1.x, |r1.x|, l(0.000010)
  if_nz r1.x
    store_raw g0.x, l(4), r0.w
  endif 
  ld_raw r0.w, l(8), g1.xxxx
  add r1.x, -r0.w, r1.z
  lt r1.x, |r1.x|, l(0.000010)
  if_nz r1.x
    store_raw g0.x, l(8), r0.w
  endif 
endif 
sync_g_t
mov r0.w, vThreadIDInGroup.x
mov r1.x, l(0)
loop 
  ige r1.y, r1.x, r0.z
  breakc_nz r1.y
  bfi r1.y, l(26), l(6), r1.x, r0.w
  ilt r1.z, r1.y, r0.y
  if_nz r1.z
    iadd r1.y, r0.x, r1.y
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.z, r1.y, l(0), t1.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.z, r1.z, l(0), t5.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, r1.z, l(0), u2.xyzx
    ld_raw r3.xyz, l(0), g0.xyzx
    add r2.xyz, r2.xyzx, -r3.xyzx
    ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r1.yzw, r1.y, l(0), u1.xxyz
    mul r3.xyz, r2.xxxx, r1.yzwy
    mul r2.xyw, r2.yyyy, r1.yzyw
    mul r1.yzw, r2.zzzz, r1.yyzw
    mov r4.x, r3.x
    mov r4.y, r2.x
    mov r4.z, r1.y
    mov r5.x, r3.y
    mov r5.y, r2.y
    mov r5.z, r1.z
    mov r1.y, r3.z
    mov r1.z, r2.w
  else 
    mov r4.xyz, l(0,0,0,0)
    mov r5.xyz, l(0,0,0,0)
    mov r1.yzw, l(0,0,0,0)
  endif 
  store_structured g3.xyz, r0.w, l(0), r4.xyzx
  mov r2.x, l(32)
  loop 
    uge r2.y, l(0), r2.x
    breakc_nz r2.y
    sync_g_t
    ult r2.y, r0.w, r2.x
    if_nz r2.y
      iadd r2.y, r0.w, r2.x
      ld_structured r3.xyz, r0.w, l(0), g3.xyzx
      ld_structured r2.yzw, r2.y, l(0), g3.xxyz
      add r2.yzw, r2.yyzw, r3.xxyz
      store_structured g3.xyz, r0.w, l(0), r2.yzwy
    endif 
    ushr r2.x, r2.x, l(1)
  endloop 
  sync_g_t
  ld_structured r2.xyz, l(0), l(0), g3.xyzx
  sync_g_t
  store_structured g3.xyz, r0.w, l(0), r5.xyzx
  mov r2.w, l(32)
  loop 
    uge r3.x, l(0), r2.w
    breakc_nz r3.x
    sync_g_t
    ult r3.x, r0.w, r2.w
    if_nz r3.x
      iadd r3.x, r0.w, r2.w
      ld_structured r3.yzw, r0.w, l(0), g3.xxyz
      ld_structured r4.xyz, r3.x, l(0), g3.xyzx
      add r3.xyz, r3.yzwy, r4.xyzx
      store_structured g3.xyz, r0.w, l(0), r3.xyzx
    endif 
    ushr r2.w, r2.w, l(1)
  endloop 
  sync_g_t
  ld_structured r3.xyz, l(0), l(0), g3.xyzx
  sync_g_t
  store_structured g3.xyz, r0.w, l(0), r1.yzwy
  mov r1.y, l(32)
  loop 
    uge r1.z, l(0), r1.y
    breakc_nz r1.z
    sync_g_t
    ult r1.z, r0.w, r1.y
    if_nz r1.z
      iadd r1.z, r0.w, r1.y
      ld_structured r4.xyz, r0.w, l(0), g3.xyzx
      ld_structured r5.xyz, r1.z, l(0), g3.xyzx
      add r4.xyz, r4.xyzx, r5.xyzx
      store_structured g3.xyz, r0.w, l(0), r4.xyzx
    endif 
    ushr r1.y, r1.y, l(1)
  endloop 
  sync_g_t
  ld_structured r1.yzw, l(0), l(0), g3.xxyz
  if_z r0.w
    ld_raw r4.x, l(0), g2.xxxx
    ld_raw r4.y, l(12), g2.xxxx
    ld_raw r4.z, l(24), g2.xxxx
    add r2.xyz, r2.xyzx, r4.xyzx
    store_raw g2.x, l(0), r2.x
    store_raw g2.x, l(12), r2.y
    store_raw g2.x, l(24), r2.z
    ld_raw r2.x, l(4), g2.xxxx
    ld_raw r2.y, l(16), g2.xxxx
    ld_raw r2.z, l(28), g2.xxxx
    add r2.xyz, r3.xyzx, r2.xyzx
    store_raw g2.x, l(4), r2.x
    store_raw g2.x, l(16), r2.y
    store_raw g2.x, l(28), r2.z
    ld_raw r2.x, l(8), g2.xxxx
    ld_raw r2.y, l(20), g2.xxxx
    ld_raw r2.z, l(32), g2.xxxx
    add r1.yzw, r1.yyzw, r2.xxyz
    store_raw g2.x, l(8), r1.y
    store_raw g2.x, l(20), r1.z
    store_raw g2.x, l(32), r1.w
  endif 
  sync_g_t
  iadd r1.x, r1.x, l(1)
endloop 
if_z vThreadIDInGroup.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadGroupID.x, l(0), u3.xyzw
  ld_raw r2.xyz, l(0), g2.xyzx
  ld_raw r3.xyz, l(12), g2.xzyx
  ld_raw r4.xyz, l(24), g2.xyzx
  mov r5.y, l(0)
  mov r6.z, l(0)
  mov r7.z, r4.x
  mov r7.x, r2.x
  mov r7.y, r3.x
  mov r8.z, r4.y
  mov r8.x, r2.y
  mov r8.y, r3.z
  mov r3.z, r4.z
  mov r3.x, r2.z
  mov r2.xyzw, r1.xyzw
  mov r0.w, l(0)
  loop 
    ige r3.w, r0.w, l(4)
    breakc_nz r3.w
    dp2 r3.w, r2.wwww, r2.wwww
    add r3.w, r3.w, l(-1.000000)
    mul r4.xy, r3.wwww, l(0.000000, 1.000000, 0.000000, 0.000000)
    mul r4.zw, r2.zzzy, l(0.000000, 0.000000, 1.000000, -1.000000)
    mul r9.yz, r2.wwww, r4.zzwz
    mov r9.x, r2.w
    mad r4.xyz, r9.xyzx, l(0.000000, 2.000000, 2.000000, 0.000000), r4.yxxy
    mul r9.xyz, r2.xxxx, r2.xyzx
    mad r4.xyz, r9.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r4.xyzx
    mul r9.xy, r2.zxzz, l(-1.000000, 1.000000, 0.000000, 0.000000)
    mul r9.xy, r2.wwww, r9.xyxx
    mul r5.xz, r9.xxyx, l(2.000000, 0.000000, 2.000000, 0.000000)
    mad r5.xzw, r3.wwww, l(0.000000, 0.000000, 1.000000, 0.000000), r5.xxyz
    mul r9.xyz, r2.yyyy, r2.xyzx
    mad r5.xzw, r9.xxyz, l(2.000000, 0.000000, 2.000000, 2.000000), r5.xxzw
    mul r9.xy, r2.yxyy, l(1.000000, -1.000000, 0.000000, 0.000000)
    mul r9.xy, r2.wwww, r9.xyxx
    mul r6.xy, r9.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)
    mad r6.xyw, r3.wwww, l(0.000000, 0.000000, 0.000000, 1.000000), r6.xyxz
    mul r9.xyz, r2.zzzz, r2.xyzx
    mad r6.xyw, r9.xyxz, l(2.000000, 2.000000, 0.000000, 2.000000), r6.xyxw
    mul r9.xyzw, r7.zxxy, r4.xyyz
    mad r9.xyzw, r4.zxxy, r7.xyyz, -r9.xyzw
    mul r10.xyzw, r8.zxxy, r5.xzzw
    mad r10.xyzw, r5.wxxz, r8.xyyz, -r10.xyzw
    add r9.xyzw, r9.xyzw, r10.xyzw
    mul r10.xyzw, r3.zxxy, r6.xyyw
    mad r10.xyzw, r6.wxxy, r3.xyyz, -r10.xyzw
    add r9.xyzw, r9.xyzw, r10.xyzw
    dp3 r3.w, r4.xyzx, r7.xyzx
    dp3 r4.x, r5.xzwx, r8.xyzx
    add r3.w, r3.w, r4.x
    dp3 r4.x, r6.xywx, r3.xyzx
    add r3.w, r3.w, r4.x
    div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), |r3.w|
    add r3.w, r3.w, l(0.00000000)
    mul r4.xyzw, r3.wwww, r9.xyzw
    dp3 r3.w, r4.xzwx, r4.xzwx
    sqrt r3.w, r3.w
    lt r5.x, r3.w, l(0.00000000)
    if_nz r5.x
      break 
    endif 
    div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
    mul r4.xyzw, r4.xyzw, r5.xxxx
    dp3 r5.x, r4.xzwx, r4.xzwx
    rsq r5.x, r5.x
    mul r4.xyzw, r4.xyzw, r5.xxxx
    mul r3.w, r3.w, l(0.500000)
    sincos r5.x, r6.x, r3.w
    mul r4.xyzw, r4.xyzw, r5.xxxx
    mul r5.xzw, r2.wwww, r4.wwxz
    mad r5.xzw, r6.xxxx, r2.xxyz, r5.xxzw
    mad r5.xz, r4.xxzx, r2.zzxz, r5.xxzx
    mad r9.xy, -r4.ywyy, r2.yzyy, r5.xzxx
    mul r3.w, r2.x, r4.w
    mad r4.y, r4.w, r2.y, r5.w
    mad r9.z, -r4.x, r2.x, r4.y
    mad r3.w, r6.x, r2.w, -r3.w
    mad r3.w, -r4.x, r2.y, r3.w
    mad r9.w, -r4.z, r2.z, r3.w
    mul r4.xy, r9.xyxx, r9.xyxx
    add r3.w, r4.y, r4.x
    mad r3.w, r9.z, r9.z, r3.w
    mad r3.w, r9.w, r9.w, r3.w
    lt r4.x, l(0.000000), r3.w
    if_nz r4.x
      sqrt r3.w, r3.w
      div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
      mul r2.xyzw, r3.wwww, r9.xyzw
    else 
      mov r2.xyzw, l(0,0,0,0)
    endif 
    iadd r0.w, r0.w, l(1)
  endloop 
  store_structured u3.xyzw, vThreadGroupID.x, l(0), r2.xyzw
  ld_raw r1.xyz, l(0), g0.xyzx
  store_structured u4.xyz, vThreadGroupID.x, l(0), r1.xyzx
  store_raw g4.xyzw, l(0), r2.xyzw
endif 
sync_g_t
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadGroupID.x, l(0), t2.xxxx
ld_raw r1.xyzw, l(0), g4.xyzw
dp2 r2.x, r1.wwww, r1.wwww
add r2.x, r2.x, l(-1.000000)
ld_raw r2.yzw, l(0), g0.xxyz
mov r3.x, l(0)
loop 
  ige r3.y, r3.x, r0.z
  breakc_nz r3.y
  bfi r3.y, l(26), l(6), r3.x, vThreadIDInGroup.x
  ilt r3.z, r3.y, r0.y
  if_nz r3.z
    iadd r3.y, r0.x, r3.y
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.z, r3.y, l(0), t1.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.z, l(0), t5.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyz, r3.w, l(0), u2.xyzx
    ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r5.xyz, r3.y, l(0), u1.xyzx
    mul r6.xy, r1.zxzz, r5.yzyy
    mad r6.xy, r1.yzyy, r5.zxzz, -r6.xyxx
    mul r4.w, r1.y, r5.x
    mad r6.z, r1.x, r5.y, -r4.w
    mul r6.xyz, r1.wwww, r6.xyzx
    add r6.xyz, r6.xyzx, r6.xyzx
    mad r6.xyz, r5.xyzx, r2.xxxx, r6.xyzx
    dp3 r4.w, r1.xyzx, r5.xyzx
    mul r5.xyz, r1.xyzx, r4.wwww
    mad r5.xyz, r5.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r6.xyzx
    add r5.xyz, r2.yzwy, r5.xyzx
    add r4.xyz, r4.xyzx, -r5.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r5.xyzw, r3.y, l(0), t7.xyzw
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r6.xyz, r3.y, l(0), t7.xyzx
    mul r7.xy, r1.zxzz, r6.yzyy
    mad r7.xy, r1.yzyy, r6.zxzz, -r7.xyxx
    mul r3.y, r1.y, r6.x
    mad r7.z, r1.x, r6.y, -r3.y
    mul r7.xyz, r1.wwww, r7.xyzx
    add r7.xyz, r7.xyzx, r7.xyzx
    mad r7.xyz, r5.xyzx, r2.xxxx, r7.xyzx
    dp3 r3.y, r1.xyzx, r6.xyzx
    mul r6.xyz, r1.xyzx, r3.yyyy
    mad r5.xyz, r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r7.xyzx
    store_structured u5.xyzw, r3.z, l(0), r5.xyzw
    ishl r3.y, r3.w, l(4)
    mul r5.xyz, r0.wwww, -r4.xyzx
    mov r6.x, r5.x
    mov r6.y, l(0)
    loop 
      imm_atomic_cmp_exch r7.y, u0, r3.y, r6.y, r6.x
      ieq r3.z, r6.y, r7.y
      if_nz r3.z
        break 
      endif 
      mad r7.x, -r4.x, r0.w, r7.y
      mov r6.xy, r7.xyxx
    endloop 
    bfi r3.yzw, l(0, 28, 28, 28), l(0, 4, 4, 4), r3.wwww, l(0, 4, 8, 12)
    mov r6.x, r5.y
    mov r6.y, l(0)
    loop 
      imm_atomic_cmp_exch r7.y, u0, r3.y, r6.y, r6.x
      ieq r4.x, r6.y, r7.y
      if_nz r4.x
        break 
      endif 
      mad r7.x, -r4.y, r0.w, r7.y
      mov r6.xy, r7.xyxx
    endloop 
    mov r4.x, r5.z
    mov r4.y, l(0)
    loop 
      imm_atomic_cmp_exch r6.y, u0, r3.z, r4.y, r4.x
      ieq r3.y, r4.y, r6.y
      if_nz r3.y
        break 
      endif 
      mad r6.x, -r4.z, r0.w, r6.y
      mov r4.xy, r6.xyxx
    endloop 
    mov r3.yz, l(0,1.000000,0,0)
    loop 
      imm_atomic_cmp_exch r4.x, u0, r3.w, r3.z, r3.y
      ieq r4.z, r3.z, r4.x
      if_nz r4.z
        break 
      endif 
      add r4.y, r4.x, l(1.000000)
      mov r3.yz, r4.yyxy
    endloop 
  endif 
  iadd r3.x, r3.x, l(1)
endloop 
ret 
// Approximately 383 instruction slots used
