//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// Resource bind info for CalculateInflatableVolume::inflatables
// {
//
//   struct FlexInflatable
//   {
//       
//       int mStartTri;                 // Offset:    0
//       int mNumTris;                  // Offset:    4
//       float mRestVolume;             // Offset:    8
//       float mConstraintScale;        // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateInflatableVolume::positions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateInflatableVolume::reverseLookup
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateInflatableVolume::indices
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateInflatableVolume::lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for g_NvidiaExt
// {
//
//   struct NvShaderExtnStruct
//   {
//       
//       uint opcode;                   // Offset:    0
//       uint rid;                      // Offset:    4
//       uint sid;                      // Offset:    8
//       uint4 dst1u;                   // Offset:   12
//       uint4 padding0[3];             // Offset:   28
//       uint4 src0u;                   // Offset:   76
//       uint4 src1u;                   // Offset:   92
//       uint4 src2u;                   // Offset:  108
//       uint4 dst0u;                   // Offset:  124
//       uint markUavRef;               // Offset:  140
//       float padding1[28];            // Offset:  144
//
//   } $Element;                        // Offset:    0 Size:   256
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CalculateInflatableVolume::inflatables    texture  struct         r/o             t0      1 
// CalculateInflatableVolume::positions    texture  struct         r/o             t1      1 
// CalculateInflatableVolume::reverseLookup    texture  struct         r/o             t2      1 
// CalculateInflatableVolume::indices    texture  struct         r/o             t3      1 
// CalculateInflatableVolume::lambdas        UAV  struct         r/w             u0      1 
// g_NvidiaExt                           UAV  struct     r/w+cnt             u7      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_uav_structured u0, 4
dcl_uav_structured_opc u7, 256
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 34
dcl_tgsm_raw g0, 16
dcl_tgsm_raw g1, 4
dcl_tgsm_raw g2, 12
dcl_tgsm_structured g3, 4, 16
dcl_tgsm_structured g4, 12, 16
dcl_thread_group 512, 1, 1
if_z vThreadIDInGroup.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadGroupID.x, l(0), t0.xyzw
  store_raw g0.xyzw, l(0), r0.xyzw
  store_raw g1.x, l(0), l(0)
  store_raw g2.xyz, l(0), l(0,0,0,0)
endif 
sync_g_t
ld_raw r0.x, l(4), g0.xxxx
iadd r0.y, r0.x, l(511)
ushr r0.y, r0.y, l(9)
itof r0.x, r0.x
mul r0.x, r0.x, l(3.000000)
div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
and r0.z, vThreadIDInGroup.x, l(31)
ishr r0.w, vThreadIDInGroup.x, l(5)
mov r1.yz, l(0,1,31,0)
mov r2.yz, l(0,1,31,0)
mov r3.yz, l(0,1,31,0)
mov r4.yz, l(0,2,31,0)
mov r5.yz, l(0,2,31,0)
mov r6.yz, l(0,2,31,0)
mov r7.yz, l(0,4,31,0)
mov r8.yz, l(0,4,31,0)
mov r9.yz, l(0,4,31,0)
mov r10.yz, l(0,8,31,0)
mov r11.yz, l(0,8,31,0)
mov r12.yz, l(0,8,31,0)
mov r13.yz, l(0,16,31,0)
mov r14.yz, l(0,16,31,0)
mov r15.yz, l(0,16,31,0)
mov r16.w, l(2)
mov r17.w, l(1)
mov r18.w, l(3)
mov r19.w, l(4)
mov r20.w, l(5)
mov r21.w, l(6)
mov r22.w, l(7)
mov r23.w, l(8)
mov r24.w, l(9)
mov r25.w, l(10)
mov r26.w, l(11)
mov r27.w, l(12)
mov r28.w, l(13)
mov r29.w, l(14)
mov r30.w, l(15)
mov r1.w, l(0)
loop 
  ige r2.w, r1.w, r0.y
  breakc_nz r2.w
  bfi r2.w, l(23), l(9), r1.w, vThreadIDInGroup.x
  ld_raw r31.xy, l(0), g0.xyxx
  ld_raw r3.w, l(4), g0.xxxx
  ilt r3.w, r2.w, r3.w
  if_nz r3.w
    iadd r2.w, r2.w, r31.x
    imul null, r3.w, r2.w, l(3)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), t2.xxxx
    imad r31.xz, r2.wwww, l(3, 0, 3, 0), l(1, 0, 2, 0)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r31.x, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.w, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.w, r31.z, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.w, r4.w, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r31.xzw, r3.w, l(0), t1.xxyz
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r32.xyz, r2.w, l(0), t1.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r33.xyz, r4.w, l(0), t1.xyzx
    add r31.xzw, r31.xxzw, r32.xxyz
    add r31.xzw, r33.xxyz, r31.xxzw
    mul r31.xzw, r0.xxxx, r31.xxzw
  else 
    mov r31.xzw, l(0,0,0,0)
  endif 
  imm_atomic_alloc r32.x, u7
  mov r1.x, r31.x
  store_structured u7.xyz, r32.x, l(76), r1.xyzx
  store_structured u7.x, r32.x, l(0), l(3)
  imm_atomic_alloc r32.x, u7
  imm_atomic_alloc r33.x, u7
  mov r2.x, r31.z
  store_structured u7.xyz, r33.x, l(76), r2.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.y, u7
  imm_atomic_alloc r33.x, u7
  mov r3.x, r31.w
  store_structured u7.xyz, r33.x, l(76), r3.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.z, u7
  add r31.xzw, r31.xxzw, r32.xxyz
  imm_atomic_alloc r32.x, u7
  mov r4.x, r31.x
  store_structured u7.xyz, r32.x, l(76), r4.xyzx
  store_structured u7.x, r32.x, l(0), l(3)
  imm_atomic_alloc r32.x, u7
  imm_atomic_alloc r33.x, u7
  mov r5.x, r31.z
  store_structured u7.xyz, r33.x, l(76), r5.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.y, u7
  imm_atomic_alloc r33.x, u7
  mov r6.x, r31.w
  store_structured u7.xyz, r33.x, l(76), r6.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.z, u7
  add r31.xzw, r31.xxzw, r32.xxyz
  imm_atomic_alloc r32.x, u7
  mov r7.x, r31.x
  store_structured u7.xyz, r32.x, l(76), r7.xyzx
  store_structured u7.x, r32.x, l(0), l(3)
  imm_atomic_alloc r32.x, u7
  imm_atomic_alloc r33.x, u7
  mov r8.x, r31.z
  store_structured u7.xyz, r33.x, l(76), r8.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.y, u7
  imm_atomic_alloc r33.x, u7
  mov r9.x, r31.w
  store_structured u7.xyz, r33.x, l(76), r9.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.z, u7
  add r31.xzw, r31.xxzw, r32.xxyz
  imm_atomic_alloc r32.x, u7
  mov r10.x, r31.x
  store_structured u7.xyz, r32.x, l(76), r10.xyzx
  store_structured u7.x, r32.x, l(0), l(3)
  imm_atomic_alloc r32.x, u7
  imm_atomic_alloc r33.x, u7
  mov r11.x, r31.z
  store_structured u7.xyz, r33.x, l(76), r11.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.y, u7
  imm_atomic_alloc r33.x, u7
  mov r12.x, r31.w
  store_structured u7.xyz, r33.x, l(76), r12.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.z, u7
  add r31.xzw, r31.xxzw, r32.xxyz
  imm_atomic_alloc r32.x, u7
  mov r13.x, r31.x
  store_structured u7.xyz, r32.x, l(76), r13.xyzx
  store_structured u7.x, r32.x, l(0), l(3)
  imm_atomic_alloc r32.x, u7
  imm_atomic_alloc r33.x, u7
  mov r14.x, r31.z
  store_structured u7.xyz, r33.x, l(76), r14.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.y, u7
  imm_atomic_alloc r33.x, u7
  mov r15.x, r31.w
  store_structured u7.xyz, r33.x, l(76), r15.xyzx
  store_structured u7.x, r33.x, l(0), l(3)
  imm_atomic_alloc r32.z, u7
  if_z r0.z
    add r31.xzw, r31.xxzw, r32.xxyz
    store_structured g4.xyz, r0.w, l(0), r31.xzwx
  endif 
  sync_g_t
  if_z vThreadIDInGroup.x
    ishl r1.x, r1.w, l(9)
    iadd r1.x, -r1.x, r31.y
    imin r1.x, r1.x, l(512)
    ushr r1.x, r1.x, l(5)
    ld_structured r17.xyz, l(0), l(0), g4.xyzx
    ilt r2.x, l(1), r1.x
    ld_structured r31.xyz, l(1), l(0), g4.xyzx
    add r16.xyz, r17.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r16.xyzw, r17.xyzw
    ilt r2.x, r31.w, r1.x
    ld_structured r16.xyz, l(2), l(0), g4.xyzx
    add r18.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r18.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(3), l(0), g4.xyzx
    add r19.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r19.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(4), l(0), g4.xyzx
    add r20.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r20.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(5), l(0), g4.xyzx
    add r21.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r21.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(6), l(0), g4.xyzx
    add r22.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r22.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(7), l(0), g4.xyzx
    add r23.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r23.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(8), l(0), g4.xyzx
    add r24.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r24.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(9), l(0), g4.xyzx
    add r25.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r25.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(10), l(0), g4.xyzx
    add r26.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r26.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(11), l(0), g4.xyzx
    add r27.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r27.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(12), l(0), g4.xyzx
    add r28.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r28.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(13), l(0), g4.xyzx
    add r29.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r29.xyzw, r31.xyzw
    ilt r2.w, r31.w, r1.x
    and r2.x, r2.w, r2.x
    ld_structured r16.xyz, l(14), l(0), g4.xyzx
    add r30.xyz, r16.xyzx, r31.xyzx
    movc r31.xyzw, r2.xxxx, r30.xyzw, r31.xyzw
    ilt r1.x, r31.w, r1.x
    and r1.x, r1.x, r2.x
    ld_structured r16.xyz, l(15), l(0), g4.xyzx
    add r16.xyz, r16.xyzx, r31.xyzx
    movc r16.xyz, r1.xxxx, r16.xyzx, r31.xyzx
    store_structured g4.xyz, l(0), l(0), r16.xyzx
  endif 
  sync_g_t
  ld_structured r16.xyz, l(0), l(0), g4.xyzx
  if_z vThreadIDInGroup.x
    ld_raw r1.x, l(0), g2.xxxx
    add r1.x, r16.x, r1.x
    store_raw g2.x, l(0), r1.x
    ld_raw r1.x, l(4), g2.xxxx
    add r1.x, r16.y, r1.x
    store_raw g2.x, l(4), r1.x
    ld_raw r1.x, l(8), g2.xxxx
    add r1.x, r16.z, r1.x
    store_raw g2.x, l(8), r1.x
  endif 
  sync_g_t
  iadd r1.w, r1.w, l(1)
endloop 
sync_g_t
mov r1.yz, l(0,1,31,0)
mov r2.yz, l(0,2,31,0)
mov r3.yz, l(0,4,31,0)
mov r4.yz, l(0,8,31,0)
mov r5.yz, l(0,16,31,0)
mov r6.yw, l(0,2,0,1)
mov r7.yw, l(0,3,0,4)
mov r8.yw, l(0,5,0,6)
mov r9.yw, l(0,7,0,8)
mov r10.yw, l(0,9,0,10)
mov r11.yw, l(0,11,0,12)
mov r12.yw, l(0,13,0,14)
mov r13.y, l(15)
mov r0.x, l(0)
loop 
  ige r1.w, r0.x, r0.y
  breakc_nz r1.w
  bfi r1.w, l(23), l(9), r0.x, vThreadIDInGroup.x
  ld_raw r13.zw, l(0), g0.xxxy
  ld_raw r2.w, l(4), g0.xxxx
  ilt r2.w, r1.w, r2.w
  if_nz r2.w
    iadd r1.w, r1.w, r13.z
    imul null, r2.w, r1.w, l(3)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.w, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.w, l(0), t2.xxxx
    imad r14.xy, r1.wwww, l(3, 3, 0, 0), l(1, 2, 0, 0)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r14.x, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r1.w, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r14.y, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r14.xyz, r2.w, l(0), t1.xyzx
    ld_raw r15.xyz, l(0), g2.xyzx
    add r14.xyz, r14.xyzx, -r15.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r16.xyz, r1.w, l(0), t1.xyzx
    add r16.xyzw, -r15.yzzx, r16.yzzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r17.xyz, r3.w, l(0), t1.xyzx
    add r15.xyzw, -r15.zyxz, r17.zyxz
    add r16.xyzw, -r14.yzzx, r16.xyzw
    add r15.xyzw, -r14.zyxz, r15.xyzw
    mul r17.xy, r15.ywyy, r16.ywyy
    mad r17.xy, r16.xzxx, r15.xzxx, -r17.xyxx
    mul r1.w, r15.z, r16.x
    mad r17.z, r16.w, r15.y, -r1.w
    dp3 r1.x, r14.xyzx, r17.xyzx
  else 
    mov r1.x, l(0)
  endif 
  imm_atomic_alloc r14.x, u7
  store_structured u7.xyz, r14.x, l(76), r1.xyzx
  store_structured u7.x, r14.x, l(0), l(3)
  imm_atomic_alloc r14.x, u7
  add r2.x, r1.x, r14.x
  imm_atomic_alloc r14.x, u7
  store_structured u7.xyz, r14.x, l(76), r2.xyzx
  store_structured u7.x, r14.x, l(0), l(3)
  imm_atomic_alloc r14.x, u7
  add r3.x, r2.x, r14.x
  imm_atomic_alloc r14.x, u7
  store_structured u7.xyz, r14.x, l(76), r3.xyzx
  store_structured u7.x, r14.x, l(0), l(3)
  imm_atomic_alloc r14.x, u7
  add r4.x, r3.x, r14.x
  imm_atomic_alloc r14.x, u7
  store_structured u7.xyz, r14.x, l(76), r4.xyzx
  store_structured u7.x, r14.x, l(0), l(3)
  imm_atomic_alloc r14.x, u7
  add r5.x, r4.x, r14.x
  imm_atomic_alloc r14.x, u7
  store_structured u7.xyz, r14.x, l(76), r5.xyzx
  store_structured u7.x, r14.x, l(0), l(3)
  imm_atomic_alloc r14.x, u7
  if_z r0.z
    add r1.x, r5.x, r14.x
    store_structured g3.x, r0.w, l(0), r1.x
  endif 
  sync_g_t
  if_z vThreadIDInGroup.x
    ishl r1.x, r0.x, l(9)
    iadd r1.x, -r1.x, r13.w
    imin r1.x, r1.x, l(512)
    ushr r1.x, r1.x, l(5)
    ld_structured r6.z, l(0), l(0), g3.xxxx
    ilt r1.w, l(1), r1.x
    ld_structured r2.x, l(1), l(0), g3.xxxx
    add r6.x, r2.x, r6.z
    movc r2.xw, r1.wwww, r6.xxxy, r6.zzzw
    ilt r1.w, r2.w, r1.x
    ld_structured r3.x, l(2), l(0), g3.xxxx
    add r7.x, r2.x, r3.x
    movc r2.xw, r1.wwww, r7.xxxy, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(3), l(0), g3.xxxx
    add r7.z, r2.x, r3.x
    movc r2.xw, r1.wwww, r7.zzzw, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(4), l(0), g3.xxxx
    add r8.x, r2.x, r3.x
    movc r2.xw, r1.wwww, r8.xxxy, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(5), l(0), g3.xxxx
    add r8.z, r2.x, r3.x
    movc r2.xw, r1.wwww, r8.zzzw, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(6), l(0), g3.xxxx
    add r9.x, r2.x, r3.x
    movc r2.xw, r1.wwww, r9.xxxy, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(7), l(0), g3.xxxx
    add r9.z, r2.x, r3.x
    movc r2.xw, r1.wwww, r9.zzzw, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(8), l(0), g3.xxxx
    add r10.x, r2.x, r3.x
    movc r2.xw, r1.wwww, r10.xxxy, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(9), l(0), g3.xxxx
    add r10.z, r2.x, r3.x
    movc r2.xw, r1.wwww, r10.zzzw, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(10), l(0), g3.xxxx
    add r11.x, r2.x, r3.x
    movc r2.xw, r1.wwww, r11.xxxy, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(11), l(0), g3.xxxx
    add r11.z, r2.x, r3.x
    movc r2.xw, r1.wwww, r11.zzzw, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(12), l(0), g3.xxxx
    add r12.x, r2.x, r3.x
    movc r2.xw, r1.wwww, r12.xxxy, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(13), l(0), g3.xxxx
    add r12.z, r2.x, r3.x
    movc r2.xw, r1.wwww, r12.zzzw, r2.xxxw
    ilt r3.x, r2.w, r1.x
    and r1.w, r1.w, r3.x
    ld_structured r3.x, l(14), l(0), g3.xxxx
    add r13.x, r2.x, r3.x
    movc r2.xw, r1.wwww, r13.xxxy, r2.xxxw
    ilt r1.x, r2.w, r1.x
    and r1.x, r1.x, r1.w
    ld_structured r1.w, l(15), l(0), g3.xxxx
    add r1.w, r1.w, r2.x
    movc r1.x, r1.x, r1.w, r2.x
    store_structured g3.x, l(0), l(0), r1.x
  endif 
  sync_g_t
  ld_structured r1.x, l(0), l(0), g3.xxxx
  if_z vThreadIDInGroup.x
    ld_raw r1.w, l(0), g1.xxxx
    add r1.x, r1.x, r1.w
    store_raw g1.x, l(0), r1.x
  endif 
  sync_g_t
  iadd r0.x, r0.x, l(1)
endloop 
if_z vThreadIDInGroup.x
  ld_raw r0.xy, l(8), g0.xyxx
  mul r0.x, r0.x, l(0.010000)
  ld_raw r0.z, l(8), g0.xxxx
  ld_raw r0.w, l(0), g1.xxxx
  max r0.x, |r0.x|, |r0.w|
  div r0.x, |r0.z|, r0.x
  mul r1.x, r0.x, r0.x
  mul r0.x, r0.x, r1.x
  add r0.z, -r0.z, r0.w
  mul r0.y, r0.y, r0.z
  mul r0.x, r0.x, r0.y
  store_structured u0.x, vThreadGroupID.x, l(0), r0.x
endif 
ret 
// Approximately 437 instruction slots used
