//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for SolveInflatableVolume::inflatables
// {
//
//   struct FlexInflatable
//   {
//       
//       int mStartTri;                 // Offset:    0
//       int mNumTris;                  // Offset:    4
//       float mRestVolume;             // Offset:    8
//       float mConstraintScale;        // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveInflatableVolume::positions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveInflatableVolume::reverseLookup
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveInflatableVolume::indices
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveInflatableVolume::lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for g_NvidiaExt
// {
//
//   struct NvShaderExtnStruct
//   {
//       
//       uint opcode;                   // Offset:    0
//       uint rid;                      // Offset:    4
//       uint sid;                      // Offset:    8
//       uint4 dst1u;                   // Offset:   12
//       uint4 padding0[3];             // Offset:   28
//       uint4 src0u;                   // Offset:   76
//       uint4 src1u;                   // Offset:   92
//       uint4 src2u;                   // Offset:  108
//       uint4 dst0u;                   // Offset:  124
//       uint markUavRef;               // Offset:  140
//       float padding1[28];            // Offset:  144
//
//   } $Element;                        // Offset:    0 Size:   256
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SolveInflatableVolume::inflatables    texture  struct         r/o             t0      1 
// SolveInflatableVolume::positions    texture  struct         r/o             t1      1 
// SolveInflatableVolume::reverseLookup    texture  struct         r/o             t2      1 
// SolveInflatableVolume::indices    texture  struct         r/o             t3      1 
// SolveInflatableVolume::lambdas    texture  struct         r/o             t4      1 
// InterlockedFloat::accum               UAV    byte         r/w             u0      1 
// g_NvidiaExt                           UAV  struct     r/w+cnt             u7      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[25], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_resource_structured t4, 4
dcl_uav_raw u0
dcl_uav_structured_opc u7, 256
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 6
dcl_tgsm_raw g0, 16
dcl_thread_group 512, 1, 1
mul r0.x, cb0[23].z, cb0[24].y
if_z vThreadIDInGroup.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.yz, vThreadGroupID.x, l(0), t0.xxyx
  store_raw g0.xy, l(0), r0.yzyy
endif 
sync_g_t
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.y, vThreadGroupID.x, l(0), t4.xxxx
ld_raw r0.zw, l(0), g0.xxxy
mul r1.x, r0.x, r0.x
mov r1.y, vThreadIDInGroup.x
loop 
  ige r1.z, r1.y, r0.w
  breakc_nz r1.z
  iadd r1.z, r0.z, r1.y
  imul null, r1.w, r1.z, l(3)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r1.w, l(0), t3.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r1.w, l(0), t2.xxxx
  imad r2.xy, r1.zzzz, l(3, 3, 0, 0), l(1, 2, 0, 0)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.z, r2.x, l(0), t3.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.z, r1.z, l(0), t2.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.x, r2.y, l(0), t3.xxxx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.x, r2.x, l(0), t2.xxxx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.yzw, r1.w, l(0), t1.xxyz
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyz, r1.z, l(0), t1.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyz, r2.x, l(0), t1.xyzx
  add r3.xyzw, -r2.zwwy, r3.yzzx
  add r4.xyzw, -r2.wzyw, r4.zyxz
  mul r2.yz, r3.yywy, r4.yywy
  mad r5.xy, r3.xzxx, r4.xzxx, -r2.yzyy
  mul r2.y, r3.x, r4.z
  mad r5.z, r3.w, r4.y, -r2.y
  mul r2.yzw, -r0.yyyy, r5.xxyz
  dp3 r3.x, r2.yzwy, r2.yzwy
  rsq r3.y, r3.x
  lt r3.x, r1.x, r3.x
  mul r3.y, r0.x, r3.y
  mul r3.yzw, r2.yyzw, r3.yyyy
  movc r2.yzw, r3.xxxx, r3.yyzw, r2.yyzw
  ishl r3.x, r1.w, l(4)
  imm_atomic_alloc r4.x, u7
  store_structured u7.x, r4.x, l(140), l(1)
  store_raw u0.x, r4.x, l(0)
  imm_atomic_alloc r4.x, u7
  store_structured u7.x, r4.x, l(76), r3.x
  store_structured u7.x, r4.x, l(92), r2.y
  store_structured u7.x, r4.x, l(108), l(3)
  store_structured u7.x, r4.x, l(0), l(13)
  bfi r3.xy, l(28, 28, 0, 0), l(4, 4, 0, 0), r1.wwww, l(4, 8, 0, 0)
  imm_atomic_alloc r4.x, u7
  store_structured u7.x, r4.x, l(140), l(1)
  store_raw u0.x, r4.x, l(0)
  imm_atomic_alloc r4.x, u7
  store_structured u7.x, r4.x, l(76), r3.x
  store_structured u7.x, r4.x, l(92), r2.z
  store_structured u7.x, r4.x, l(108), l(3)
  store_structured u7.x, r4.x, l(0), l(13)
  imm_atomic_alloc r4.x, u7
  store_structured u7.x, r4.x, l(140), l(1)
  store_raw u0.x, r4.x, l(0)
  imm_atomic_alloc r4.x, u7
  store_structured u7.x, r4.x, l(76), r3.y
  store_structured u7.x, r4.x, l(92), r2.w
  store_structured u7.x, r4.x, l(108), l(3)
  store_structured u7.x, r4.x, l(0), l(13)
  ishl r1.w, r1.z, l(4)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(140), l(1)
  store_raw u0.x, r3.x, l(0)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(76), r1.w
  store_structured u7.x, r3.x, l(92), r2.y
  store_structured u7.x, r3.x, l(108), l(3)
  store_structured u7.x, r3.x, l(0), l(13)
  bfi r1.zw, l(0, 0, 28, 28), l(0, 0, 4, 4), r1.zzzz, l(0, 0, 4, 8)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(140), l(1)
  store_raw u0.x, r3.x, l(0)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(76), r1.z
  store_structured u7.x, r3.x, l(92), r2.z
  store_structured u7.x, r3.x, l(108), l(3)
  store_structured u7.x, r3.x, l(0), l(13)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(140), l(1)
  store_raw u0.x, r3.x, l(0)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(76), r1.w
  store_structured u7.x, r3.x, l(92), r2.w
  store_structured u7.x, r3.x, l(108), l(3)
  store_structured u7.x, r3.x, l(0), l(13)
  ishl r1.z, r2.x, l(4)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(140), l(1)
  store_raw u0.x, r3.x, l(0)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(76), r1.z
  store_structured u7.x, r3.x, l(92), r2.y
  store_structured u7.x, r3.x, l(108), l(3)
  store_structured u7.x, r3.x, l(0), l(13)
  bfi r1.zw, l(0, 0, 28, 28), l(0, 0, 4, 4), r2.xxxx, l(0, 0, 4, 8)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(140), l(1)
  store_raw u0.x, r3.x, l(0)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(76), r1.z
  store_structured u7.x, r3.x, l(92), r2.z
  store_structured u7.x, r3.x, l(108), l(3)
  store_structured u7.x, r3.x, l(0), l(13)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(140), l(1)
  store_raw u0.x, r3.x, l(0)
  imm_atomic_alloc r3.x, u7
  store_structured u7.x, r3.x, l(76), r1.w
  store_structured u7.x, r3.x, l(92), r2.w
  store_structured u7.x, r3.x, l(108), l(3)
  store_structured u7.x, r3.x, l(0), l(13)
  iadd r1.y, r1.y, l(512)
endloop 
ret 
// Approximately 119 instruction slots used
