//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for SmoothPositions::contacts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SmoothPositions::contactCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SmoothPositions::phases
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SmoothPositions::sortedNewPositionsTex
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SmoothPositions::smoothPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SmoothPositions::smoothPositionsOriginal
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SmoothPositions::contacts         texture  struct         r/o             t0      1 
// SmoothPositions::contactCounts    texture  struct         r/o             t1      1 
// SmoothPositions::phases           texture  struct         r/o             t2      1 
// SmoothPositions::sortedNewPositionsTex    texture  struct         r/o             t3      1 
// SmoothPositions::indices          texture    uint         buf             t4      1 
// SmoothPositions::smoothPositions        UAV  struct         r/w             u0      1 
// SmoothPositions::smoothPositionsOriginal        UAV  struct         r/w             u1      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 4
dcl_resource_structured t2, 4
dcl_resource_structured t3, 16
dcl_resource_buffer (uint,uint,uint,uint) t4
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_input vThreadID.x
dcl_temps 6
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[23].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), t3.xyzw
  ld_indexable(buffer)(uint,uint,uint,uint) r1.x, vThreadID.xxxx, t4.xyzw
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, vThreadID.x, l(0), t2.xxxx
  and r1.y, r1.y, l(0x00400000)
  if_nz r1.y
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, vThreadID.x, l(0), t1.xxxx
    mov r1.z, vThreadID.x
    mov r2.xyzw, l(0,0,0,0)
    mov r1.w, l(0)
    loop 
      ige r3.x, r1.w, r1.y
      breakc_nz r3.x
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.x, r1.z, l(0), t0.xxxx
      iadd r1.z, r1.z, cb0[23].y
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyz, r3.x, l(0), t3.xyzx
      add r4.xyz, r0.xyzx, -r3.xyzx
      dp3 r3.w, r4.xyzx, r4.xyzx
      lt r4.x, r3.w, cb0[8].z
      lt r4.y, l(0.000000), r3.w
      and r4.x, r4.y, r4.x
      sqrt r3.w, r3.w
      mul r3.w, r3.w, cb0[8].w
      mul r4.y, r3.w, r3.w
      mad r3.w, -r4.y, r3.w, l(1.000000)
      mad r5.yzw, r3.xxyz, r3.wwww, r2.yyzw
      add r5.x, r2.x, r3.w
      movc r2.xyzw, r4.xxxx, r5.xyzw, r2.xyzw
      iadd r1.w, r1.w, l(1)
    endloop 
    mul r1.y, cb0[8].w, cb0[8].y
    mul r1.y, r1.y, l(0.500000)
    mul r1.z, r1.y, r1.y
    mad r1.y, -r1.z, r1.y, l(1.000000)
    mul r1.y, r1.y, l(4.000000)
    div r1.y, r2.x, r1.y
    min r3.w, r1.y, l(1.000000)
    lt r1.y, l(0.000000), r2.x
    div r3.xyz, r2.yzwy, r2.xxxx
    mov r2.x, l(0)
    movc r2.xyzw, r1.yyyy, r3.xyzw, r2.yzwx
    mul r1.y, r2.w, cb0[14].x
    add r2.xyz, -r0.xyzx, r2.xyzx
    mad r0.xyz, r2.xyzx, r1.yyyy, r0.xyzx
    mov r2.xyz, r0.xyzx
  else 
    mov r2.xyz, r0.xyzx
  endif 
  store_structured u1.xyzw, r1.x, l(0), r0.xyzw
  mov r2.w, r0.w
  store_structured u0.xyzw, vThreadID.x, l(0), r2.xyzw
endif 
ret 
// Approximately 54 instruction slots used
