//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer ComputeTriangleBounds::mConstTriMeshInfo
// {
//
//   int ComputeTriangleBounds::numTris;// Offset:    0 Size:     4
//
// }
//
// Resource bind info for ComputeTriangleBounds::verticesArray
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTriangleBounds::indicesArray
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for ComputeTriangleBounds::lowers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for ComputeTriangleBounds::uppers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ComputeTriangleBounds::verticesArray    texture  struct         r/o             t0      1 
// ComputeTriangleBounds::indicesArray    texture  struct         r/o             t1      1 
// ComputeTriangleBounds::lowers         UAV  struct         r/w             u0      1 
// ComputeTriangleBounds::uppers         UAV  struct         r/w             u1      1 
// ComputeTriangleBounds::mConstTriMeshInfo    cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 4
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_input vThreadID.x
dcl_temps 4
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
if_nz r0.x
  imul null, r0.x, vThreadID.x, l(3)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), t1.xxxx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyz, r0.x, l(0), t0.xyzx
  imad r1.xy, vThreadID.xxxx, l(3, 3, 0, 0), l(1, 2, 0, 0)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r1.x, l(0), t1.xxxx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xzw, r0.w, l(0), t0.xxyz
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r1.y, l(0), t1.xxxx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, r0.w, l(0), t0.xyzx
  min r3.xyz, r1.xzwx, r2.xyzx
  min r3.xyz, r0.xyzx, r3.xyzx
  max r1.xyz, r1.xzwx, r2.xyzx
  max r0.xyz, r0.xyzx, r1.xyzx
  mov r3.w, l(0)
  store_structured u0.xyzw, vThreadID.x, l(0), r3.xyzw
  mov r0.w, l(0)
  store_structured u1.xyzw, vThreadID.x, l(0), r0.xyzw
endif 
ret 
// Approximately 20 instruction slots used
