//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer TransformShapeBounds::consts
// {
//
//   int TransformShapeBounds::gNumBounds;// Offset:    0 Size:     4
//
// }
//
// Resource bind info for TransformShapeBounds::positions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for TransformShapeBounds::rotations
// {
//
//   struct DxQuat
//   {
//       
//       float3 xyz;                    // Offset:    0
//       float w;                       // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for TransformShapeBounds::positionsPrev
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for TransformShapeBounds::rotationsPrev
// {
//
//   struct DxQuat
//   {
//       
//       float3 xyz;                    // Offset:    0
//       float w;                       // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for TransformShapeBounds::flags
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for TransformShapeBounds::geometry
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for TransformShapeBounds::convexMeshes
// {
//
//   struct FlexConvexMeshDevice
//   {
//       
//       float4 mLower;                 // Offset:    0
//       float4 mUpper;                 // Offset:   16
//       int mPlaneOffset;              // Offset:   32
//       int mPlaneCount;               // Offset:   36
//       int mPad[2];                   // Offset:   40
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for TransformShapeBounds::triangleMeshes
// {
//
//   struct FlexTriangleMeshDevice
//   {
//       
//       float4 mLower;                 // Offset:    0
//       float4 mUpper;                 // Offset:   16
//       int mIndexStart;               // Offset:   32
//       int mVertexStart;              // Offset:   36
//       int mNodeStart;                // Offset:   40
//       int mPad;                      // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for TransformShapeBounds::lowers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for TransformShapeBounds::uppers
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TransformShapeBounds::positions    texture  struct         r/o             t0      1 
// TransformShapeBounds::rotations    texture  struct         r/o             t1      1 
// TransformShapeBounds::positionsPrev    texture  struct         r/o             t2      1 
// TransformShapeBounds::rotationsPrev    texture  struct         r/o             t3      1 
// TransformShapeBounds::flags       texture  struct         r/o             t4      1 
// TransformShapeBounds::geometry    texture  struct         r/o             t5      1 
// TransformShapeBounds::convexMeshes    texture  struct         r/o             t6      1 
// TransformShapeBounds::triangleMeshes    texture  struct         r/o             t7      1 
// TransformShapeBounds::lowers          UAV  struct         r/w             u0      1 
// TransformShapeBounds::uppers          UAV  struct         r/w             u1      1 
// TransformShapeBounds::consts      cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 16
dcl_resource_structured t3, 16
dcl_resource_structured t4, 4
dcl_resource_structured t5, 16
dcl_resource_structured t6, 48
dcl_resource_structured t7, 48
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_input vThreadID.x
dcl_temps 9
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[0].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, vThreadID.x, l(0), t4.xxxx
  and r0.x, r0.x, l(7)
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadID.x, l(0), t5.yzxw
  switch r0.x
    case l(0)
    mov r0.xyz, -r1.zzzz
    mov r1.xyz, r1.zzzz
    break 
    case l(1)
    mov r1.y, l(0)
    add r0.xyz, -r1.zzzz, -r1.xyyx
    add r1.xyz, r1.zzzz, r1.yyxy
    break 
    case l(2)
    mov r0.xyz, -r1.zxyz
    break 
    case l(3)
    iadd r0.w, r1.w, l(-1)
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.xyz, r0.w, l(0), t6.xyzx
    mul r0.xyz, r1.zxyz, r2.xyzx
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.xyz, r0.w, l(16), t6.xyzx
    mul r1.xyz, r1.xyzx, r2.yzxy
    break 
    case l(4)
    iadd r0.w, r1.w, l(-1)
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.xyz, r0.w, l(0), t7.xyzx
    mul r0.xyz, r1.zxyz, r2.xyzx
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.xyz, r0.w, l(16), t7.xyzx
    mul r1.xyz, r1.xyzx, r2.yzxy
    break 
    case l(5)
    mov r0.xyz, l(0,0,0,0)
    mov r1.xyz, r1.zzzz
    break 
    default 
    break 
  endswitch 
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyzw, vThreadID.x, l(0), t1.xyzw
  dp2 r0.w, r2.wwww, r2.wwww
  add r0.w, r0.w, l(-1.000000)
  mul r3.xy, r0.wwww, l(0.000000, 1.000000, 0.000000, 0.000000)
  mul r3.zw, r2.zzzy, l(0.000000, 0.000000, 1.000000, -1.000000)
  mul r4.yz, r2.wwww, r3.zzwz
  mov r4.x, r2.w
  mad r3.xyz, r4.xyzx, l(0.000000, 2.000000, 2.000000, 0.000000), r3.yxxy
  mul r4.xyz, r2.xxxx, r2.xyzx
  mad r3.xyz, r4.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r3.xyzx
  mul r4.xy, r2.zxzz, l(-1.000000, 1.000000, 0.000000, 0.000000)
  mul r4.xy, r2.wwww, r4.xyxx
  mul r4.xz, r4.xxyx, l(2.000000, 0.000000, 2.000000, 0.000000)
  mov r4.y, l(0)
  mad r4.xyz, r0.wwww, l(0.000000, 1.000000, 0.000000, 0.000000), r4.xyzx
  mul r5.xyz, r2.yyyy, r2.xyzx
  mad r4.xyz, r5.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r4.xyzx
  mul r5.xy, r2.yxyy, l(1.000000, -1.000000, 0.000000, 0.000000)
  mul r5.xy, r2.wwww, r5.xyxx
  mul r5.xy, r5.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)
  mov r5.z, l(0)
  mad r5.xyz, r0.wwww, l(0.000000, 0.000000, 1.000000, 0.000000), r5.xyzx
  mul r6.xyz, r2.zzzz, r2.xyzx
  mad r5.xyz, r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r5.xyzx
  add r6.xyz, -r0.xyzx, r1.zxyz
  mul r3.xyz, r3.xyzx, r6.xxxx
  mul r4.xyz, r4.xyzx, r6.yyyy
  mul r5.xyz, r5.xyzx, r6.zzzz
  add r3.xyz, |r3.xyzx|, |r4.xyzx|
  add r3.xyz, |r5.xyzx|, r3.xyzx
  add r0.xyz, r0.xyzx, r1.zxyz
  mul r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  mul r1.xyw, r0.yzyx, r2.zxzy
  mad r1.xy, r2.yzyy, r0.zxzz, -r1.xyxx
  mad r1.z, r2.x, r0.y, -r1.w
  mul r1.xyz, r2.wwww, r1.xyzx
  add r1.xyz, r1.xyzx, r1.xyzx
  mad r1.xyz, r0.xyzx, r0.wwww, r1.xyzx
  dp3 r0.w, r2.xyzx, r0.xyzx
  mul r2.xyz, r0.wwww, r2.xyzx
  mad r1.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r1.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, vThreadID.x, l(0), t0.xyzx
  add r1.xyz, r1.xyzx, r2.xyzx
  mad r2.xyz, -r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx
  mad r1.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyzw, vThreadID.x, l(0), t3.xyzw
  dp2 r0.w, r3.wwww, r3.wwww
  add r0.w, r0.w, l(-1.000000)
  mul r4.xy, r0.wwww, l(0.000000, 1.000000, 0.000000, 0.000000)
  mul r4.zw, r3.zzzy, l(0.000000, 0.000000, 1.000000, -1.000000)
  mul r5.yz, r3.wwww, r4.zzwz
  mov r5.x, r3.w
  mad r4.xyz, r5.xyzx, l(0.000000, 2.000000, 2.000000, 0.000000), r4.yxxy
  mul r5.xyz, r3.xxxx, r3.xyzx
  mad r4.xyz, r5.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r4.xyzx
  mul r5.xy, r3.zxzz, l(-1.000000, 1.000000, 0.000000, 0.000000)
  mul r5.xy, r3.wwww, r5.xyxx
  mul r5.xz, r5.xxyx, l(2.000000, 0.000000, 2.000000, 0.000000)
  mov r5.y, l(0)
  mad r5.xyz, r0.wwww, l(0.000000, 1.000000, 0.000000, 0.000000), r5.xyzx
  mul r7.xyz, r3.yyyy, r3.xyzx
  mad r5.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r5.xyzx
  mul r7.xy, r3.yxyy, l(1.000000, -1.000000, 0.000000, 0.000000)
  mul r7.xy, r3.wwww, r7.xyxx
  mul r7.xy, r7.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)
  mov r7.z, l(0)
  mad r7.xyz, r0.wwww, l(0.000000, 0.000000, 1.000000, 0.000000), r7.xyzx
  mul r8.xyz, r3.zzzz, r3.xyzx
  mad r7.xyz, r8.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r7.xyzx
  mul r4.xyz, r6.xxxx, r4.xyzx
  mul r5.xyz, r6.yyyy, r5.xyzx
  mul r6.xyz, r6.zzzz, r7.xyzx
  add r4.xyz, |r4.xyzx|, |r5.xyzx|
  add r4.xyz, |r6.xyzx|, r4.xyzx
  mul r5.xy, r0.yzyy, r3.zxzz
  mad r5.xy, r3.yzyy, r0.zxzz, -r5.xyxx
  mul r1.w, r0.x, r3.y
  mad r5.z, r3.x, r0.y, -r1.w
  mul r5.xyz, r3.wwww, r5.xyzx
  add r5.xyz, r5.xyzx, r5.xyzx
  mad r5.xyz, r0.xyzx, r0.wwww, r5.xyzx
  dp3 r0.x, r3.xyzx, r0.xyzx
  mul r0.xyz, r0.xxxx, r3.xyzx
  mad r0.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r5.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyz, vThreadID.x, l(0), t2.xyzx
  add r0.xyz, r0.xyzx, r3.xyzx
  mad r3.xyz, -r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r0.xyzx
  mad r0.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r0.xyzx
  min r2.xyz, r2.xyzx, r3.xyzx
  mov r2.w, l(0)
  store_structured u0.xyzw, vThreadID.x, l(0), r2.xyzw
  max r0.xyz, r0.xyzx, r1.xyzx
  mov r0.w, l(0)
  store_structured u1.xyzw, vThreadID.x, l(0), r0.xyzw
endif 
ret 
// Approximately 135 instruction slots used
