//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// Resource bind info for CompactDiffuseParticles::numDiffuseParticles
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CompactDiffuseParticles::diffusePositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CompactDiffuseParticles::diffuseVelocities
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CompactDiffuseParticles::numDiffuseParticlesNew
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CompactDiffuseParticles::diffusePositionsNew
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CompactDiffuseParticles::diffuseVelocitiesNew
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CompactDiffuseParticles::numDiffuseParticles    texture  struct         r/o             t0      1 
// CompactDiffuseParticles::diffusePositions    texture  struct         r/o             t1      1 
// CompactDiffuseParticles::diffuseVelocities    texture  struct         r/o             t2      1 
// CompactDiffuseParticles::numDiffuseParticlesNew        UAV  struct         r/w             u0      1 
// CompactDiffuseParticles::diffusePositionsNew        UAV  struct         r/w             u1      1 
// CompactDiffuseParticles::diffuseVelocitiesNew        UAV  struct         r/w             u2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 16
dcl_resource_structured t2, 16
dcl_uav_structured u0, 4
dcl_uav_structured u1, 16
dcl_uav_structured u2, 16
dcl_input vThreadID.x
dcl_temps 2
dcl_thread_group 256, 1, 1
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, l(0), l(0), t0.xxxx
ilt r0.x, vThreadID.x, r0.x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.x, vThreadID.x, l(12), t1.xxxx
  lt r0.x, l(0.000000), r0.x
  if_nz r0.x
    imm_atomic_iadd r0.x, u0, l(0, 0, 0, 0), l(1)
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadID.x, l(0), t1.xyzw
    store_structured u1.xyzw, r0.x, l(0), r1.xyzw
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadID.x, l(0), t2.xyzw
    store_structured u2.xyzw, r0.x, l(0), r1.xyzw
  endif 
endif 
ret 
// Approximately 14 instruction slots used
