//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// Resource bind info for CalculateInflatableVolume::inflatables
// {
//
//   struct FlexInflatable
//   {
//       
//       int mStartTri;                 // Offset:    0
//       int mNumTris;                  // Offset:    4
//       float mRestVolume;             // Offset:    8
//       float mConstraintScale;        // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateInflatableVolume::positions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateInflatableVolume::reverseLookup
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateInflatableVolume::indices
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateInflatableVolume::lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CalculateInflatableVolume::inflatables    texture  struct         r/o             t0      1 
// CalculateInflatableVolume::positions    texture  struct         r/o             t1      1 
// CalculateInflatableVolume::reverseLookup    texture  struct         r/o             t2      1 
// CalculateInflatableVolume::indices    texture  struct         r/o             t3      1 
// CalculateInflatableVolume::lambdas        UAV  struct         r/w             u0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_uav_structured u0, 4
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 5
dcl_tgsm_raw g0, 16
dcl_tgsm_raw g1, 4
dcl_tgsm_raw g2, 12
dcl_tgsm_structured g3, 4, 512
dcl_tgsm_structured g4, 12, 512
dcl_thread_group 512, 1, 1
if_z vThreadIDInGroup.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadGroupID.x, l(0), t0.xyzw
  store_raw g0.xyzw, l(0), r0.xyzw
  store_raw g1.x, l(0), l(0)
  store_raw g2.xyz, l(0), l(0,0,0,0)
endif 
sync_g_t
ld_raw r0.x, l(4), g0.xxxx
iadd r0.y, r0.x, l(511)
ushr r0.y, r0.y, l(9)
itof r0.x, r0.x
mul r0.x, r0.x, l(3.000000)
div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
mov r0.z, l(0)
loop 
  ige r0.w, r0.z, r0.y
  breakc_nz r0.w
  bfi r0.w, l(23), l(9), r0.z, vThreadIDInGroup.x
  ld_raw r1.xy, l(0), g0.xyxx
  ishl r1.z, r0.z, l(9)
  iadd r1.y, -r1.z, r1.y
  imin r1.y, r1.y, l(512)
  ld_raw r1.z, l(4), g0.xxxx
  ilt r1.z, r0.w, r1.z
  if_nz r1.z
    iadd r0.w, r0.w, r1.x
    imul null, r1.x, r0.w, l(3)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.x, r1.x, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.x, r1.x, l(0), t2.xxxx
    imad r1.zw, r0.wwww, l(0, 0, 3, 3), l(0, 0, 1, 2)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r1.z, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r0.w, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.z, r1.w, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.z, r1.z, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, r1.x, l(0), t1.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyz, r0.w, l(0), t1.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xzw, r1.z, l(0), t1.xxyz
    add r2.xyz, r2.xyzx, r3.xyzx
    add r1.xzw, r1.xxzw, r2.xxyz
    mul r1.xzw, r0.xxxx, r1.xxzw
  else 
    mov r1.xzw, l(0,0,0,0)
  endif 
  store_structured g4.xyz, vThreadIDInGroup.x, l(0), r1.xzwx
  ushr r0.w, r1.y, l(1)
  mov r1.x, r0.w
  loop 
    uge r1.y, l(0), r1.x
    breakc_nz r1.y
    sync_g_t
    ult r1.y, vThreadIDInGroup.x, r1.x
    if_nz r1.y
      iadd r1.y, r1.x, vThreadIDInGroup.x
      ld_structured r2.xyz, vThreadIDInGroup.x, l(0), g4.xyzx
      ld_structured r1.yzw, r1.y, l(0), g4.xxyz
      add r1.yzw, r1.yyzw, r2.xxyz
      store_structured g4.xyz, vThreadIDInGroup.x, l(0), r1.yzwy
    endif 
    ushr r1.x, r1.x, l(1)
  endloop 
  sync_g_t
  ld_structured r1.xyz, l(0), l(0), g4.xyzx
  if_z vThreadIDInGroup.x
    ld_raw r0.w, l(0), g2.xxxx
    add r0.w, r1.x, r0.w
    store_raw g2.x, l(0), r0.w
    ld_raw r0.w, l(4), g2.xxxx
    add r0.w, r1.y, r0.w
    store_raw g2.x, l(4), r0.w
    ld_raw r0.w, l(8), g2.xxxx
    add r0.w, r1.z, r0.w
    store_raw g2.x, l(8), r0.w
  endif 
  sync_g_t
  iadd r0.z, r0.z, l(1)
endloop 
sync_g_t
mov r0.x, l(0)
loop 
  ige r0.z, r0.x, r0.y
  breakc_nz r0.z
  bfi r0.z, l(23), l(9), r0.x, vThreadIDInGroup.x
  ld_raw r1.xy, l(0), g0.xyxx
  ishl r0.w, r0.x, l(9)
  iadd r0.w, -r0.w, r1.y
  imin r0.w, r0.w, l(512)
  ld_raw r1.y, l(4), g0.xxxx
  ilt r1.y, r0.z, r1.y
  if_nz r1.y
    iadd r0.z, r0.z, r1.x
    imul null, r1.x, r0.z, l(3)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.x, r1.x, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.x, r1.x, l(0), t2.xxxx
    imad r1.yz, r0.zzzz, l(0, 3, 3, 0), l(0, 1, 2, 0)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.z, r1.y, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.z, r0.z, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, r1.z, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, r1.y, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xzw, r1.x, l(0), t1.xxyz
    ld_raw r2.xyz, l(0), g2.xyzx
    add r1.xzw, r1.xxzw, -r2.xxyz
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyz, r0.z, l(0), t1.xyzx
    add r3.xyzw, -r2.yzzx, r3.yzzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r4.xyz, r1.y, l(0), t1.xyzx
    add r2.xyzw, -r2.zyxz, r4.zyxz
    add r3.xyzw, -r1.zwwx, r3.xyzw
    add r2.xyzw, -r1.wzxw, r2.xyzw
    mul r4.xy, r2.ywyy, r3.ywyy
    mad r4.xy, r3.xzxx, r2.xzxx, -r4.xyxx
    mul r0.z, r2.z, r3.x
    mad r4.z, r3.w, r2.y, -r0.z
    dp3 r0.z, r1.xzwx, r4.xyzx
  else 
    mov r0.z, l(0)
  endif 
  store_structured g3.x, vThreadIDInGroup.x, l(0), r0.z
  ushr r0.z, r0.w, l(1)
  mov r0.w, r0.z
  loop 
    uge r1.x, l(0), r0.w
    breakc_nz r1.x
    sync_g_t
    ult r1.x, vThreadIDInGroup.x, r0.w
    if_nz r1.x
      iadd r1.x, r0.w, vThreadIDInGroup.x
      ld_structured r1.y, vThreadIDInGroup.x, l(0), g3.xxxx
      ld_structured r1.x, r1.x, l(0), g3.xxxx
      add r1.x, r1.x, r1.y
      store_structured g3.x, vThreadIDInGroup.x, l(0), r1.x
    endif 
    ushr r0.w, r0.w, l(1)
  endloop 
  sync_g_t
  ld_structured r0.z, l(0), l(0), g3.xxxx
  if_z vThreadIDInGroup.x
    ld_raw r0.w, l(0), g1.xxxx
    add r0.z, r0.z, r0.w
    store_raw g1.x, l(0), r0.z
  endif 
  sync_g_t
  iadd r0.x, r0.x, l(1)
endloop 
if_z vThreadIDInGroup.x
  ld_raw r0.xy, l(8), g0.xyxx
  mul r0.x, r0.x, l(0.010000)
  ld_raw r0.z, l(8), g0.xxxx
  ld_raw r0.w, l(0), g1.xxxx
  max r0.x, |r0.x|, |r0.w|
  div r0.x, |r0.z|, r0.x
  mul r1.x, r0.x, r0.x
  mul r0.x, r0.x, r1.x
  add r0.z, -r0.z, r0.w
  mul r0.y, r0.y, r0.z
  mul r0.x, r0.x, r0.y
  store_structured u0.x, vThreadGroupID.x, l(0), r0.x
endif 
ret 
// Approximately 157 instruction slots used
