//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// Resource bind info for CalculateInflatableVolume::inflatables
// {
//
//   struct FlexInflatable
//   {
//       
//       int mStartTri;                 // Offset:    0
//       int mNumTris;                  // Offset:    4
//       float mRestVolume;             // Offset:    8
//       float mConstraintScale;        // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateInflatableVolume::positions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateInflatableVolume::reverseLookup
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateInflatableVolume::indices
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateInflatableVolume::lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CalculateInflatableVolume::inflatables    texture  struct         r/o             t0      1 
// CalculateInflatableVolume::positions    texture  struct         r/o             t1      1 
// CalculateInflatableVolume::reverseLookup    texture  struct         r/o             t2      1 
// CalculateInflatableVolume::indices    texture  struct         r/o             t3      1 
// CalculateInflatableVolume::lambdas        UAV  struct         r/w             u0      1 
// AmdDxExtShaderIntrinsicsUAV           UAV    byte         r/w             u7      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 16
dcl_resource_structured t1, 16
dcl_resource_structured t2, 4
dcl_resource_structured t3, 4
dcl_uav_structured u0, 4
dcl_uav_raw u7
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 20
dcl_tgsm_raw g0, 16
dcl_tgsm_raw g1, 4
dcl_tgsm_raw g2, 12
dcl_tgsm_structured g3, 4, 16
dcl_tgsm_structured g4, 12, 16
dcl_thread_group 512, 1, 1
if_z vThreadIDInGroup.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadGroupID.x, l(0), t0.xyzw
  store_raw g0.xyzw, l(0), r0.xyzw
  store_raw g1.x, l(0), l(0)
  store_raw g2.xyz, l(0), l(0,0,0,0)
endif 
sync_g_t
ld_raw r0.x, l(4), g0.xxxx
iadd r0.y, r0.x, l(511)
ushr r0.y, r0.y, l(9)
itof r0.x, r0.x
mul r0.x, r0.x, l(3.000000)
div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
and r0.z, vThreadIDInGroup.x, l(31)
ishr r0.w, vThreadIDInGroup.x, l(5)
mov r1.w, l(2)
mov r2.w, l(1)
mov r3.w, l(3)
mov r4.w, l(4)
mov r5.w, l(5)
mov r6.w, l(6)
mov r7.w, l(7)
mov r8.w, l(8)
mov r9.w, l(9)
mov r10.w, l(10)
mov r11.w, l(11)
mov r12.w, l(12)
mov r13.w, l(13)
mov r14.w, l(14)
mov r15.w, l(15)
mov r16.x, l(0)
loop 
  ige r16.y, r16.x, r0.y
  breakc_nz r16.y
  bfi r16.y, l(23), l(9), r16.x, vThreadIDInGroup.x
  ld_raw r16.zw, l(0), g0.xxxy
  ld_raw r17.x, l(4), g0.xxxx
  ilt r17.x, r16.y, r17.x
  if_nz r17.x
    iadd r16.y, r16.y, r16.z
    imul null, r16.z, r16.y, l(3)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r16.z, r16.z, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r16.z, r16.z, l(0), t2.xxxx
    imad r17.xy, r16.yyyy, l(3, 3, 0, 0), l(1, 2, 0, 0)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r16.y, r17.x, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r16.y, r16.y, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r17.x, r17.y, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r17.x, r17.x, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r17.yzw, r16.z, l(0), t1.xxyz
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r18.xyz, r16.y, l(0), t1.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r19.xyz, r17.x, l(0), t1.xyzx
    add r17.xyz, r17.yzwy, r18.xyzx
    add r17.xyz, r19.xyzx, r17.xyzx
    mul r17.xyz, r0.xxxx, r17.xyzx
  else 
    mov r17.xyz, l(0,0,0,0)
  endif 
  imm_atomic_cmp_exch r18.x, u7, l(0x50401f04), r17.x, l(0)
  imm_atomic_cmp_exch r18.y, u7, l(0x50401f04), r17.y, l(0)
  imm_atomic_cmp_exch r18.z, u7, l(0x50401f04), r17.z, l(0)
  add r17.xyz, r17.xyzx, r18.xyzx
  imm_atomic_cmp_exch r18.x, u7, l(0x50201f04), r17.x, l(0)
  imm_atomic_cmp_exch r18.y, u7, l(0x50201f04), r17.y, l(0)
  imm_atomic_cmp_exch r18.z, u7, l(0x50201f04), r17.z, l(0)
  add r17.xyz, r17.xyzx, r18.xyzx
  imm_atomic_cmp_exch r18.x, u7, l(0x50101f04), r17.x, l(0)
  imm_atomic_cmp_exch r18.y, u7, l(0x50101f04), r17.y, l(0)
  imm_atomic_cmp_exch r18.z, u7, l(0x50101f04), r17.z, l(0)
  add r17.xyz, r17.xyzx, r18.xyzx
  imm_atomic_cmp_exch r18.x, u7, l(0x50081f04), r17.x, l(0)
  imm_atomic_cmp_exch r18.y, u7, l(0x50081f04), r17.y, l(0)
  imm_atomic_cmp_exch r18.z, u7, l(0x50081f04), r17.z, l(0)
  add r17.xyz, r17.xyzx, r18.xyzx
  imm_atomic_cmp_exch r18.x, u7, l(0x50041f04), r17.x, l(0)
  imm_atomic_cmp_exch r18.y, u7, l(0x50041f04), r17.y, l(0)
  imm_atomic_cmp_exch r18.z, u7, l(0x50041f04), r17.z, l(0)
  if_z r0.z
    add r17.xyz, r17.xyzx, r18.xyzx
    store_structured g4.xyz, r0.w, l(0), r17.xyzx
  endif 
  sync_g_t
  if_z vThreadIDInGroup.x
    ishl r16.y, r16.x, l(9)
    iadd r16.y, -r16.y, r16.w
    imin r16.y, r16.y, l(512)
    ushr r16.y, r16.y, l(5)
    ld_structured r2.xyz, l(0), l(0), g4.xyzx
    ilt r16.z, l(1), r16.y
    ld_structured r17.xyz, l(1), l(0), g4.xyzx
    add r1.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r16.zzzz, r1.xyzw, r2.xyzw
    ilt r1.x, r17.w, r16.y
    ld_structured r2.xyz, l(2), l(0), g4.xyzx
    add r3.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r3.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(3), l(0), g4.xyzx
    add r4.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r4.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(4), l(0), g4.xyzx
    add r5.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r5.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(5), l(0), g4.xyzx
    add r6.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r6.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(6), l(0), g4.xyzx
    add r7.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r7.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(7), l(0), g4.xyzx
    add r8.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r8.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(8), l(0), g4.xyzx
    add r9.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r9.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(9), l(0), g4.xyzx
    add r10.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r10.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(10), l(0), g4.xyzx
    add r11.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r11.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(11), l(0), g4.xyzx
    add r12.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r12.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(12), l(0), g4.xyzx
    add r13.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r13.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(13), l(0), g4.xyzx
    add r14.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r14.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(14), l(0), g4.xyzx
    add r15.xyz, r2.xyzx, r17.xyzx
    movc r17.xyzw, r1.xxxx, r15.xyzw, r17.xyzw
    ilt r1.y, r17.w, r16.y
    and r1.x, r1.y, r1.x
    ld_structured r2.xyz, l(15), l(0), g4.xyzx
    add r2.xyz, r2.xyzx, r17.xyzx
    movc r1.xyz, r1.xxxx, r2.xyzx, r17.xyzx
    store_structured g4.xyz, l(0), l(0), r1.xyzx
  endif 
  sync_g_t
  ld_structured r1.xyz, l(0), l(0), g4.xyzx
  if_z vThreadIDInGroup.x
    ld_raw r2.x, l(0), g2.xxxx
    add r1.x, r1.x, r2.x
    store_raw g2.x, l(0), r1.x
    ld_raw r1.x, l(4), g2.xxxx
    add r1.x, r1.y, r1.x
    store_raw g2.x, l(4), r1.x
    ld_raw r1.x, l(8), g2.xxxx
    add r1.x, r1.z, r1.x
    store_raw g2.x, l(8), r1.x
  endif 
  sync_g_t
  iadd r16.x, r16.x, l(1)
endloop 
sync_g_t
mov r1.yw, l(0,2,0,1)
mov r2.yw, l(0,3,0,4)
mov r3.yw, l(0,5,0,6)
mov r4.yw, l(0,7,0,8)
mov r5.yw, l(0,9,0,10)
mov r6.yw, l(0,11,0,12)
mov r7.yw, l(0,13,0,14)
mov r8.y, l(15)
mov r0.x, l(0)
loop 
  ige r8.z, r0.x, r0.y
  breakc_nz r8.z
  bfi r8.z, l(23), l(9), r0.x, vThreadIDInGroup.x
  ld_raw r9.xy, l(0), g0.xyxx
  ld_raw r8.w, l(4), g0.xxxx
  ilt r8.w, r8.z, r8.w
  if_nz r8.w
    iadd r8.z, r8.z, r9.x
    imul null, r8.w, r8.z, l(3)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.w, r8.w, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.w, r8.w, l(0), t2.xxxx
    imad r9.xz, r8.zzzz, l(3, 0, 3, 0), l(1, 0, 2, 0)
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.z, r9.x, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.z, r8.z, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r9.x, r9.z, l(0), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r9.x, r9.x, l(0), t2.xxxx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r10.xyz, r8.w, l(0), t1.xyzx
    ld_raw r11.xyz, l(0), g2.xyzx
    add r10.xyz, r10.xyzx, -r11.xyzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r12.xyz, r8.z, l(0), t1.xyzx
    add r12.xyzw, -r11.yzzx, r12.yzzx
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r9.xzw, r9.x, l(0), t1.xxyz
    add r11.xyzw, -r11.zyxz, r9.wzxw
    add r12.xyzw, -r10.yzzx, r12.xyzw
    add r11.xyzw, -r10.zyxz, r11.xyzw
    mul r8.zw, r11.yyyw, r12.yyyw
    mad r13.xy, r12.xzxx, r11.xzxx, -r8.zwzz
    mul r8.z, r11.z, r12.x
    mad r13.z, r12.w, r11.y, -r8.z
    dp3 r8.z, r10.xyzx, r13.xyzx
  else 
    mov r8.z, l(0)
  endif 
  imm_atomic_cmp_exch r10.x, u7, l(0x50401f04), r8.z, l(0)
  add r8.z, r8.z, r10.x
  imm_atomic_cmp_exch r10.x, u7, l(0x50201f04), r8.z, l(0)
  add r8.z, r8.z, r10.x
  imm_atomic_cmp_exch r10.x, u7, l(0x50101f04), r8.z, l(0)
  add r8.z, r8.z, r10.x
  imm_atomic_cmp_exch r10.x, u7, l(0x50081f04), r8.z, l(0)
  add r8.z, r8.z, r10.x
  imm_atomic_cmp_exch r10.x, u7, l(0x50041f04), r8.z, l(0)
  if_z r0.z
    add r8.z, r8.z, r10.x
    store_structured g3.x, r0.w, l(0), r8.z
  endif 
  sync_g_t
  if_z vThreadIDInGroup.x
    ishl r8.z, r0.x, l(9)
    iadd r8.z, -r8.z, r9.y
    imin r8.z, r8.z, l(512)
    ushr r8.z, r8.z, l(5)
    ld_structured r1.z, l(0), l(0), g3.xxxx
    ilt r8.w, l(1), r8.z
    ld_structured r9.x, l(1), l(0), g3.xxxx
    add r1.x, r1.z, r9.x
    movc r1.xz, r8.wwww, r1.xxyx, r1.zzwz
    ilt r8.w, r1.z, r8.z
    ld_structured r9.x, l(2), l(0), g3.xxxx
    add r2.x, r1.x, r9.x
    movc r1.xz, r8.wwww, r2.xxyx, r1.xxzx
    ilt r2.x, r1.z, r8.z
    and r2.x, r2.x, r8.w
    ld_structured r8.w, l(3), l(0), g3.xxxx
    add r2.z, r1.x, r8.w
    movc r1.xz, r2.xxxx, r2.zzwz, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(4), l(0), g3.xxxx
    add r3.x, r1.x, r2.z
    movc r1.xz, r2.xxxx, r3.xxyx, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(5), l(0), g3.xxxx
    add r3.z, r1.x, r2.z
    movc r1.xz, r2.xxxx, r3.zzwz, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(6), l(0), g3.xxxx
    add r4.x, r1.x, r2.z
    movc r1.xz, r2.xxxx, r4.xxyx, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(7), l(0), g3.xxxx
    add r4.z, r1.x, r2.z
    movc r1.xz, r2.xxxx, r4.zzwz, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(8), l(0), g3.xxxx
    add r5.x, r1.x, r2.z
    movc r1.xz, r2.xxxx, r5.xxyx, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(9), l(0), g3.xxxx
    add r5.z, r1.x, r2.z
    movc r1.xz, r2.xxxx, r5.zzwz, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(10), l(0), g3.xxxx
    add r6.x, r1.x, r2.z
    movc r1.xz, r2.xxxx, r6.xxyx, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(11), l(0), g3.xxxx
    add r6.z, r1.x, r2.z
    movc r1.xz, r2.xxxx, r6.zzwz, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(12), l(0), g3.xxxx
    add r7.x, r1.x, r2.z
    movc r1.xz, r2.xxxx, r7.xxyx, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(13), l(0), g3.xxxx
    add r7.z, r1.x, r2.z
    movc r1.xz, r2.xxxx, r7.zzwz, r1.xxzx
    ilt r2.z, r1.z, r8.z
    and r2.x, r2.z, r2.x
    ld_structured r2.z, l(14), l(0), g3.xxxx
    add r8.x, r1.x, r2.z
    movc r1.xz, r2.xxxx, r8.xxyx, r1.xxzx
    ilt r1.z, r1.z, r8.z
    and r1.z, r1.z, r2.x
    ld_structured r2.x, l(15), l(0), g3.xxxx
    add r2.x, r1.x, r2.x
    movc r1.x, r1.z, r2.x, r1.x
    store_structured g3.x, l(0), l(0), r1.x
  endif 
  sync_g_t
  ld_structured r1.x, l(0), l(0), g3.xxxx
  if_z vThreadIDInGroup.x
    ld_raw r1.z, l(0), g1.xxxx
    add r1.x, r1.x, r1.z
    store_raw g1.x, l(0), r1.x
  endif 
  sync_g_t
  iadd r0.x, r0.x, l(1)
endloop 
if_z vThreadIDInGroup.x
  ld_raw r0.xy, l(8), g0.xyxx
  mul r0.x, r0.x, l(0.010000)
  ld_raw r0.z, l(8), g0.xxxx
  ld_raw r0.w, l(0), g1.xxxx
  max r0.x, |r0.x|, |r0.w|
  div r0.x, |r0.z|, r0.x
  mul r1.x, r0.x, r0.x
  mul r0.x, r0.x, r1.x
  add r0.z, -r0.z, r0.w
  mul r0.y, r0.y, r0.z
  mul r0.x, r0.x, r0.y
  store_structured u0.x, vThreadGroupID.x, l(0), r0.x
endif 
ret 
// Approximately 342 instruction slots used
