//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:44 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for CalculateAnisotropy::contacts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateAnisotropy::contactCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateAnisotropy::phases
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for CalculateAnisotropy::sortedPositionsTex
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateAnisotropy::q1
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateAnisotropy::q2
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for CalculateAnisotropy::q3
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CalculateAnisotropy::contacts     texture  struct         r/o             t0      1 
// CalculateAnisotropy::contactCounts    texture  struct         r/o             t1      1 
// CalculateAnisotropy::indices      texture    uint         buf             t2      1 
// CalculateAnisotropy::phases       texture  struct         r/o             t3      1 
// CalculateAnisotropy::sortedPositionsTex    texture  struct         r/o             t4      1 
// CalculateAnisotropy::q1               UAV  struct         r/w             u0      1 
// CalculateAnisotropy::q2               UAV  struct         r/w             u1      1 
// CalculateAnisotropy::q3               UAV  struct         r/w             u2      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 4
dcl_resource_buffer (uint,uint,uint,uint) t2
dcl_resource_structured t3, 4
dcl_resource_structured t4, 16
dcl_uav_structured u0, 16
dcl_uav_structured u1, 16
dcl_uav_structured u2, 16
dcl_input vThreadID.x
dcl_temps 17
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[23].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), t4.xyzx
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), t1.xxxx
  mov r2.x, vThreadID.x
  mov r1.xyzw, l(0,0,0,0)
  mov r2.y, l(0)
  loop 
    ige r2.z, r2.y, r0.w
    breakc_nz r2.z
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.z, r2.x, l(0), t0.xxxx
    iadd r2.x, r2.x, cb0[23].y
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.z, l(0), t3.xxxx
    and r2.w, r2.w, l(0x00400000)
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xyz, r2.z, l(0), t4.xyzx
    add r4.xyz, r0.xyzx, -r3.xyzx
    dp3 r2.z, r4.xyzx, r4.xyzx
    lt r3.w, r2.z, cb0[8].z
    lt r4.x, l(0.000000), r2.z
    and r3.w, r3.w, r4.x
    rsq r4.x, r2.z
    mul r2.z, r2.z, r4.x
    mul r2.z, r2.z, cb0[8].w
    mul r4.x, r2.z, r2.z
    mad r2.z, -r4.x, r2.z, l(1.000000)
    mad r4.xyz, r3.xyzx, r2.zzzz, r1.xyzx
    add r4.w, r1.w, r2.z
    movc r3.xyzw, r3.wwww, r4.xyzw, r1.xyzw
    movc r1.xyzw, r2.wwww, r3.xyzw, r1.xyzw
    iadd r2.y, r2.y, l(1)
  endloop 
  ld_indexable(buffer)(uint,uint,uint,uint) r2.x, vThreadID.xxxx, t2.xyzw
  eq r2.y, r1.w, l(0.000000)
  ilt r2.z, r0.w, l(0)
  or r2.y, r2.z, r2.y
  if_nz r2.y
    mov r3.xy, l(1.000000,0,0,0)
    mov r3.w, cb0[13].z
    store_structured u0.xyzw, r2.x, l(0), r3.xyyw
    store_structured u1.xyzw, r2.x, l(0), r3.yxyw
    store_structured u2.xyzw, r2.x, l(0), r3.yyxw
    ret 
  endif 
  div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), r1.w
  mov r3.xyzw, l(0,0,0,0)
  mov r4.xyzw, l(0,0,0,0)
  mov r2.y, vThreadID.x
  mov r2.zw, l(0,0,0,0)
  loop 
    ige r5.x, r2.w, r0.w
    breakc_nz r5.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.x, r2.y, l(0), t0.xxxx
    iadd r2.y, r2.y, cb0[23].y
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.y, r5.x, l(0), t3.xxxx
    and r5.y, r5.y, l(0x00400000)
    if_nz r5.y
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r5.xyz, r5.x, l(0), t4.xyzx
      add r6.xyz, r0.xyzx, -r5.xyzx
      dp3 r5.w, r6.xyzx, r6.xyzx
      lt r6.x, r5.w, cb0[8].z
      lt r6.y, l(0.000000), r5.w
      and r6.x, r6.y, r6.x
      if_nz r6.x
        sqrt r5.w, r5.w
        mul r5.w, r5.w, cb0[8].w
        mul r6.x, r5.w, r5.w
        mad r5.w, -r6.x, r5.w, l(1.000000)
        mad r5.xyz, -r1.xyzx, r1.wwww, r5.xyzx
        mul r6.xyz, r5.xxxx, r5.xyzx
        mul r7.xyz, r5.yyyy, r5.yzxy
        mul r5.xyz, r5.zzzz, r5.xyzx
        mov r6.w, r7.z
        mov r7.zw, r5.xxxy
        mad r3.xyzw, r5.wwww, r6.xyzw, r3.xyzw
        mad r4.xyzw, r5.wwww, r7.xyzw, r4.xyzw
        mad r2.z, r5.w, r5.z, r2.z
      endif 
    endif 
    iadd r2.w, r2.w, l(1)
  endloop 
  mul r0.xyzw, r1.wwww, r3.xyzw
  mul r3.xyzw, r1.wwww, r4.xyzw
  mul r1.x, r1.w, r2.z
  mov r4.xz, l(1,0,0,0)
  mov r5.x, l(0)
  mov r6.xz, l(2,0,0,0)
  mov r7.w, l(0)
  mov r8.xyz, l(1.000000,0,0,0)
  mov r9.xyz, l(0,1.000000,0,0)
  mov r10.xyz, l(0,0,1.000000,0)
  mov r11.zw, r3.zzzw
  mov r1.y, r0.x
  mov r11.xy, r0.yzyy
  mov r12.x, r0.w
  mov r12.y, r3.x
  mov r13.z, r3.y
  mov r12.z, r1.x
  mov r1.z, l(0)
  loop 
    ige r1.w, r1.z, l(4)
    breakc_nz r1.w
    mov r4.yw, |r11.yyyx|
    lt r1.w, r4.w, r4.y
    movc r2.yz, r1.wwww, r4.xxyx, r4.zzwz
    mov r6.y, |r13.z|
    lt r1.w, r2.z, r6.y
    movc r2.yz, r1.wwww, r6.xxyx, r2.yyzy
    lt r1.w, r2.z, l(0.00000000)
    if_nz r1.w
      break 
    endif 
    if_z r2.y
      ne r1.w, r11.x, l(0.000000)
      add r2.z, r1.y, -r12.y
      add r2.w, r11.x, r11.x
      rcp r2.w, r2.w
      mul r2.z, r2.w, r2.z
      mad r2.w, r2.z, r2.z, l(1.000000)
      sqrt r2.w, r2.w
      add r2.w, r2.w, |r2.z|
      rcp r2.w, r2.w
      lt r4.y, l(0.000000), r2.z
      lt r2.z, r2.z, l(0.000000)
      iadd r2.z, -r4.y, r2.z
      itof r2.z, r2.z
      mul r2.z, r2.z, r2.w
      mad r2.w, r2.z, r2.z, l(1.000000)
      rsq r2.w, r2.w
      mul r4.y, r2.w, r2.z
      mad r14.x, r2.z, r11.x, r1.y
      mad r5.y, -r2.z, r11.x, r12.y
      mul r15.xy, r11.zwzz, r2.wwww
      mad r14.y, r4.y, r11.w, r15.x
      mad r5.z, -r4.y, r11.z, r15.y
      mul r15.xyz, r9.xyzx, r4.yyyy
      mul r16.xyz, r9.xyzx, r2.wwww
      mad r15.xyz, r2.wwww, r8.xyzx, r15.xyzx
      mad r16.xyz, -r4.yyyy, r8.xyzx, r16.xyzx
      mov r11.x, r1.y
      movc r11.xy, r1.wwww, r14.xyxx, r11.xyxx
      mov r13.xy, r12.xyxx
      movc r13.xyz, r1.wwww, r5.xyzx, r13.xyzx
      movc r8.xyz, r1.wwww, r15.xyzx, r8.xyzx
      movc r9.xyz, r1.wwww, r16.xyzx, r9.xyzx
      mov r14.z, r5.z
      movc r11.zw, r1.wwww, r14.yyyz, r11.zzzw
      mov r1.y, r11.x
      mov r11.x, l(0)
      mov r12.xy, r13.xyxx
    else 
      ieq r1.w, r2.y, l(1)
      if_nz r1.w
        ne r1.w, r11.y, l(0.000000)
        add r2.y, r1.y, -r12.z
        add r2.z, r11.y, r11.y
        rcp r2.z, r2.z
        mul r2.y, r2.z, r2.y
        mad r2.z, r2.y, r2.y, l(1.000000)
        sqrt r2.z, r2.z
        add r2.z, r2.z, |r2.y|
        rcp r2.z, r2.z
        lt r2.w, l(0.000000), r2.y
        lt r2.y, r2.y, l(0.000000)
        iadd r2.y, -r2.w, r2.y
        itof r2.y, r2.y
        mul r2.y, r2.y, r2.z
        mad r2.z, r2.y, r2.y, l(1.000000)
        rsq r2.z, r2.z
        mul r2.w, r2.z, r2.y
        mad r14.x, r2.y, r11.y, r1.y
        mad r14.w, -r2.y, r11.y, r12.z
        mul r2.y, r13.z, r2.w
        mad r14.y, r2.z, r12.x, r2.y
        mul r2.y, r13.z, r2.z
        mad r14.z, -r2.w, r12.x, r2.y
        mul r5.yzw, r10.xxyz, r2.wwww
        mul r15.xyz, r10.xyzx, r2.zzzz
        mad r5.yzw, r2.zzzz, r8.xxyz, r5.yyzw
        mad r2.yzw, -r2.wwww, r8.xxyz, r15.xxyz
        mov r11.y, r1.y
        movc r11.xy, r1.wwww, r14.yxyy, r11.xyxx
        mov r13.xy, r12.xzxx
        movc r13.xyz, r1.wwww, r14.ywzy, r13.xyzx
        movc r8.xyz, r1.wwww, r5.yzwy, r8.xyzx
        movc r10.xyz, r1.wwww, r2.yzwy, r10.xyzx
        mov r6.w, r14.z
        movc r11.zw, r1.wwww, r6.zzzw, r11.zzzw
        mov r1.y, r11.y
        mov r11.y, l(0)
        mov r12.xz, r13.xxyx
      else 
        ne r1.w, r13.z, l(0.000000)
        add r2.y, -r12.z, r12.y
        add r2.z, r13.z, r13.z
        rcp r2.z, r2.z
        mul r2.y, r2.z, r2.y
        mad r2.z, r2.y, r2.y, l(1.000000)
        sqrt r2.z, r2.z
        add r2.z, r2.z, |r2.y|
        rcp r2.z, r2.z
        lt r2.w, l(0.000000), r2.y
        lt r2.y, r2.y, l(0.000000)
        iadd r2.y, -r2.w, r2.y
        itof r2.y, r2.y
        mul r2.y, r2.y, r2.z
        mad r2.z, r2.y, r2.y, l(1.000000)
        rsq r2.z, r2.z
        mul r2.w, r2.z, r2.y
        mad r14.y, r2.y, r13.z, r12.y
        mad r14.z, -r2.y, r13.z, r12.z
        mul r2.y, r11.y, r2.w
        mad r14.x, r2.z, r11.x, r2.y
        mul r2.y, r11.y, r2.z
        mad r7.yz, -r2.wwww, r11.xxxx, r2.yyyy
        mul r5.yzw, r10.xxyz, r2.wwww
        mul r13.xyw, r10.xyxz, r2.zzzz
        mad r5.yzw, r2.zzzz, r9.xxyz, r5.yyzw
        mad r2.yzw, -r2.wwww, r9.xxyz, r13.xxyw
        movc r12.xyz, r1.wwww, r14.xyzx, r12.xyzx
        movc r9.xyz, r1.wwww, r5.yzwy, r9.xyzx
        movc r10.xyz, r1.wwww, r2.yzwy, r10.xyzx
        mov r7.x, r14.x
        movc r11.xyzw, r1.wwww, r7.xyzw, r11.xyzw
        mov r13.z, l(0)
      endif 
    endif 
    iadd r1.z, r1.z, l(1)
  endloop 
  sqrt r0.x, r1.y
  sqrt r0.yz, r12.yyzy
  mul r0.xyz, r0.xyzx, cb0[13].yyyy
  max r0.xyz, r0.xyzx, cb0[13].zzzz
  min r0.xyz, r0.xyzx, cb0[13].wwww
  mov r8.w, r0.x
  store_structured u0.xyzw, r2.x, l(0), r8.xyzw
  mov r9.w, r0.y
  store_structured u1.xyzw, r2.x, l(0), r9.xyzw
  mov r10.w, r0.z
  store_structured u2.xyzw, r2.x, l(0), r10.xyzw
endif 
ret 
// Approximately 241 instruction slots used
