//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:45 2026
//
//
// Buffer Definitions: 
//
// cbuffer consts
// {
//
//   struct KernelParams
//   {
//       
//       float4 kPlanes[8];             // Offset:    0
//       int kNumPlanes;                // Offset:  128
//       float kRadius;                 // Offset:  132
//       float kRadiusSq;               // Offset:  136
//       float kInvRadius;              // Offset:  140
//       float kPoly6;                  // Offset:  144
//       float kSpiky1;                 // Offset:  148
//       float kSpiky2;                 // Offset:  152
//       float kAkinci1;                // Offset:  156
//       float kAkinci2;                // Offset:  160
//       float kCohesion1;              // Offset:  164
//       float kCohesion2;              // Offset:  168
//       float _pad0;                   // Offset:  172
//       float kRestDensity;            // Offset:  176
//       float kInvRestDensity;         // Offset:  180
//       float kFluidRestDistance;      // Offset:  184
//       float kSolidRestDistance;      // Offset:  188
//       float kLambdaScale;            // Offset:  192
//       float kCohesion;               // Offset:  196
//       float kSurfaceTension;         // Offset:  200
//       float kSolidPressure;          // Offset:  204
//       float kVorticityConfinement;   // Offset:  208
//       float kAnisotropy;             // Offset:  212
//       float kAnisotropyMin;          // Offset:  216
//       float kAnisotropyMax;          // Offset:  220
//       float kSmoothing;              // Offset:  224
//       float kViscosity;              // Offset:  228
//       float kFreeSurfaceDrag;        // Offset:  232
//       float kBuoyancy;               // Offset:  236
//       float kDiffuseThreshold;       // Offset:  240
//       float kDiffuseBuoyancy;        // Offset:  244
//       float kDiffuseDrag;            // Offset:  248
//       int kDiffuseBallistic;         // Offset:  252
//       float3 kGravity;               // Offset:  256
//       float kDynamicFriction;        // Offset:  268
//       float kStaticFriction;         // Offset:  272
//       float kParticleFriction;       // Offset:  276
//       float kAdhesion;               // Offset:  280
//       float kDissipation;            // Offset:  284
//       float kDamping;                // Offset:  288
//       float kInertiaBias;            // Offset:  292
//       float kCollisionDistance;      // Offset:  296
//       float kCollisionThreshold;     // Offset:  300
//       float kCollisionMargin;        // Offset:  304
//       float kCollisionMarginSq;      // Offset:  308
//       float _pad1;                   // Offset:  312
//       float _pad2;                   // Offset:  316
//       float kDrag;                   // Offset:  320
//       float kLift;                   // Offset:  324
//       float kPlasticThreshold_deprecated;// Offset:  328
//       float kPlasticCreep_deprecated;// Offset:  332
//       float kSleepThreshold;         // Offset:  336
//       float kSleepThresholdSq;       // Offset:  340
//       float kShockPropagation;       // Offset:  344
//       float kRestitution;            // Offset:  348
//       float kSOR;                    // Offset:  352
//       float3 _pad3;                  // Offset:  356
//       int kNumParticles;             // Offset:  368
//       int kNumParticlesAligned;      // Offset:  372
//       float kDt;                     // Offset:  376
//       float kInvDt;                  // Offset:  380
//       float kSubStepLength;          // Offset:  384
//       float kMaxSpeed;               // Offset:  388
//       float kInvCellEdge;            // Offset:  392
//       float kStaticTriGridInvCellEdge;// Offset:  396
//       float kCollideParticlesRadiusSq;// Offset:  400
//       int kMaxParticles;             // Offset:  404
//       int kRelaxationMode;           // Offset:  408
//       int kShapesCount;              // Offset:  412
//       int kNumShapes;                // Offset:  416
//       int kNumRigids;                // Offset:  420
//       int kNumSprings;               // Offset:  424
//       int kNumTriangles;             // Offset:  428
//       int kMaxDiffuseParticles;      // Offset:  432
//       int kDiffuseRadixSortSize;     // Offset:  436
//       float kDiffuseDt;              // Offset:  440
//       float kDiffuseMaxVelocity;     // Offset:  444
//       float3 kDiffuseSortAxis;       // Offset:  448
//       float kRelaxationFactor;       // Offset:  460
//       float3 kStaticTriGridLower;    // Offset:  464
//       float kDiffuseLifetime;        // Offset:  476
//       float3 kWind;                  // Offset:  480
//       int kMaxNeighborsPerParticle;  // Offset:  492
//       int kNumGeometryEntries;       // Offset:  496
//       float kMaxAcceleration;        // Offset:  500
//       float kMaxVelocityDelta;       // Offset:  504
//       int kMaxContactsPerParticle;   // Offset:  508
//
//   } gParams;                         // Offset:    0 Size:   512
//
// }
//
// Resource bind info for SolveDensities::contacts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveDensities::contactCounts
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for SolveDensities::sortedNewPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveDensities::sortedPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for SolveDensities::sortedNormals
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SolveDensities::contacts          texture  struct         r/o             t0      1 
// SolveDensities::contactCounts     texture  struct         r/o             t1      1 
// SolveDensities::sortedNewPositions    texture  struct         r/o             t2      1 
// SolveDensities::sortedPositions    texture  struct         r/o             t6      1 
// SolveDensities::sortedNormals     texture  struct         r/o             t7      1 
// SolveDensities::deltas                UAV    byte         r/w             u0      1 
// consts                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 4
dcl_resource_structured t2, 16
dcl_resource_structured t6, 16
dcl_resource_structured t7, 16
dcl_uav_raw u0
dcl_input vThreadID.x
dcl_temps 11
dcl_thread_group 256, 1, 1
ilt r0.x, vThreadID.x, cb0[23].x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), t2.xyzw
  eq r1.x, r0.w, l(0.000000)
  if_nz r1.x
    ishl r1.x, vThreadID.x, l(4)
    store_raw u0.xyzw, r1.x, l(0,0,0,0)
    ret 
  endif 
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(0), t6.xyzx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyzw, vThreadID.x, l(0), t7.xyzw
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(0), t1.xxxx
  mov r3.xyz, -r2.xyzx
  min r3.w, r2.w, l(0.000000)
  lt r2.x, l(0.000000), cb0[16].w
  mov r2.y, vThreadID.x
  mov r4.xyzw, l(0,0,0,0)
  mov r2.z, l(0)
  loop 
    ige r2.w, r2.z, r1.w
    breakc_nz r2.w
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.y, l(0), t0.xxxx
    iadd r5.x, r2.y, cb0[23].y
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r6.xyzw, r2.w, l(0), t2.xyzw
    add r5.yzw, r0.xxyz, -r6.xxyz
    dp3 r6.x, r5.yzwy, r5.yzwy
    ge r6.y, cb0[8].z, r6.x
    lt r6.z, l(0.000000), r6.x
    and r6.y, r6.z, r6.y
    if_nz r6.y
      sqrt r6.x, r6.x
      lt r6.y, cb0[11].w, r6.x
      if_nz r6.y
        iadd r6.y, r2.z, l(1)
        mov r2.y, r5.x
        mov r2.z, r6.y
        continue 
      endif 
      div r6.y, l(1.000000, 1.000000, 1.000000, 1.000000), r6.x
      mul r7.xyz, r5.yzwy, r6.yyyy
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r8.xyzw, r2.w, l(0), t7.xyzw
      add r6.y, r0.w, r6.w
      div r6.y, r0.w, r6.y
      lt r6.z, r8.w, r3.w
      movc r8.xyzw, r6.zzzz, r8.xyzw, r3.xyzw
      eq r6.z, r8.w, l(0.000000)
      add r9.w, r6.x, -cb0[11].w
      ge r6.x, r8.w, -cb0[11].w
      dp3 r6.w, r8.xyzx, r7.xyzx
      lt r10.x, r6.w, l(0.000000)
      add r6.w, r6.w, r6.w
      mad r10.yzw, -r6.wwww, r8.xxyz, r7.xxyz
      movc r9.xyz, r10.xxxx, r10.yzwy, r7.xyzx
      movc r8.xyzw, r6.xxxx, r9.xyzw, r8.xyzw
      mov r7.w, r9.w
      movc r7.xyzw, r6.zzzz, r7.xyzw, r8.xyzw
      mul r6.x, r6.y, r7.w
      mad r6.xzw, -r6.xxxx, r7.xxyz, r4.xxyz
      dp3 r8.x, r7.xyzx, r7.xyzx
      lt r8.x, l(0.000000), r8.x
      and r8.x, r2.x, r8.x
      ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r8.yzw, r2.w, l(0), t6.xxyz
      add r8.yzw, r1.xxyz, -r8.yyzw
      add r5.yzw, r5.yyzw, -r8.yyzw
      dp3 r2.w, r5.yzwy, r7.xyzx
      mad r5.yzw, -r2.wwww, r7.xxyz, r5.yyzw
      dp3 r2.w, r5.yzwy, r5.yzwy
      rsq r7.x, r2.w
      mul r7.y, r7.w, cb0[17].x
      mul r7.y, r7.y, r7.y
      lt r2.w, r2.w, r7.y
      mul r8.yzw, r5.yyzw, r6.yyyy
      mad r5.yzw, -r6.yyyy, r5.yyzw, r6.xxzw
      mul r6.y, -r7.w, cb0[17].y
      mul r6.y, r7.x, r6.y
      min r6.y, r6.y, l(1.000000)
      mad r7.xyz, -r8.yzwy, r6.yyyy, r6.xzwx
      movc r5.yzw, r2.wwww, r5.yyzw, r7.xxyz
      movc r4.xyz, r8.xxxx, r5.yzwy, r6.xzwx
      add r4.w, r4.w, l(1.000000)
    endif 
    iadd r2.z, r2.z, l(1)
    mov r2.y, r5.x
  endloop 
  ishl r0.x, vThreadID.x, l(4)
  store_raw u0.xyzw, r0.x, r4.xyzw
endif 
ret 
// Approximately 88 instruction slots used
