//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer params
// {
//
//   uint3 gridDim;                     // Offset:    0 Size:    12
//   uint passStart;                    // Offset:   12 Size:     4
//   uint numCounters;                  // Offset:   16 Size:     4 [unused]
//   uint numKeys;                      // Offset:   20 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// srcKey                            texture   uint4         buf             t0      1 
// counters                              UAV    uint         buf             u0      1 
// params                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_buffer (uint,uint,uint,uint) t0
dcl_uav_typed_buffer (uint,uint,uint,uint) u0
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 5
dcl_tgsm_structured g0, 16, 256
dcl_tgsm_structured g1, 16, 64
dcl_thread_group 256, 1, 1
imad r0.x, vThreadGroupID.x, l(256), vThreadIDInGroup.x
ld_indexable(buffer)(uint,uint,uint,uint) r0.xyzw, r0.xxxx, t0.xyzw
ishl r1.x, vThreadIDInGroup.x, l(2)
imad r1.x, vThreadGroupID.x, l(1024), r1.x
uge r1.y, r1.x, cb0[1].y
movc r0.x, r1.y, l(-1), r0.x
iadd r1.xyz, r1.xxxx, l(1, 2, 3, 0)
uge r1.xyz, r1.xyzx, cb0[1].yyyy
movc r0.yzw, r1.xxyz, l(0,-1,-1,-1), r0.yyzw
ushr r0.xyzw, r0.xyzw, cb0[0].wwww
and r0.xyzw, r0.xyzw, l(15, 15, 15, 15)
ieq r1.xyzw, r0.xxxx, l(1, 2, 3, 4)
movc r2.xy, r0.xxxx, l(0,0x00010000,0,0), l(1,0x00010001,0,0)
movc r1.x, r1.x, r2.y, r2.x
and r2.xy, r1.ywyy, l(1, 1, 0, 0)
movc r1.yw, r1.yyyw, l(0,0x00010001,0,0x00010001), l(0,0x00010000,0,0x00010000)
movc r1.y, r1.z, r1.y, r2.x
ieq r3.xyzw, r0.xxxx, l(5, 6, 7, 8)
movc r1.z, r3.x, r1.w, r2.y
and r1.w, r3.y, l(1)
movc r2.x, r3.y, l(0x00010001), l(0x00010000)
movc r1.w, r3.z, r2.x, r1.w
iadd r2.x, r1.x, l(256)
movc r1.x, r3.w, r2.x, r1.x
ieq r2.xyzw, r0.xxxx, l(9, 10, 11, 12)
iadd r3.x, r1.x, l(0x01000000)
movc r1.x, r2.x, r3.x, r1.x
iadd r2.x, r1.y, l(256)
movc r1.y, r2.y, r2.x, r1.y
iadd r2.x, r1.y, l(0x01000000)
movc r1.y, r2.z, r2.x, r1.y
iadd r2.x, r1.z, l(256)
movc r1.z, r2.w, r2.x, r1.z
ieq r2.xyz, r0.xxxx, l(13, 14, 15, 0)
iadd r0.x, r1.z, l(0x01000000)
movc r0.x, r2.x, r0.x, r1.z
iadd r1.z, r1.w, l(256)
movc r1.z, r2.y, r1.z, r1.w
iadd r1.w, r1.z, l(0x01000000)
movc r1.z, r2.z, r1.w, r1.z
iadd r1.w, r1.x, l(1)
movc r1.x, r0.y, r1.x, r1.w
ieq r2.xyzw, r0.yyyy, l(1, 2, 3, 4)
iadd r1.w, r1.x, l(0x00010000)
movc r1.x, r2.x, r1.w, r1.x
iadd r1.y, r1.y, -r2.y
iadd r1.w, r1.y, l(0x00010000)
movc r1.y, r2.z, r1.w, r1.y
iadd r0.x, r0.x, -r2.w
ieq r2.xyzw, r0.yyyy, l(5, 6, 7, 8)
iadd r1.w, r0.x, l(0x00010000)
movc r0.x, r2.x, r1.w, r0.x
iadd r1.z, r1.z, -r2.y
iadd r1.w, r1.z, l(0x00010000)
movc r1.z, r2.z, r1.w, r1.z
iadd r1.w, r1.x, l(256)
movc r1.x, r2.w, r1.w, r1.x
ieq r2.xyzw, r0.yyyy, l(9, 10, 11, 12)
iadd r1.w, r1.x, l(0x01000000)
movc r1.x, r2.x, r1.w, r1.x
iadd r1.w, r1.y, l(256)
movc r1.y, r2.y, r1.w, r1.y
iadd r1.w, r1.y, l(0x01000000)
movc r1.y, r2.z, r1.w, r1.y
iadd r1.w, r0.x, l(256)
movc r0.x, r2.w, r1.w, r0.x
ieq r2.xyzw, r0.yyyz, l(13, 14, 15, 1)
iadd r0.y, r0.x, l(0x01000000)
movc r0.x, r2.x, r0.y, r0.x
iadd r0.y, r1.z, l(256)
movc r0.y, r2.y, r0.y, r1.z
iadd r1.z, r0.y, l(0x01000000)
movc r0.y, r2.z, r1.z, r0.y
iadd r1.z, r1.x, l(1)
movc r1.x, r0.z, r1.x, r1.z
iadd r1.z, r1.x, l(0x00010000)
movc r1.x, r2.w, r1.z, r1.x
ieq r2.xyzw, r0.zzzz, l(2, 3, 4, 5)
iadd r1.y, r1.y, -r2.x
iadd r1.z, r1.y, l(0x00010000)
movc r1.y, r2.y, r1.z, r1.y
iadd r0.x, r0.x, -r2.z
iadd r1.z, r0.x, l(0x00010000)
movc r0.x, r2.w, r1.z, r0.x
ieq r2.xyzw, r0.zzzz, l(6, 7, 8, 9)
iadd r0.y, r0.y, -r2.x
iadd r1.z, r0.y, l(0x00010000)
movc r0.y, r2.y, r1.z, r0.y
iadd r1.z, r1.x, l(256)
movc r1.x, r2.z, r1.z, r1.x
iadd r1.z, r1.x, l(0x01000000)
movc r1.x, r2.w, r1.z, r1.x
ieq r2.xyzw, r0.zzzz, l(10, 11, 12, 13)
iadd r1.z, r1.y, l(256)
movc r1.y, r2.x, r1.z, r1.y
iadd r1.z, r1.y, l(0x01000000)
movc r1.y, r2.y, r1.z, r1.y
iadd r1.z, r0.x, l(256)
movc r0.x, r2.z, r1.z, r0.x
iadd r1.z, r0.x, l(0x01000000)
movc r0.x, r2.w, r1.z, r0.x
ieq r2.xyzw, r0.zzww, l(14, 15, 1, 2)
iadd r0.z, r0.y, l(256)
movc r0.y, r2.x, r0.z, r0.y
iadd r0.z, r0.y, l(0x01000000)
movc r0.y, r2.y, r0.z, r0.y
iadd r0.z, r1.x, l(1)
movc r0.z, r0.w, r1.x, r0.z
iadd r1.x, r0.z, l(0x00010000)
movc r0.z, r2.z, r1.x, r0.z
iadd r1.x, r1.y, -r2.w
ieq r2.xyzw, r0.wwww, l(3, 4, 5, 6)
iadd r1.y, r1.x, l(0x00010000)
movc r1.x, r2.x, r1.y, r1.x
iadd r0.xy, r0.xyxx, -r2.ywyy
iadd r1.y, r0.x, l(0x00010000)
movc r0.x, r2.z, r1.y, r0.x
ieq r2.xyzw, r0.wwww, l(7, 8, 9, 10)
iadd r1.y, r0.y, l(0x00010000)
movc r0.y, r2.x, r1.y, r0.y
iadd r1.y, r0.z, l(256)
movc r0.z, r2.y, r1.y, r0.z
iadd r1.y, r0.z, l(0x01000000)
movc r3.x, r2.z, r1.y, r0.z
iadd r0.z, r1.x, l(256)
movc r0.z, r2.w, r0.z, r1.x
ieq r1.xyzw, r0.wwww, l(11, 12, 13, 14)
iadd r2.x, r0.z, l(0x01000000)
movc r3.y, r1.x, r2.x, r0.z
iadd r0.z, r0.x, l(256)
movc r0.x, r1.y, r0.z, r0.x
iadd r0.z, r0.x, l(0x01000000)
movc r3.z, r1.z, r0.z, r0.x
iadd r0.x, r0.y, l(256)
movc r0.x, r1.w, r0.x, r0.y
ieq r0.y, r0.w, l(15)
iadd r0.z, r0.x, l(0x01000000)
movc r3.w, r0.y, r0.z, r0.x
store_structured g0.xyzw, vThreadIDInGroup.x, l(0), r3.xyzw
sync_g_t
ult r0.xy, vThreadIDInGroup.xxxx, l(64, 16, 0, 0)
if_nz r0.x
  iadd r0.xzw, vThreadIDInGroup.xxxx, l(64, 0, 128, 192)
  ld_structured r1.xyzw, r0.x, l(0), g0.xyzw
  iadd r1.xyzw, r1.xyzw, r3.xyzw
  ld_structured r2.xyzw, r0.z, l(0), g0.xyzw
  iadd r1.xyzw, r1.xyzw, r2.xyzw
  ld_structured r2.xyzw, r0.w, l(0), g0.xyzw
  iadd r1.xyzw, r1.xyzw, r2.xyzw
  store_structured g1.xyzw, vThreadIDInGroup.x, l(0), r1.xyzw
endif 
sync_g_t
if_nz r0.y
  ld_structured r0.xyzw, vThreadIDInGroup.x, l(0), g1.xyzw
  and r1.xyzw, r0.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  ushr r0.xyzw, r0.xyzw, l(8, 8, 8, 8)
  and r0.xyzw, r0.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  iadd r2.xyz, vThreadIDInGroup.xxxx, l(16, 32, 48, 0)
  ld_structured r3.xyzw, r2.x, l(0), g1.xyzw
  and r4.xyzw, r3.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  iadd r1.xyzw, r1.xyzw, r4.xyzw
  ushr r3.xyzw, r3.xyzw, l(8, 8, 8, 8)
  and r3.xyzw, r3.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  iadd r0.xyzw, r0.xyzw, r3.xyzw
  ld_structured r3.xyzw, r2.y, l(0), g1.xyzw
  and r4.xyzw, r3.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  iadd r1.xyzw, r1.xyzw, r4.xyzw
  ushr r3.xyzw, r3.xyzw, l(8, 8, 8, 8)
  and r3.xyzw, r3.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  iadd r0.xyzw, r0.xyzw, r3.xyzw
  ld_structured r3.xyzw, r2.z, l(0), g1.xyzw
  and r4.xyzw, r3.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  iadd r1.xyzw, r1.xyzw, r4.xyzw
  ushr r3.xyzw, r3.xyzw, l(8, 8, 8, 8)
  and r3.xyzw, r3.xyzw, l(0x00ff00ff, 0x00ff00ff, 0x00ff00ff, 0x00ff00ff)
  iadd r0.xyzw, r0.xyzw, r3.xyzw
  store_structured g0.xyzw, vThreadIDInGroup.x, l(0), r1.xyzw
  store_structured g0.xyzw, r2.x, l(0), r0.xyzw
endif 
sync_g_t
ushr r0.x, vThreadIDInGroup.x, l(7)
and r0.y, vThreadIDInGroup.x, l(127)
ult r0.z, r0.y, l(4)
if_nz r0.z
  ishl r0.z, r0.x, l(8)
  ushr r0.zw, r0.zzzz, l(0, 0, 4, 6)
  iadd r0.zw, r0.zzzw, r0.yyyy
  ld_structured r1.xyzw, r0.z, l(0), g0.xyzw
  iadd r2.xyz, r0.zzzz, l(4, 8, 12, 0)
  ld_structured r3.xyzw, r2.x, l(0), g0.xyzw
  iadd r1.xyzw, r1.xyzw, r3.xyzw
  ld_structured r3.xyzw, r2.y, l(0), g0.xyzw
  iadd r1.xyzw, r1.xyzw, r3.xyzw
  ld_structured r2.xyzw, r2.z, l(0), g0.xyzw
  iadd r1.xyzw, r1.xyzw, r2.xyzw
  store_structured g1.xyzw, r0.w, l(0), r1.xyzw
endif 
sync_g_t
if_z r0.y
  ishl r0.yz, r0.xxxx, l(0, 8, 3, 0)
  ushr r0.y, r0.y, l(6)
  ld_structured r1.xyzw, r0.y, l(0), g1.xyzw
  iadd r2.xyz, r0.yyyy, l(1, 2, 3, 0)
  ld_structured r3.xyzw, r2.x, l(0), g1.xyzw
  iadd r1.xyzw, r1.xyzw, r3.xyzw
  ld_structured r3.xyzw, r2.y, l(0), g1.xyzw
  iadd r1.xyzw, r1.xyzw, r3.xyzw
  ld_structured r2.xyzw, r2.z, l(0), g1.xyzw
  iadd r1.xyzw, r1.xyzw, r2.xyzw
  imad r0.y, r0.z, cb0[0].x, vThreadGroupID.x
  and r2.xyzw, r1.xyzw, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0x0000ffff)
  store_uav_typed u0.xyzw, r0.yyyy, r2.xxxx
  imad r3.xyzw, r0.xxxx, l(8, 8, 8, 8), l(1, 2, 3, 4)
  imad r4.xyzw, r3.xyzw, cb0[0].xxxx, vThreadGroupID.xxxx
  ushr r1.xyzw, r1.xyzw, l(16, 16, 16, 16)
  store_uav_typed u0.xyzw, r4.xxxx, r1.xxxx
  store_uav_typed u0.xyzw, r4.yyyy, r2.yyyy
  store_uav_typed u0.xyzw, r4.zzzz, r1.yyyy
  store_uav_typed u0.xyzw, r4.wwww, r2.zzzz
  imad r0.xyw, r0.xxxx, l(8, 8, 0, 8), l(5, 6, 0, 7)
  imad r4.xyz, r0.xywx, cb0[0].xxxx, vThreadGroupID.xxxx
  store_uav_typed u0.xyzw, r4.xxxx, r1.zzzz
  store_uav_typed u0.xyzw, r4.yyyy, r2.wwww
  store_uav_typed u0.xyzw, r4.zzzz, r1.wwww
  iadd r4.x, vThreadGroupID.x, cb0[0].x
  bfi r0.z, l(28), l(4), r4.x, r0.z
  store_uav_typed u0.xyzw, r0.zzzz, r2.xxxx
  bfi r3.xyzw, l(28, 28, 28, 28), l(4, 4, 4, 4), r4.xxxx, r3.xyzw
  store_uav_typed u0.xyzw, r3.xxxx, r1.xxxx
  store_uav_typed u0.xyzw, r3.yyyy, r2.yyyy
  store_uav_typed u0.xyzw, r3.zzzz, r1.yyyy
  store_uav_typed u0.xyzw, r3.wwww, r2.zzzz
  bfi r0.xyz, l(28, 28, 28, 0), l(4, 4, 4, 0), r4.xxxx, r0.xywx
  store_uav_typed u0.xyzw, r0.xxxx, r1.zzzz
  store_uav_typed u0.xyzw, r0.yyyy, r2.wwww
  store_uav_typed u0.xyzw, r0.zzzz, r1.wwww
endif 
ret 
// Approximately 238 instruction slots used
