//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer params
// {
//
//   uint3 gridDim;                     // Offset:    0 Size:    12 [unused]
//   uint passStart;                    // Offset:   12 Size:     4 [unused]
//   uint numCounters;                  // Offset:   16 Size:     4 [unused]
//   uint numKeys;                      // Offset:   20 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// srcKey                            texture   uint4         buf             t0      1 
// srcVal                            texture   uint4         buf             t1      1 
// dstKey                                UAV   uint4         buf             u0      1 
// dstVal                                UAV   uint4         buf             u1      1 
// params                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_buffer (uint,uint,uint,uint) t0
dcl_resource_buffer (uint,uint,uint,uint) t1
dcl_uav_typed_buffer (uint,uint,uint,uint) u0
dcl_uav_typed_buffer (uint,uint,uint,uint) u1
dcl_input vThreadIDInGroup.x
dcl_input vThreadID.x
dcl_temps 14
dcl_tgsm_structured g0, 4, 1024
dcl_tgsm_structured g1, 4, 1024
dcl_tgsm_structured g2, 4, 256
dcl_tgsm_structured g3, 4, 256
dcl_thread_group 256, 1, 1
ld_indexable(buffer)(uint,uint,uint,uint) r0.xyzw, vThreadID.xxxx, t0.xyzw
ishl r1.x, vThreadID.x, l(2)
uge r1.x, r1.x, cb0[1].y
movc r0.x, r1.x, l(-1), r0.x
imad r1.xyz, vThreadID.xxxx, l(4, 4, 4, 0), l(1, 2, 3, 0)
uge r1.xyz, r1.xyzx, cb0[1].yyyy
movc r0.yzw, r1.xxyz, l(0,-1,-1,-1), r0.yyzw
ld_indexable(buffer)(uint,uint,uint,uint) r1.xyzw, vThreadID.xxxx, t1.xyzw
uge r2.xyzw, vThreadIDInGroup.xxxx, l(1, 2, 3, 4)
iadd r3.xyzw, vThreadIDInGroup.xxxx, l(-1, -2, -3, -4)
uge r4.xyzw, vThreadIDInGroup.xxxx, l(8, 12, 16, 32)
iadd r5.xyzw, vThreadIDInGroup.xxxx, l(-8, -12, -16, -32)
uge r6.xyzw, vThreadIDInGroup.xxxx, l(48, 64, 128, 192)
ishl r7.x, vThreadIDInGroup.x, l(2)
iadd r8.xyzw, vThreadIDInGroup.xxxx, l(-48, -64, -128, -192)
imad r7.yzw, vThreadIDInGroup.xxxx, l(0, 4, 4, 4), l(0, 1, 2, 3)
mov r9.xyzw, r0.xyzw
mov r10.xyzw, r1.xyzw
mov r11.x, l(0)
loop 
  uge r11.y, r11.x, l(32)
  breakc_nz r11.y
  ushr r12.xyzw, r9.xyzw, r11.xxxx
  and r12.xyzw, r12.xyzw, l(1, 1, 1, 1)
  xor r12.xyzw, r12.xyzw, l(1, 1, 1, 1)
  iadd r11.y, r12.y, r12.x
  iadd r11.y, r12.z, r11.y
  iadd r11.y, r12.w, r11.y
  store_structured g2.x, vThreadIDInGroup.x, l(0), r11.y
  sync_g_t
  if_nz r2.x
    ld_structured r11.z, r3.x, l(0), g2.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r2.y
    ld_structured r11.z, r3.y, l(0), g2.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r2.z
    ld_structured r11.z, r3.z, l(0), g2.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  store_structured g3.x, vThreadIDInGroup.x, l(0), r11.y
  sync_g_t
  if_nz r2.w
    ld_structured r11.z, r3.w, l(0), g3.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r4.x
    ld_structured r11.z, r5.x, l(0), g3.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r4.y
    ld_structured r11.z, r5.y, l(0), g3.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  store_structured g2.x, vThreadIDInGroup.x, l(0), r11.y
  sync_g_t
  if_nz r4.z
    ld_structured r11.z, r5.z, l(0), g2.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r4.w
    ld_structured r11.z, r5.w, l(0), g2.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r6.x
    ld_structured r11.z, r8.x, l(0), g2.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  store_structured g3.x, vThreadIDInGroup.x, l(0), r11.y
  sync_g_t
  if_nz r6.y
    ld_structured r11.z, r8.y, l(0), g3.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r6.z
    ld_structured r11.z, r8.z, l(0), g3.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  if_nz r6.w
    ld_structured r11.z, r8.w, l(0), g3.xxxx
    iadd r11.y, r11.z, r11.y
  endif 
  iadd r11.z, -r12.w, r11.y
  iadd r11.w, -r12.z, r11.z
  iadd r13.x, -r12.y, r11.w
  ld_structured r13.y, l(63), l(0), g3.xxxx
  ld_structured r13.z, l(127), l(0), g3.xxxx
  iadd r13.y, r13.z, r13.y
  ld_structured r13.z, l(191), l(0), g3.xxxx
  iadd r13.y, r13.z, r13.y
  ld_structured r13.z, l(255), l(0), g3.xxxx
  iadd r13.y, r13.z, r13.y
  iadd r13.z, r13.x, l(-1)
  iadd r13.x, r7.x, -r13.x
  iadd r13.x, r13.y, r13.x
  movc r12.x, r12.x, r13.z, r13.x
  iadd r13.x, r11.w, l(-1)
  iadd r11.w, r7.y, -r11.w
  iadd r11.w, r13.y, r11.w
  movc r11.w, r12.y, r13.x, r11.w
  iadd r12.y, r11.z, l(-1)
  iadd r11.z, r7.z, -r11.z
  iadd r11.z, r13.y, r11.z
  movc r11.z, r12.z, r12.y, r11.z
  iadd r12.y, r11.y, l(-1)
  iadd r11.y, r7.w, -r11.y
  iadd r11.y, r13.y, r11.y
  movc r11.y, r12.w, r12.y, r11.y
  store_structured g0.x, r12.x, l(0), r9.x
  store_structured g0.x, r11.w, l(0), r9.y
  store_structured g0.x, r11.z, l(0), r9.z
  store_structured g0.x, r11.y, l(0), r9.w
  store_structured g1.x, r12.x, l(0), r10.x
  store_structured g1.x, r11.w, l(0), r10.y
  store_structured g1.x, r11.z, l(0), r10.z
  store_structured g1.x, r11.y, l(0), r10.w
  sync_g_t
  ld_structured r9.x, r7.x, l(0), g0.xxxx
  ld_structured r9.y, r7.y, l(0), g0.xxxx
  ld_structured r9.z, r7.z, l(0), g0.xxxx
  ld_structured r9.w, r7.w, l(0), g0.xxxx
  ld_structured r10.x, r7.x, l(0), g1.xxxx
  ld_structured r10.y, r7.y, l(0), g1.xxxx
  ld_structured r10.z, r7.z, l(0), g1.xxxx
  ld_structured r10.w, r7.w, l(0), g1.xxxx
  iadd r11.x, r11.x, l(1)
endloop 
store_uav_typed u0.xyzw, vThreadID.xxxx, r9.xyzw
store_uav_typed u1.xyzw, vThreadID.xxxx, r10.xyzw
ret 
// Approximately 132 instruction slots used
