//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.2.45 on Wed Apr 29 23:32:46 2026
//
//
// Buffer Definitions: 
//
// cbuffer params
// {
//
//   uint3 gridDim;                     // Offset:    0 Size:    12 [unused]
//   uint passStart;                    // Offset:   12 Size:     4 [unused]
//   uint numCounters;                  // Offset:   16 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// countersSrc                       texture   uint4         buf             t0      1 
// countersDst                           UAV   uint4         buf             u0      1 
// params                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_buffer (uint,uint,uint,uint) t0
dcl_uav_typed_buffer (uint,uint,uint,uint) u0
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 6
dcl_tgsm_structured g0, 4, 256
dcl_tgsm_structured g1, 4, 256
dcl_thread_group 256, 1, 1
if_z vThreadGroupID.x
  ushr r0.x, cb0[1].x, l(2)
  iadd r0.y, r0.x, l(255)
  ushr r0.y, r0.y, l(8)
  mov r0.z, vThreadIDInGroup.x
  mov r0.w, l(0)
  mov r1.x, vThreadIDInGroup.x
  mov r1.y, l(0)
  loop 
    uge r1.z, r1.y, r0.y
    breakc_nz r1.z
    ult r1.z, r1.x, r0.x
    ld_indexable(buffer)(uint,uint,uint,uint) r2.xyzw, r1.xxxx, t0.xyzw
    and r2.xyzw, r1.zzzz, r2.wzyx
    iadd r1.w, r2.z, r2.w
    iadd r1.w, r2.y, r1.w
    iadd r1.w, r2.x, r1.w
    store_structured g0.x, r0.z, l(0), r1.w
    sync_g_t
    uge r3.xyzw, r0.zzzz, l(1, 2, 3, 4)
    if_nz r3.x
      iadd r3.x, r0.z, l(-1)
      ld_structured r3.x, r3.x, l(0), g0.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    if_nz r3.y
      iadd r3.x, r0.z, l(-2)
      ld_structured r3.x, r3.x, l(0), g0.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    if_nz r3.z
      iadd r3.x, r0.z, l(-3)
      ld_structured r3.x, r3.x, l(0), g0.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    store_structured g1.x, r0.z, l(0), r1.w
    sync_g_t
    if_nz r3.w
      iadd r3.x, r0.z, l(-4)
      ld_structured r3.x, r3.x, l(0), g1.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    uge r3.xyzw, r0.zzzz, l(8, 12, 16, 32)
    if_nz r3.x
      iadd r3.x, r0.z, l(-8)
      ld_structured r3.x, r3.x, l(0), g1.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    if_nz r3.y
      iadd r3.x, r0.z, l(-12)
      ld_structured r3.x, r3.x, l(0), g1.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    store_structured g0.x, r0.z, l(0), r1.w
    sync_g_t
    if_nz r3.z
      iadd r3.x, r0.z, l(-16)
      ld_structured r3.x, r3.x, l(0), g0.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    if_nz r3.w
      iadd r3.x, r0.z, l(-32)
      ld_structured r3.x, r3.x, l(0), g0.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    uge r3.xyzw, r0.zzzz, l(48, 64, 128, 192)
    if_nz r3.x
      iadd r3.x, r0.z, l(-48)
      ld_structured r3.x, r3.x, l(0), g0.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    store_structured g1.x, r0.z, l(0), r1.w
    sync_g_t
    if_nz r3.y
      iadd r3.x, r0.z, l(-64)
      ld_structured r3.x, r3.x, l(0), g1.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    if_nz r3.z
      iadd r3.x, r0.z, l(-128)
      ld_structured r3.x, r3.x, l(0), g1.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    if_nz r3.w
      iadd r3.x, r0.z, l(-192)
      ld_structured r3.x, r3.x, l(0), g1.xxxx
      iadd r1.w, r1.w, r3.x
    endif 
    ld_structured r3.x, l(63), l(0), g1.xxxx
    ld_structured r3.y, l(127), l(0), g1.xxxx
    iadd r3.x, r3.y, r3.x
    ld_structured r3.y, l(191), l(0), g1.xxxx
    iadd r3.x, r3.y, r3.x
    ld_structured r3.y, l(255), l(0), g1.xxxx
    iadd r3.x, r3.y, r3.x
    if_nz r1.z
      iadd r1.z, -r2.x, r1.w
      iadd r1.w, -r2.y, r1.z
      iadd r2.x, -r2.z, r1.w
      iadd r2.y, -r2.w, r2.x
      iadd r4.xy, r0.wwww, r2.yxyy
      iadd r4.zw, r0.wwww, r1.wwwz
      store_uav_typed u0.xyzw, r1.xxxx, r4.xyzw
    endif 
    iadd r0.w, r0.w, r3.x
    iadd r1.xy, r1.xyxx, l(256, 1, 0, 0)
  endloop 
else 
  ushr r0.x, cb0[1].x, l(2)
  iadd r0.y, r0.x, l(255)
  ushr r0.y, r0.y, l(8)
  and r0.zw, vThreadIDInGroup.xxxx, l(0, 0, 3, 252)
  uge r1.xyz, r0.zzzz, l(1, 2, 3, 0)
  bfi r2.xy, l(2, 2, 0, 0), l(0, 0, 0, 0), l(1, 2, 0, 0), vThreadIDInGroup.xxxx
  mov r0.z, vThreadIDInGroup.x
  mov r1.w, l(0)
  loop 
    uge r2.z, r1.w, r0.y
    breakc_nz r2.z
    ult r2.z, r0.z, r0.x
    iadd r2.w, r0.x, r0.z
    ld_indexable(buffer)(uint,uint,uint,uint) r3.xyzw, r2.wwww, t0.xyzw
    and r3.xyzw, r2.zzzz, r3.xyzw
    iadd r4.x, r3.y, r3.x
    iadd r4.y, r3.z, r4.x
    iadd r3.w, r3.w, r4.y
    store_structured g0.x, vThreadIDInGroup.x, l(0), r3.w
    sync_g_t
    if_nz r1.x
      ld_structured r5.x, r0.w, l(0), g0.xxxx
    else 
      mov r5.x, l(0)
    endif 
    if_nz r1.y
      ld_structured r3.w, r2.x, l(0), g0.xxxx
      iadd r5.x, r3.w, r5.x
    endif 
    if_nz r1.z
      ld_structured r3.w, r2.y, l(0), g0.xxxx
      iadd r5.x, r3.w, r5.x
    endif 
    if_nz r2.z
      iadd r2.z, r3.y, r3.z
      iadd r2.z, r3.x, r2.z
      iadd r5.w, r5.x, r2.z
      iadd r5.z, r4.x, r5.x
      iadd r5.y, r3.x, r5.x
      store_uav_typed u0.xyzw, r2.wwww, r5.xyzw
    endif 
    iadd r0.z, r0.z, l(256)
    iadd r1.w, r1.w, l(1)
  endloop 
endif 
ret 
// Approximately 154 instruction slots used
