set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

get_filename_component(
    NVFLEX_SOURCE_ROOT
    "${CMAKE_CURRENT_LIST_DIR}/../.."
    ABSOLUTE)

if(DEFINED ENV{NVFLEX_TOOLCHAIN_ROOT})
    set(NVFLEX_TOOLCHAIN_ROOT "$ENV{NVFLEX_TOOLCHAIN_ROOT}")
else()
    set(NVFLEX_TOOLCHAIN_ROOT "${NVFLEX_SOURCE_ROOT}/.toolchains")
endif()
set(NVFLEX_TOOLCHAIN_ROOT "${NVFLEX_TOOLCHAIN_ROOT}" CACHE PATH
    "Root containing local FleX Windows cross-build support files")

if(DEFINED ENV{NVFLEX_WINEPREFIX})
    set(NVFLEX_WINEPREFIX "$ENV{NVFLEX_WINEPREFIX}")
elseif(DEFINED ENV{HOME})
    set(NVFLEX_WINEPREFIX "$ENV{HOME}/.wineprefixes/dev-x64")
else()
    message(FATAL_ERROR
        "Unable to determine the Wine prefix; set NVFLEX_WINEPREFIX.")
endif()
set(NVFLEX_WINEPREFIX "${NVFLEX_WINEPREFIX}" CACHE PATH
    "Win64 Wine prefix containing MSVC and the Windows SDK")

if(DEFINED ENV{NVFLEX_MSVC_ROOT})
    set(NVFLEX_MSVC_ROOT "$ENV{NVFLEX_MSVC_ROOT}")
else()
    set(NVFLEX_MSVC_ROOT
        "${NVFLEX_WINEPREFIX}/drive_c/Program Files/Microsoft Visual Studio/2022/BuildTools")
endif()
if(DEFINED ENV{NVFLEX_WINDOWS_SDK_ROOT})
    set(NVFLEX_WINDOWS_SDK_ROOT "$ENV{NVFLEX_WINDOWS_SDK_ROOT}")
else()
    set(NVFLEX_WINDOWS_SDK_ROOT
        "${NVFLEX_WINEPREFIX}/drive_c/Program Files (x86)/Windows Kits/10")
endif()

file(GLOB NVFLEX_MSVC_TOOLSETS
    "${NVFLEX_MSVC_ROOT}/VC/Tools/MSVC/14.44.*")
file(GLOB NVFLEX_SDK_INCLUDES
    "${NVFLEX_WINDOWS_SDK_ROOT}/Include/10.0.26100.*")
file(GLOB NVFLEX_FXC_EXECUTABLES
    "${NVFLEX_WINDOWS_SDK_ROOT}/bin/10.0.26100.*/x64/fxc.exe")
list(SORT NVFLEX_MSVC_TOOLSETS COMPARE NATURAL ORDER DESCENDING)
list(SORT NVFLEX_SDK_INCLUDES COMPARE NATURAL ORDER DESCENDING)
list(SORT NVFLEX_FXC_EXECUTABLES COMPARE NATURAL ORDER DESCENDING)
if(NVFLEX_MSVC_TOOLSETS)
    list(GET NVFLEX_MSVC_TOOLSETS 0 NVFLEX_MSVC_TOOLSET)
endif()
if(NVFLEX_SDK_INCLUDES)
    list(GET NVFLEX_SDK_INCLUDES 0 NVFLEX_SDK_INCLUDE)
endif()
if(NVFLEX_FXC_EXECUTABLES)
    list(GET NVFLEX_FXC_EXECUTABLES 0 NVFLEX_FXC_EXECUTABLE)
endif()

if(NOT NVFLEX_MSVC_TOOLSET OR NOT NVFLEX_SDK_INCLUDE OR
        NOT NVFLEX_FXC_EXECUTABLE)
    message(FATAL_ERROR
        "Missing FleX Windows cross-toolchain files in ${NVFLEX_WINEPREFIX}.\n"
        "Run Tools/wine/bootstrap-toolchain.sh --check, or provision them "
        "with --install --accept-msvc-license.")
endif()

set(CMAKE_C_COMPILER "${NVFLEX_SOURCE_ROOT}/Tools/wine/clang-cl.sh")
set(CMAKE_CXX_COMPILER "${NVFLEX_SOURCE_ROOT}/Tools/wine/clang-cl.sh")
set(CMAKE_LINKER "${NVFLEX_SOURCE_ROOT}/Tools/wine/lld-link.sh")
set(CMAKE_AR "${NVFLEX_SOURCE_ROOT}/Tools/wine/llvm-lib.sh")
set(CMAKE_RC_COMPILER "${NVFLEX_SOURCE_ROOT}/Tools/wine/llvm-rc.sh")
set(CMAKE_MT "${NVFLEX_SOURCE_ROOT}/Tools/wine/llvm-mt.sh")

set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDLL)
set(CMAKE_MAP_IMPORTED_CONFIG_DEBUG Release "")
set(CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release "")

set(CMAKE_C_FLAGS_DEBUG_INIT "/Od /Ob0 -gdwarf")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "/Od /Ob0 -gdwarf")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "/debug:dwarf")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT "/debug:dwarf")

set(NVFLEX_WINDOWS_CLANG_CROSS ON CACHE BOOL
    "Build x64 Windows FleX binaries with host clang-cl and lld-link")
set(NVFLEX_SHADER_TOOL_EMULATOR
    "${NVFLEX_SOURCE_ROOT}/Tools/wine/wine-shader-tool.sh"
    CACHE FILEPATH "Wine emulator and path translator for ShaderTool.exe")
set(FXC_COMPILER "${NVFLEX_FXC_EXECUTABLE}" CACHE FILEPATH
    "Windows SDK FXC executable run by ShaderTool.exe" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    NVFLEX_WINEPREFIX
    NVFLEX_MSVC_ROOT
    NVFLEX_WINDOWS_SDK_ROOT
    NVFLEX_WINDOWS_CLANG_CROSS)
